// ===================================================================================
// Author        : System
// Created date  : 10 Apr 2016 13:23:48
// Description   : vRoutePlanCustomerDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vRoutePlanCustomerDataProvider : DefaultViewDataProvider<vRoutePlanCustomer>, IvRoutePlanCustomerDataProvider
    {
        
        #region Methods

        protected override void OnInsertData(vRoutePlanCustomer obj)
        {
            
        }

        protected override void OnUpdateData(vRoutePlanCustomer obj)
        {
            
        }

        protected override void OnDeleteData(vRoutePlanCustomer obj)
        {
            
        }

        #endregion
        
    }

}
