// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:14
// Description   : DiscountGroupProductDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
using Dismoyo.Data;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class DiscountGroupProductDataProvider : DefaultTableDataProvider<DiscountGroupProduct>, IDiscountGroupProductDataProvider
    {

        #region Methods

        public IList<DiscountGroupProduct> GetDataByDiscountGroupID(int discountGroupID)
        {
            var discountGroupProducts = GetData().Where(p => p.DiscountGroupID.Equals(discountGroupID)).ToList();

            return discountGroupProducts;
        }

        #endregion

    }

}
