// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12::51:33
// Description   : vMerchandiseDisplayActivityDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vMerchandiseDisplayActivityDataProvider : DefaultViewDataProvider<vMerchandiseDisplayActivity>, IvMerchandiseDisplayActivityDataProvider
    {

        #region Methods
        protected override void OnInsertData(vMerchandiseDisplayActivity obj, bool useTransaction)
        {
            var merchandiseDisplayActivityDataProvider = DataConfiguration.GetDefaultDataProvider<IMerchandiseDisplayActivityDataProvider>();

            var merchandiseDisplayActivity = new MerchandiseDisplayActivity();

            merchandiseDisplayActivity.ID = (obj.ID.Equals(Guid.Empty) ? Guid.NewGuid() : obj.ID);
            merchandiseDisplayActivity.ActivityDate = obj.ActivityDate;
            merchandiseDisplayActivity.SalesmanCallID = obj.SalesmanCallID;
            merchandiseDisplayActivity.AttachmentFile = obj.AttachmentFile;

            merchandiseDisplayActivityDataProvider.InsertData(merchandiseDisplayActivity, useTransaction);
        }

        protected override void OnUpdateData(vMerchandiseDisplayActivity obj, bool useTransaction)
        {
            var merchandiseDisplayActivityDataProvider = DataConfiguration.GetDefaultDataProvider<IMerchandiseDisplayActivityDataProvider>();

            var merchandiseDisplayActivity = merchandiseDisplayActivityDataProvider.GetData(obj.ID);

            merchandiseDisplayActivity.ActivityDate = obj.ActivityDate;
            merchandiseDisplayActivity.SalesmanCallID = obj.SalesmanCallID;
            merchandiseDisplayActivity.AttachmentFile = obj.AttachmentFile;

            merchandiseDisplayActivityDataProvider.UpdateData(merchandiseDisplayActivity, useTransaction);
        }

        #endregion

    }

}
