// ===================================================================================
// Author        : System
// Created date  : 18 Mar 2016 00:00:00
// Description   : DataService partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Dismoyo.Ciptoning.Data;
using System;
using System.Data.Services;
using System.Data.Services.Providers;
using System.Linq;
using System.Linq.Expressions;
using System.ServiceModel.Web;

namespace Dismoyo.Ciptoning.Web.Services
{

    public partial class DataService : EntityFrameworkDataService<StoreFunctionsDataContext>, IServiceProvider
    {

        #region Methods

        [QueryInterceptor("vSalesOrderSwapSummaries")]
        public Expression<Func<vSalesOrderSwapSummary, bool>> OnQueryvSalesOrderSwapSummaries()
        {
            return (p => true);
        }

        [ChangeInterceptor("vSalesOrderSwapSummaries")]
        public void OnChangevSalesOrderSwapSummaries(vSalesOrderSwapSummary data, UpdateOperations operations)
        {
            if (ValidateSegment("vSalesOrderSwapSummaries"))
            {
                var dataProvider = DataConfiguration.GetDefaultDataProvider<IvSalesOrderSwapSummaryDataProvider>();

                switch (operations)
                {
                    case UpdateOperations.Add:
                        dataProvider.InsertData(data);
                        operations = UpdateOperations.None;
                        break;
                    case UpdateOperations.Change:
                        dataProvider.UpdateData(data);
                        operations = UpdateOperations.None;
                        break;
                    case UpdateOperations.Delete:
                        dataProvider.DeleteData(data);
                        operations = UpdateOperations.None;
                        break;
                }

                if (operations == UpdateOperations.None)
                    CancelChanges();
            }
        }

        #endregion

        #region Custom Methods

        [WebGet]
        public IQueryable<vSalesOrderSwapSummary> fSalesOrderSwapSummaries()
        {
            return CurrentDataSource.fSalesOrderSwapSummary(
                (Guid?)GetQueryFilterParameterValue("DocumentID"),
                (int?)GetQueryFilterParameterValue("ProductID"),
                (string)GetQueryFilterParameterValue("ProductCode"),
                (string)GetQueryFilterParameterValue("ProductName"),
                (int?)GetQueryFilterParameterValue("ProductBrandID"),
                (string)GetQueryFilterParameterValue("ProductBrandCode"),
                (string)GetQueryFilterParameterValue("ProductBrandName"),
                (string)GetQueryFilterParameterValue("ProductShortName"),
                (int?)GetQueryFilterParameterValue("ProductStatusID"),
                (string)GetQueryFilterParameterValue("ProductAdditionalInfo"));
        }

        #endregion

    }

}
