// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:57
// Description   : vUserRolePermissionEntityTypeConfig partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Data.Entity.ModelConfiguration;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vUserRolePermissionEntityTypeConfig : EntityTypeConfiguration<vUserRolePermission>
    {

        #region Constructors

        public vUserRolePermissionEntityTypeConfig()
        {
            HasRequired(p => p.ParentPermissionObject)
                .WithMany(q => q.ChildUserRolePermissions)
                .HasForeignKey(p => p.PermissionObjectID);
        }

        #endregion

    }

}
