// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:57
// Description   : vUserPermissionAllEntityTypeConfig partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Data.Entity.ModelConfiguration;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vUserPermissionAllEntityTypeConfig : EntityTypeConfiguration<vUserPermissionAll>
    {

        #region Constructors

        public vUserPermissionAllEntityTypeConfig()
        {
            HasRequired(p => p.ParentUser)
                .WithMany(q => q.ChildPermissions)
                .HasForeignKey(p => p.UserID);
        }

        #endregion

    }

}
