// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:57
// Description   : vUserPermissionAllDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Dismoyo.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vUserPermissionAllDataProvider : DefaultViewDataProvider<vUserPermissionAll>, IvUserPermissionAllDataProvider
    {

        #region Methods
        public IList<vUserPermissionAll> GetDataByUserID(int userID)
        {
            var userPermissionAlls = GetData().Where(p => p.UserID == userID).ToList();
            
            return userPermissionAlls;
        }

        #endregion

    }

}
