// ===================================================================================
// Author        : System
// Created date  : 15 Mar 2016 15:24:42
// Description   : vSalesmanProductDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vSalesmanProductDataProvider : DefaultViewDataProvider<vSalesmanProduct>, IvSalesmanProductDataProvider
    {
        
        #region Methods

        protected override void OnInsertData(vSalesmanProduct obj, bool useTransaction)
        {
            var salesmanProductDataProvider = DataConfiguration.GetDefaultDataProvider<ISalesmanProductDataProvider>();

            var existingProduct = salesmanProductDataProvider.GetData(obj.SalesmanID, obj.ProductID);
            if (existingProduct == null)
            {
                var salesmanProduct = new SalesmanProduct();

                salesmanProduct.SalesmanID = obj.SalesmanID;
                salesmanProduct.ProductID = obj.ProductID;

                salesmanProductDataProvider.InsertData(salesmanProduct, useTransaction);
            }
        }

        protected override void OnUpdateData(vSalesmanProduct obj, bool useTransaction)
        {
            var salesmanProductDataProvider = DataConfiguration.GetDefaultDataProvider<ISalesmanProductDataProvider>();
            
            var salesmanProduct = salesmanProductDataProvider.GetData(obj.SalesmanID, obj.ProductID);

            salesmanProduct.ProductID = obj.ProductID;

            salesmanProductDataProvider.UpdateData(salesmanProduct, useTransaction);
        }

        protected override void OnDeleteData(vSalesmanProduct obj, bool useTransaction)
        {
            var salesmanProductDataProvider = DataConfiguration.GetDefaultDataProvider<ISalesmanProductDataProvider>();

            var salesmanProduct = salesmanProductDataProvider.GetData(obj.SalesmanID, obj.ProductID);

            salesmanProductDataProvider.DeleteData(salesmanProduct, useTransaction);
        }

        #endregion
        
    }

}
