// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:14
// Description   : StockDisposalSummaryDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
using Dismoyo.Data;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class StockDisposalSummaryDataProvider : DefaultTableDataProvider<StockDisposalSummary>, IStockDisposalSummaryDataProvider
    {

        #region Methods

        public IList<StockDisposalSummary> GetDataByDocumentID(Guid documentID)
        {
            var stockDisposalDetails = GetData().Where(p => p.DocumentID.Equals(documentID)).ToList();

            return stockDisposalDetails;
        }


        public override void DeleteData(StockDisposalSummary obj, bool useTransaction)
        {
            var stockDisposalDetailsDataProvider =
                DataConfiguration.GetDefaultDataProvider<IStockDisposalDetailsDataProvider>();

            var deleteChilds = stockDisposalDetailsDataProvider.GetDataByDocumentIDAndProductID(
                obj.DocumentID, obj.ProductID);
            foreach (var child in deleteChilds)
                stockDisposalDetailsDataProvider.DeleteData(child, useTransaction);

            base.DeleteData(obj, useTransaction);
        }

        #endregion

    }

}
