// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:57
// Description   : vSalesOrderFOCDetailsDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vSalesOrderFOCDetailsDataProvider : DefaultViewDataProvider<vSalesOrderFOCDetails>, IvSalesOrderFOCDetailsDataProvider
    {

        #region Methods

        protected override void OnInsertData(vSalesOrderFOCDetails obj, bool useTransaction)
        {
            var salesOrderFOCDetailsDataProvider = DataConfiguration.GetDefaultDataProvider<ISalesOrderFOCDetailsDataProvider>();

            var salesOrderFOCDetails = new SalesOrderFOCDetails();

            salesOrderFOCDetails.DocumentID = obj.DocumentID;
            salesOrderFOCDetails.ProductID = obj.ProductID;
            salesOrderFOCDetails.ProductLotID = obj.ProductLotID;

            salesOrderFOCDetails.QtyOnHand = obj.QtyOnHand;

            salesOrderFOCDetails.QtyConvL = obj.QtyConvL;
            salesOrderFOCDetails.QtyConvM = obj.QtyConvM;
            salesOrderFOCDetails.QtyConvS = obj.QtyConvS;

            salesOrderFOCDetails.Qty = obj.Qty;

            salesOrderFOCDetailsDataProvider.InsertData(salesOrderFOCDetails, useTransaction);
        }

        protected override void OnUpdateData(vSalesOrderFOCDetails obj, bool useTransaction)
        {
            var salesOrderFOCDetailsDataProvider = DataConfiguration.GetDefaultDataProvider<ISalesOrderFOCDetailsDataProvider>();

            var salesOrderFOCDetails = salesOrderFOCDetailsDataProvider.GetData(obj.DocumentID, obj.ProductID,
                obj.ProductLotID);

            salesOrderFOCDetails.QtyOnHand = obj.QtyOnHand;

            salesOrderFOCDetails.QtyConvL = obj.QtyConvL;
            salesOrderFOCDetails.QtyConvM = obj.QtyConvM;
            salesOrderFOCDetails.QtyConvS = obj.QtyConvS;

            salesOrderFOCDetails.Qty = obj.Qty;

            salesOrderFOCDetailsDataProvider.UpdateData(salesOrderFOCDetails, useTransaction);
        }

        #endregion

    }

}
