// ===================================================================================
// Author        : System
// Created date  : 10 Mar 2016 14:24:58
// Description   : SalesmanDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Dismoyo.Data;
using Dismoyo.Web.Security;
using System;
using System.Linq;
using System.Web;

namespace Dismoyo.Ciptoning.Data
{

    public partial class SalesmanDataProvider : DefaultTableDataProvider<Salesman>, ISalesmanDataProvider
    {
        
        #region Methods

        public Salesman GetDataByCode(string code)
        {
            var salesman = GetData().SingleOrDefault(p => p.Code.Equals(code, StringComparison.OrdinalIgnoreCase));

            return salesman;
        }


        protected override void OnBeginInsertData(BeginOperationDataEventArgs<Salesman> e)
        {
            e.Data.CreatedDate = DefaultDataContext.GetDBServerUtcDateTime();
            if (HttpContext.Current.User.Identity.IsAuthenticated)
                e.Data.CreatedByUserID = ((BasicGenericIdentity<IvUser>)HttpContext.Current.User.Identity).UserData.ID;

            base.OnBeginInsertData(e);
        }

        protected override void OnBeginUpdateData(BeginOperationDataEventArgs<Salesman> e)
        {
            e.Data.ModifiedDate = DefaultDataContext.GetDBServerUtcDateTime();
            if (HttpContext.Current.User.Identity.IsAuthenticated)
                e.Data.ModifiedByUserID = ((BasicGenericIdentity<IvUser>)HttpContext.Current.User.Identity).UserData.ID;

            base.OnBeginUpdateData(e);
        }

        #endregion

    }

}
