// ===================================================================================
// Author        : System
// Created date  : 02 Mei 2016 21:22:34
// Description   : ISystemParameterDataProvider partial interface.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using ISID.Data;

namespace AIO.IDOS2.Data
{

    public partial interface ISystemParameterDataProvider : IDataProvider<SystemParameter>
    {
        
        #region Methods

        SystemParameter GetDataByCode(string code);

        #endregion

    }

}
