// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:57
// Description   : vSalesOrderSwapDetailsDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vSalesOrderSwapDetailsDataProvider : DefaultViewDataProvider<vSalesOrderSwapDetails>, IvSalesOrderSwapDetailsDataProvider
    {

        #region Methods

        protected override void OnInsertData(vSalesOrderSwapDetails obj, bool useTransaction)
        {
            var salesOrderSwapDetailsDataProvider = DataConfiguration.GetDefaultDataProvider<ISalesOrderSwapDetailsDataProvider>();

            var salesOrderSwapDetails = new SalesOrderSwapDetails();

            salesOrderSwapDetails.DocumentID = obj.DocumentID;
            salesOrderSwapDetails.ProductID = obj.ProductID;
            salesOrderSwapDetails.ProductLotID = obj.ProductLotID;

            salesOrderSwapDetails.QtyOnHand = obj.QtyOnHand;

            salesOrderSwapDetails.QtyConvL = obj.QtyConvL;
            salesOrderSwapDetails.QtyConvM = obj.QtyConvM;
            salesOrderSwapDetails.QtyConvS = obj.QtyConvS;

            salesOrderSwapDetails.Qty = obj.Qty;

            salesOrderSwapDetailsDataProvider.InsertData(salesOrderSwapDetails, useTransaction);
        }

        protected override void OnUpdateData(vSalesOrderSwapDetails obj, bool useTransaction)
        {
            var salesOrderSwapDetailsDataProvider = DataConfiguration.GetDefaultDataProvider<ISalesOrderSwapDetailsDataProvider>();

            var salesOrderSwapDetails = salesOrderSwapDetailsDataProvider.GetData(obj.DocumentID, obj.ProductID,
                obj.ProductLotID);

            salesOrderSwapDetails.QtyOnHand = obj.QtyOnHand;

            salesOrderSwapDetails.QtyConvL = obj.QtyConvL;
            salesOrderSwapDetails.QtyConvM = obj.QtyConvM;
            salesOrderSwapDetails.QtyConvS = obj.QtyConvS;

            salesOrderSwapDetails.Qty = obj.Qty;

            salesOrderSwapDetailsDataProvider.UpdateData(salesOrderSwapDetails, useTransaction);
        }

        #endregion

    }

}
