USE [IDOS];
GO

SET IDENTITY_INSERT [dbo].[Area] ON;
GO

INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (1, 'A001', 'PEMATANG SIANTAR', 1, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (2, 'A002', 'KISARAN', 1, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (3, 'A003', 'RANTAU PARAPAT', 1, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (4, 'A004', 'SIBOLGA', 1, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (5, 'A005', 'PADANG SIDEMPUAN', 1, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (6, 'A006', 'KABANJAHE', 1, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (7, 'A007', 'ACEH', 1, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (8, 'A008', 'LHOKSEUMAWE', 1, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (9, 'A009', 'MEULABOH', 1, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (10, 'A010', 'PEKANBARU', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (11, 'A011', 'RENGAT', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (12, 'A012', 'DUMAI', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (13, 'A013', 'TEMBILAHAN', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (14, 'A014', 'BENGKALIS', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (15, 'A015', 'SELAT PANJANG', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (16, 'A016', 'PADANG', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (17, 'A017', 'BUKIT TINGGI', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (18, 'A018', 'BATAM', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (19, 'A019', 'TANJUNG PINANG', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (20, 'A020', 'TANJUNG BALAI', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (21, 'A021', 'TANJUNG BATU', 2, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (22, 'A022', 'CILEGON', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (23, 'A023', 'KARAWANG', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (24, 'A024', 'PURWAKARTA', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (25, 'A025', 'TASIKMALAYA', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (26, 'A026', 'GARUT', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (27, 'A027', 'SUMEDANG', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (28, 'A028', 'BANJAR', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (29, 'A029', 'CIREBON', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (30, 'A030', 'JATIBARANG', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (31, 'A031', 'BOGOR', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (32, 'A032', 'SUKABUMI', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (33, 'A033', 'CIANJUR', 3, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (34, 'A034', 'PALEMBANG', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (35, 'A035', 'LUBUK LINGGAU', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (36, 'A036', 'BATURAJA', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (37, 'A037', 'LAHAT', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (38, 'A038', 'BANGKA', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (39, 'A039', 'JAMBI', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (40, 'A040', 'MUARA BUNGO', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (41, 'A041', 'SAROLANGUN', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (42, 'A042', 'BENGKULU', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (43, 'A043', 'LAMPUNG', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (44, 'A044', 'KOTA BUMI', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (45, 'A045', 'TULUNG BAWANG', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (46, 'A046', 'METRO', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (47, 'A047', 'BELITUNG', 4, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (48, 'A048', 'BOJONEGORO', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (49, 'A049', 'LAMONGAN', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (50, 'A050', 'MALANG', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (51, 'A051', 'PROBOLINGGO', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (52, 'A052', 'PASURUAN', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (53, 'A053', 'MADIUN', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (54, 'A054', 'PONOROGO', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (55, 'A055', 'KEDIRI', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (56, 'A056', 'JOMBANG', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (57, 'A057', 'MOJOKERTO', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (58, 'A058', 'TULUNG AGUNG', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (59, 'A059', 'BLITAR', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (60, 'A060', 'JEMBER', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (61, 'A061', 'LUMAJANG', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (62, 'A062', 'SITUBONDO', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (63, 'A063', 'BANYUWANGI', 5, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (64, 'A064', 'JAYAPURA', 6, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (65, 'A065', 'MERAUKE', 6, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (66, 'A066', 'MONOKWARI', 6, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (67, 'A067', 'SORONG', 6, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (68, 'A068', 'TIMIKA', 6, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (69, 'A069', 'NABIRE', 6, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (70, 'A070', 'BIAK', 6, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (71, 'A071', 'SERUI', 6, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (72, 'A072', 'KAIMANA', 6, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (73, 'A073', 'FAK FAK', 6, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (74, 'A074', 'JOGJAKARTA', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (75, 'A075', 'MAGELANG', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (76, 'A076', 'WONOSARI', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (77, 'A077', 'PURWOKERTO', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (78, 'A078', 'CILACAP', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (79, 'A079', 'BANJARNEGARA', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (80, 'A080', 'KEBUMEN', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (81, 'A081', 'TEGAL', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (82, 'A082', 'PEKALONGAN', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (83, 'A083', 'SOLO', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (84, 'A084', 'WONOGIRI', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (85, 'A085', 'KLATEN', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (86, 'A086', 'SRAGEN', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (87, 'A087', 'SEMARANG', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (88, 'A088', 'PATI', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (89, 'A089', 'PURWODADI', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (90, 'A090', 'KENDAL', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (91, 'A091', 'SEMARANG', 7, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (92, 'A092', 'KUPANG', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (93, 'A093', 'ALOR', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (94, 'A094', 'WAINGAPU', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (95, 'A095', 'ATAMBUA', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (96, 'A096', 'ENDE', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (97, 'A097', 'RUTENG', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (98, 'A098', 'LABUAN BAJO', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (99, 'A099', 'MAUMERE', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (100, 'A100', 'LEMBATA', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (101, 'A101', 'LOMBOK', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (102, 'A102', 'LOTIM', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (103, 'A103', 'LOTENG', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (104, 'A104', 'SUMBAWA', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (105, 'A105', 'BIMA', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (106, 'A106', 'DENPASAR', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (107, 'A107', 'NEGARA', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (108, 'A108', 'SINGARAJA', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (109, 'A109', 'KLUNGKUNG', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (110, 'A110', 'KARANGASEM', 8, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (111, 'A111', 'BANJARMASIN', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (112, 'A112', 'BANJARBARU', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (113, 'A113', 'KOTABARU', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (114, 'A114', 'BARABAI', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (115, 'A115', 'AMPAH', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (116, 'A116', 'BATULICIN', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (117, 'A117', 'SAMARINDA', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (118, 'A118', 'BONTANG', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (119, 'A119', 'BERAU', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (120, 'A120', 'SANGATTA', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (121, 'A121', 'TARAKAN', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (122, 'A122', 'MELAK', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (123, 'A123', 'NUNUKAN', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (124, 'A124', 'BALIKPAPAN', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (125, 'A125', 'TANAH GROGOT', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (126, 'A126', 'PONTIANAK', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (127, 'A127', 'SANGGAU', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (128, 'A128', 'SINGKAWANG', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (129, 'A129', 'KETAPANG', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (130, 'A130', 'PALANGKARAYA', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (131, 'A131', 'SAMPIT', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (132, 'A132', 'PANGKALANBUN', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (133, 'A133', 'BARABAI', 9, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (134, 'A134', 'MAKASSAR', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (135, 'A135', 'PARE-PARE', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (136, 'A136', 'PALOPO', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (137, 'A137', 'MANGKUTANA', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (138, 'A138', 'BONE', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (139, 'A139', 'BULUKUMBA', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (140, 'A140', 'TORAJA', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (141, 'A141', 'MAMUJU', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (142, 'A142', 'POLMAN', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (143, 'A143', 'MANADO', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (144, 'A144', 'GORONTALO', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (145, 'A145', 'KENDARI', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (146, 'A146', 'KOLAKA', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (147, 'A147', 'BAU-BAU', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (148, 'A148', 'PALU', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (149, 'A149', 'TOLI-TOLI', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (150, 'A150', 'LUWUK', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (151, 'A151', 'POSO', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (152, 'A152', 'TERNATE', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (153, 'A153', 'HALMAHERA', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (154, 'A154', 'AMBON', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (155, 'A155', 'TUAL', 10, DEFAULT, NULL, NULL, NULL, 0);
INSERT INTO [dbo].[Area] ([ID], [Code], [Name], [RegionID], [CreatedDate], [CreatedByUserID], [ModifiedDate], [ModifiedByUserID], [IsDeleted]) VALUES (156, 'A156', 'SAUMLAKI', 10, DEFAULT, NULL, NULL, NULL, 0);
GO

SET IDENTITY_INSERT [dbo].[Area] OFF;
GO
