USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fArea]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fArea];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:14:36
-- Description   : Provide function to retrieve [dbo].[Area] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fArea]
(
    @ID int,
    @Code nvarchar(10),
    @Name nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),
    @IsDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [A].[ID],
            [A].[Code],
            [A].[Name],
            [dbo].[fCodeNameFormatter]([A].[Code], [A].[Name]) [Area],
            [A].[RegionID],
            [fR].[Code] [RegionCode],
            [fR].[Name] [RegionName],
            [fR].[Region],
            [fR].[TerritoryID],
            [fR].[TerritoryCode],
            [fR].[TerritoryName],
            [fR].[Territory],
            [A].[CreatedDate],
            [A].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [A].[ModifiedDate],
            [A].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [A].[IsDeleted]
        FROM
			[dbo].[Area] [A] INNER JOIN
            [dbo].[fRegion]
            (
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,
                NULL
            ) [fR] ON ([A].[RegionID] = [fR].[ID]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([A].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([A].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR ([A].[ID] = @ID)) AND
            ((@Code IS NULL) OR ([A].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([A].[Name] LIKE '%' + @Name + '%')) AND
            ((@IsDeleted IS NULL) OR ([A].[IsDeleted] = @IsDeleted))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vArea]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vArea];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:14:36
-- Description   : Provide view (model) to retrieve [dbo].[fArea] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vArea]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [Area],
            [RegionID],
            [RegionCode],
            [RegionName],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted]
        FROM
			[dbo].[fArea]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
