USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fClosingPeriod]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fClosingPeriod];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:14:36
-- Description   : Provide function to retrieve [dbo].[ClosingPeriod] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fClosingPeriod]
(
    @SiteID uniqueidentifier,
    @YearID int,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @SiteDistributionTypeID int,
    @IsSiteDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [CP].[SiteID],
            [CP].[YearID],
            [CP].[Jan],
            [CP].[Feb],
            [CP].[Mar],
            [CP].[Apr],
            [CP].[May],
            [CP].[Jun],
            [CP].[Jul],
            [CP].[Aug],
            [CP].[Sep],
            [CP].[Oct],
            [CP].[Nov],
            [CP].[Dec],
            [fS].[Code] [SiteCode],
            [fS].[Name] [SiteName],
            [fS].[Site],
            [fS].[AreaID],
            [fS].[AreaCode],
            [fS].[AreaName],
            [fS].[Area],            
            [fS].[RegionID],
            [fS].[RegionCode],
            [fS].[RegionName],
            [fS].[Region],
            [fS].[TerritoryID],
            [fS].[TerritoryCode],
            [fS].[TerritoryName],
            [fS].[Territory],
            [fS].[CompanyID],
            [fS].[CompanyCode],
            [fS].[CompanyName],
            [fS].[Company],
            [fS].[DistributionTypeID] [SiteDistributionTypeID],
            [fS].[DistributionTypeName] [SiteDistributionTypeName],
            [CP].[CreatedDate],
            [CP].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [CP].[ModifiedDate],
            [CP].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName]
        FROM
			[dbo].[ClosingPeriod] [CP] INNER JOIN
            [dbo].[fSite]
            (
                @SiteID,
                @SiteCode,
                @SiteName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @SiteDistributionTypeID,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                @IsSiteDeleted
            ) [fS] ON ([CP].[SiteID] = [fS].[ID]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([CP].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([CP].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@SiteID IS NULL) OR ([CP].[SiteID] = @SiteID)) AND
            ((@YearID IS NULL) OR ([CP].[YearID] = @YearID))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vClosingPeriod]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vClosingPeriod];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:14:36
-- Description   : Provide view (model) to retrieve [dbo].[fClosingPeriod] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vClosingPeriod]
AS
(
    SELECT
            [SiteID],
            [YearID],
            [Jan],
            [Feb],
            [Mar],
            [Apr],
            [May],
            [Jun],
            [Jul],
            [Aug],
            [Sep],
            [Oct],
            [Nov],
            [Dec],
            [SiteCode],
            [SiteName],
            [Site],
            [AreaID],
            [AreaCode],
            [AreaName],
            [Area],            
            [RegionID],
            [RegionCode],
            [RegionName],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [CompanyID],
            [CompanyCode],
            [CompanyName],
            [Company],
            [SiteDistributionTypeID],
            [SiteDistributionTypeName],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName]
        FROM
			[dbo].[fClosingPeriod]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
