USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fCompany]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fCompany];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[Company] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fCompany]
(
    @ID int,
    @Code nvarchar(10),
    @Name nvarchar(50),
    @Address nvarchar(100),
    @City nvarchar(50),
    @StateProvince nvarchar(50),
    @CountryID int,
    @CountryName nvarchar(50),
    @ZipCode nvarchar(10),
    @Phone1 nvarchar(20),
    @Phone2 nvarchar(20),
    @Fax nvarchar(20),
    @Email nvarchar(256),
    @TaxNumber nvarchar(20),
    @StatusID int,
    @IsDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [C].[ID],
            [C].[Code],
            [C].[Name],
            [dbo].[fCodeNameFormatter]([C].[Code], [C].[Name]) [Company],
            [fCA].[Address1],
            [fCA].[Address2],
            [fCA].[Address3],
            [fCA].[Address],
            [fCA].[City],
            [fCA].[StateProvince],
            [fCA].[CountryID],
            [fCA].[CountryName],
            [fCA].[ZipCode],
            [fCA].[Phone1],
            [fCA].[Phone2],
            [fCA].[Fax],
            [fCA].[Email],
            [C].[TaxNumber],
            [C].[StatusID],
            [fSL].[Name] [StatusName],
            [C].[CreatedDate],
            [C].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [C].[ModifiedDate],
            [C].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [C].[IsDeleted]
        FROM
			[dbo].[Company] [C] INNER JOIN
            [dbo].[fCompanyAddress]
            (
                @ID,
                @Address,
                @City,
                @StateProvince,
                @CountryID,
                @CountryName,
                @ZipCode,
                @Phone1,
                @Phone2,
                @Fax,
                @Email
            ) [fCA] ON ([C].[ID] = [fCA].[CompanyID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'CompanyStatus',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([C].[StatusID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([C].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([C].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR (@ID = [C].[ID])) AND
            ((@Code IS NULL) OR ([C].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([C].[Name] LIKE '%' + @Name + '%')) AND
            ((@TaxNumber IS NULL) OR ([C].[TaxNumber] LIKE '%' + @TaxNumber + '%')) AND                        
            ((@StatusID IS NULL) OR ([C].[StatusID] = @StatusID)) AND
            ((@IsDeleted IS NULL) OR ([C].[IsDeleted] = @IsDeleted))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vCompany]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vCompany];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fCompany] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vCompany]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [Company],
            [Address1],
            [Address2],
            [Address3],
            [Address],
            [City],
            [StateProvince],
            [CountryID],
            [CountryName],
            [ZipCode],
            [Phone1],
            [Phone2],
            [Fax],
            [Email],
            [TaxNumber],
            [StatusID],
            [StatusName],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted]
        FROM
			[dbo].[fCompany]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
