USE [IDOS];
GO

INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AD', 'Andorra', 'AND', '376');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AE', 'United Arab Emirates', 'ARE', '971');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AF', 'Afghanistan', 'AFG', '93');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AG', 'Antigua and Barbuda', 'ATG', '1 268');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AI', 'Anguilla', 'AIA', '1 264');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AL', 'Albania', 'ALB', '355');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AM', 'Armenia', 'ARM', '374');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AO', 'Angola', 'AGO', '244');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AQ', 'Antarctica', 'ATA', '672');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AR', 'Argentina', 'ARG', '54');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AS', 'American Samoa', 'ASM', '1 684');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AT', 'Austria', 'AUT', '43');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AU', 'Australia', 'AUS', '61');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AW', 'Aruba', 'ABW', '297');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AX', 'Aland Islands', 'ALA', '358 18');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('AZ', 'Azerbaijan', 'AZE', '994');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BA', 'Bosnia and Herzegovina', 'BIH', '387');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BB', 'Barbados', 'BRB', '1 246');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BD', 'Bangladesh', 'BGD', '880');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BE', 'Belgium', 'BEL', '32');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BF', 'Burkina Faso', 'BFA', '226');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BG', 'Bulgaria', 'BGR', '359');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BH', 'Bahrain', 'BHR', '973');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BI', 'Burundi', 'BDI', '257');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BJ', 'Benin', 'BEN', '229');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BL', 'Saint Barthelemy', 'BLM', '590');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BM', 'Bermuda', 'BMU', '1 441');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BN', 'Brunei Darussalam', 'BRN', '673');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BO', 'Bolivia', 'BOL', '591');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BQ', 'Bonaire', 'BES', '599 7');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BR', 'Brazil', 'BRA', '55');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BS', 'Bahamas', 'BHS', '1 242');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BT', 'Bhutan', 'BTN', '975');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BV', 'Bouvet Island', 'BVT', '55');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BW', 'Botswana', 'BWA', '267');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BY', 'Belarus', 'BLR', '375');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('BZ', 'Belize', 'BLZ', '501');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CA', 'Canada', 'CAN', '1');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CC', 'Cocos (Keeling) Islands', 'CCK', '61');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CD', 'Congo Democratic Republic', 'COD', '243');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CF', 'Central African Republic', 'CAF', '236');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CG', 'Congo Republic', 'COG', '242');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CH', 'Switzerland', 'CHE', '41');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CI', 'Cote d''Ivoire', 'CIV', '225');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CK', 'Cook Islands', 'COK', '682');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CL', 'Chile', 'CHL', '56');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CM', 'Cameroon', 'CMR', '237');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CN', 'China', 'CHN', '86');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CO', 'Colombia', 'COL', '57');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CR', 'Costa Rica', 'CRI', '506');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CU', 'Cuba', 'CUB', '53');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CV', 'Cape Verde', 'CPV', '238');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CW', 'Curacao', 'CUW', '599 9');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CX', 'Christmas Island', 'CXR', '61');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CY', 'Cyprus', 'CYP', '357');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('CZ', 'Czech Republic', 'CZE', '420');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('DE', 'Germany', 'DEU', '49');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('DJ', 'Djibouti', 'DJI', '253');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('DK', 'Denmark', 'DNK', '45');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('DM', 'Dominica', 'DMA', '1 767');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('DO', 'Dominican Republic', 'DOM', '1 809');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('DZ', 'Algeria', 'DZA', '213');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('EC', 'Ecuador', 'ECU', '593');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('EE', 'Estonia', 'EST', '372');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('EG', 'Egypt', 'EGY', '20');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('EH', 'Western Sahara', 'ESH', '212');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('ER', 'Eritrea', 'ERI', '291');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('ES', 'Spain', 'ESP', '34');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('ET', 'Ethiopia', 'ETH', '251');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('FI', 'Finland', 'FIN', '358');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('FJ', 'Fiji', 'FJI', '679');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('FK', 'Falkland Islands (Malvinas)', 'FLK', '500');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('FM', 'Micronesia', 'FSM', '691');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('FO', 'Faroe Islands', 'FRO', '298');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('FR', 'France', 'FRA', '33');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GA', 'Gabon', 'GAB', '241');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GB', 'United Kingdom', 'GBR', '44');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GD', 'Grenada', 'GRD', '1 473');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GE', 'Georgia', 'GEO', '995');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GF', 'French Guiana', 'GUF', '594');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GG', 'Guernsey', 'GGY', '44');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GH', 'Ghana', 'GHA', '233');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GI', 'Gibraltar', 'GIB', '350');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GL', 'Greenland', 'GRL', '299');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GM', 'Gambia', 'GMB', '220');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GN', 'Guinea', 'GIN', '224');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GP', 'Guadeloupe', 'GLP', '590');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GQ', 'Equatorial Guinea', 'GNQ', '240');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GR', 'Greece', 'GRC', '30');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GS', 'South Georgia and the South Sandwich Islands', 'SGS', '500');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GT', 'Guatemala', 'GTM', '502');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GU', 'Guam', 'GUM', '1 671');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GW', 'Guinea-Bissau', 'GNB', '245');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('GY', 'Guyana', 'GUY', '592');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('HK', 'Hong Kong', 'HKG', '852');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('HM', 'Heard Island and McDonald Islands', 'HMD', '0');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('HN', 'Honduras', 'HND', '504');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('HR', 'Croatia', 'HRV', '385');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('HT', 'Haiti', 'HTI', '509');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('HU', 'Hungary', 'HUN', '36');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('ID', 'Indonesia', 'IDN', '62');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('IE', 'Ireland', 'IRL', '353');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('IL', 'Israel', 'ISR', '972');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('IM', 'Isle of Man', 'IMN', '44');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('IN', 'India', 'IND', '91');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('IO', 'British Indian Ocean Territory', 'IOT', '246');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('IQ', 'Iraq', 'IRQ', '964');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('IR', 'Iran', 'IRN', '98');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('IS', 'Iceland', 'ISL', '354');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('IT', 'Italy', 'ITA', '39');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('JE', 'Jersey', 'JEY', '44');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('JM', 'Jamaica', 'JAM', '1 876');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('JO', 'Jordan', 'JOR', '962');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('JP', 'Japan', 'JPN', '81');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('KE', 'Kenya', 'KEN', '254');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('KG', 'Kyrgyzstan', 'KGZ', '996');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('KH', 'Cambodia', 'KHM', '855');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('KI', 'Kiribati', 'KIR', '686');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('KM', 'Comoros', 'COM', '269');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('KN', 'Saint Kitts and Nevis', 'KNA', '1 869');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('KP', 'North Korea', 'PRK', '850');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('KR', 'South Korea', 'KOR', '82');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('KW', 'Kuwait', 'KWT', '965');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('KY', 'Cayman Islands', 'CYM', '1 345');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('KZ', 'Kazakhstan', 'KAZ', '7');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('LA', 'Laos', 'LAO', '856');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('LB', 'Lebanon', 'LBN', '961');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('LC', 'Saint Lucia', 'LCA', '1 758');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('LI', 'Liechtenstein', 'LIE', '423');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('LK', 'Sri Lanka', 'LKA', '94');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('LR', 'Liberia', 'LBR', '231');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('LS', 'Lesotho', 'LSO', '266');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('LT', 'Lithuania', 'LTU', '370');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('LU', 'Luxembourg', 'LUX', '352');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('LV', 'Latvia', 'LVA', '371');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('LY', 'Libya', 'LBY', '218');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MA', 'Morocco', 'MAR', '212');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MC', 'Monaco', 'MCO', '377');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MD', 'Moldova', 'MDA', '373');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('ME', 'Montenegro', 'MNE', '382');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MF', 'Saint Martin', 'MAF', '1 599');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MG', 'Madagascar', 'MDG', '261');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MH', 'Marshall Islands', 'MHL', '692');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MK', 'Macedonia', 'MKD', '389');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('ML', 'Mali', 'MLI', '223');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MM', 'Myanmar', 'MMR', '95');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MN', 'Mongolia', 'MNG', '976');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MO', 'Macao', 'MAC', '853');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MP', 'Northern Mariana Islands', 'MNP', '1 670');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MQ', 'Martinique', 'MTQ', '596');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MR', 'Mauritania', 'MRT', '222');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MS', 'Montserrat', 'MSR', '1 664');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MT', 'Malta', 'MLT', '356');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MU', 'Mauritius', 'MUS', '230');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MV', 'Maldives', 'MDV', '960');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MW', 'Malawi', 'MWI', '265');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MX', 'Mexico', 'MEX', '52');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MY', 'Malaysia', 'MYS', '60');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('MZ', 'Mozambique', 'MOZ', '258');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NA', 'Namibia', 'NAM', '264');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NC', 'New Caledonia', 'NCL', '687');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NE', 'Niger', 'NER', '227');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NF', 'Norfolk Island', 'NFK', '672 3');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NG', 'Nigeria', 'NGA', '234');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NI', 'Nicaragua', 'NIC', '505');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NL', 'Netherlands', 'NLD', '31');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NO', 'Norway', 'NOR', '47');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NP', 'Nepal', 'NPL', '977');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NR', 'Nauru', 'NRU', '674');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NU', 'Niue', 'NIU', '683');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('NZ', 'New Zealand', 'NZL', '64');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('OM', 'Oman', 'OMN', '968');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PA', 'Panama', 'PAN', '507');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PE', 'Peru', 'PER', '51');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PF', 'French Polynesia', 'PYF', '689');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PG', 'Papua New Guinea', 'PNG', '675');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PH', 'Philippines', 'PHL', '63');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PK', 'Pakistan', 'PAK', '92');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PL', 'Poland', 'POL', '48');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PM', 'Saint Pierre and Miquelon', 'SPM', '508');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PN', 'Pitcairn', 'PCN', '870');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PR', 'Puerto Rico', 'PRI', '1');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PS', 'Palestine', 'PSE', '970');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PT', 'Portugal', 'PRT', '351');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PW', 'Palau', 'PLW', '680');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('PY', 'Paraguay', 'PRY', '595');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('QA', 'Qatar', 'QAT', '974');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('RE', 'Reunion', 'REU', '262');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('RO', 'Romania', 'ROU', '40');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('RS', 'Serbia', 'SRB', '381');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('RU', 'Russia', 'RUS', '7');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('RW', 'Rwanda', 'RWA', '250');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SA', 'Saudi Arabia', 'SAU', '966');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SB', 'Solomon Islands', 'SLB', '677');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SC', 'Seychelles', 'SYC', '248');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SD', 'Sudan', 'SDN', '249');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SE', 'Sweden', 'SWE', '46');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SG', 'Singapore', 'SGP', '65');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', '290');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SI', 'Slovenia', 'SVN', '386');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SJ', 'Svalbard and Jan Mayen', 'SJM', '47 79');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SK', 'Slovakia', 'SVK', '421');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SL', 'Sierra Leone', 'SLE', '232');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SM', 'San Marino', 'SMR', '378');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SN', 'Senegal', 'SEN', '221');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SO', 'Somalia', 'SOM', '252');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SR', 'Suriname', 'SUR', '597');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SS', 'South Sudan ', 'SSD', '211');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('ST', 'Sao Tome and Principe', 'STP', '239');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SV', 'El Salvador', 'SLV', '503');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SX', 'Sint Maarten', 'SXM', '1 721');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SY', 'Syrian Arab Republic', 'SYR', '963');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('SZ', 'Swaziland', 'SWZ', '268');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TC', 'Turks and Caicos Islands', 'TCA', '1 649');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TD', 'Chad', 'TCD', '235');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TF', 'French Southern Territories', 'ATF', '262');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TG', 'Togo', 'TGO', '228');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TH', 'Thailand', 'THA', '66');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TJ', 'Tajikistan', 'TJK', '992');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TK', 'Tokelau', 'TKL', '690');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TL', 'Timor-Leste', 'TLS', '670');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TM', 'Turkmenistan', 'TKM', '993');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TN', 'Tunisia', 'TUN', '216');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TO', 'Tonga', 'TON', '676');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TR', 'Turkey', 'TUR', '90');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TT', 'Trinidad and Tobago', 'TTO', '1 868');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TV', 'Tuvalu', 'TUV', '688');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TW', 'Taiwan', 'TWN', '886');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('TZ', 'Tanzania', 'TZA', '255');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('UA', 'Ukraine', 'UKR', '380');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('UG', 'Uganda', 'UGA', '256');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('UM', 'United States Minor Outlying Islands', 'UMI', '1');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('US', 'United States', 'USA', '1');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('UY', 'Uruguay', 'URY', '598');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('UZ', 'Uzbekistan', 'UZB', '998');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('VA', 'Holy See (Vatican City State)', 'VAT', '39');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('VC', 'Saint Vincent and the Grenadines', 'VCT', '1 784');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('VE', 'Venezuela', 'VEN', '58');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('VG', 'Virgin Islands (British)', 'VGB', '1 284');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('VI', 'Virgin Islands (United States)', 'VIR', '1 340');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('VN', 'Vietnam', 'VNM', '84');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('VU', 'Vanuatu', 'VUT', '678');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('WF', 'Wallis and Futuna', 'WLF', '681');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('WS', 'Samoa', 'WSM', '685');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('YE', 'Yemen', 'YEM', '967');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('YT', 'Mayotte', 'MYT', '262');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('ZA', 'South Africa', 'ZAF', '27');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('ZM', 'Zambia', 'ZMB', '260');
INSERT INTO [dbo].[Country] ([ID], [Name], [Alpha3Code], [DialCode]) VALUES ('ZW', 'Zimbabwe', 'ZWE', '263');
GO
