USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fCustomerBillAddress]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fCustomerBillAddress];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[CustomerBillAddress] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fCustomerBillAddress]
(
    @CustomerID uniqueidentifier,
    @Address nvarchar(100),
    @City nvarchar(50),
    @StateProvince nvarchar(50),
    @CountryID int,
    @CountryName nvarchar(50),
    @ZipCode nvarchar(10),
    @Phone1 nvarchar(20),
    @Phone2 nvarchar(20),
    @Phone3 nvarchar(20),
    @Fax nvarchar(20),
    @Email nvarchar(256)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [CBA].[CustomerID],
            [CBA].[IsSameAsAddress],
            [CBA].[Name],
            [CBA].[Address1],
            [CBA].[Address2],
            [CBA].[Address3],
            [dbo].[fAddressFormatter]([CBA].[Address1], [CBA].[Address2], [CBA].[Address3]) [Address],
            [CBA].[City],
            [CBA].[StateProvince],
            [CBA].[CountryID],
            [fC].[Name] [CountryName],
            [CBA].[ZipCode],
            [CBA].[Phone1],
            [CBA].[Phone2],
            [CBA].[Phone3],
            [CBA].[Fax],
            [CBA].[Email]
        FROM
			[dbo].[CustomerBillAddress] [CBA] LEFT OUTER JOIN
            [dbo].[fCountry]
            (
                @CountryID,
                @CountryName,
                NULL,
                NULL
            ) [fC] ON ([CBA].[CountryID] = [fC].[ID])
		WHERE
            ((@CustomerID IS NULL) OR ([CBA].[CustomerID] = @CustomerID)) AND
            (
                (@Address IS NULL) OR
                (
                    ([CBA].[Address1] LIKE '%' + @Address + '%') OR
                    ([CBA].[Address2] LIKE '%' + @Address + '%') OR
                    ([CBA].[Address3] LIKE '%' + @Address + '%')
                )
            ) AND
            ((@City IS NULL) OR ([CBA].[City] LIKE '%' + @City + '%')) AND
            ((@StateProvince IS NULL) OR ([CBA].[StateProvince] LIKE '%' + @StateProvince + '%')) AND
            ((@CountryID IS NULL) OR ([CBA].[CountryID] = @CountryID)) AND
            ((@ZipCode IS NULL) OR ([CBA].[ZipCode] LIKE '%' + @ZipCode + '%')) AND
            ((@Phone1 IS NULL) OR ([CBA].[Phone1] LIKE '%' + @Phone1 + '%')) AND
            ((@Phone2 IS NULL) OR ([CBA].[Phone2] LIKE '%' + @Phone2 + '%')) AND
            ((@Phone3 IS NULL) OR ([CBA].[Phone3] LIKE '%' + @Phone3 + '%')) AND
            ((@Fax IS NULL) OR ([CBA].[Fax] LIKE '%' + @Fax + '%')) AND
            ((@Email IS NULL) OR ([CBA].[Email] LIKE '%' + @Email + '%'))            
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vCustomerBillAddress]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vCustomerBillAddress];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fCustomerBillAddress] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vCustomerBillAddress]
AS
(
    SELECT
            [CustomerID],
            [IsSameAsAddress],
            [Name],
            [Address1],
            [Address2],
            [Address3],
            [Address],
            [City],
            [StateProvince],
            [CountryID],
            [CountryName],
            [ZipCode],
            [Phone1],
            [Phone2],
            [Phone3],
            [Fax],
            [Email]
        FROM
			[dbo].[fCustomerBillAddress]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
