USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fCustomerCategoryInfo]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fCustomerCategoryInfo];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[CustomerCategoryInfo] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fCustomerCategoryInfo]
(
    @CustomerID uniqueidentifier,
    @CategoryID int,
    @CategoryCode nvarchar(10),
    @CategoryName nvarchar(50)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [CCI].[CustomerID],
            [CCI].[Category1ID],
            [CC1].[Code] [Category1Code],
            [CC1].[Name] [Category1Name],
            [dbo].[fCodeNameFormatter]([CC1].[Code], [CC1].[Name]) [Category1],
            [CCI].[Category2ID],
            [CC2].[Code] [Category2Code],
            [CC2].[Name] [Category2Name],
            [dbo].[fCodeNameFormatter]([CC2].[Code], [CC2].[Name]) [Category2],
            [CCI].[Category3ID],
            [CC3].[Code] [Category3Code],
            [CC3].[Name] [Category3Name],
            [dbo].[fCodeNameFormatter]([CC3].[Code], [CC3].[Name]) [Category3],
            [CCI].[Category4ID],
            [CC4].[Code] [Category4Code],
            [CC4].[Name] [Category4Name],
            [dbo].[fCodeNameFormatter]([CC4].[Code], [CC4].[Name]) [Category4],            
            [CCI].[Category5ID],
            [CC5].[Code] [Category5Code],
            [CC5].[Name] [Category5Name],
            [dbo].[fCodeNameFormatter]([CC5].[Code], [CC5].[Name]) [Category5],
            NULL [Category6ID], -- [CCI].[Category6ID],
            NULL [Category6Code], -- [CC6].[Code] [Category6Code],
            NULL [Category6Name], -- [CC6].[Name] [Category6Name],
            NULL [Category6], --[dbo].[fCodeNameFormatter]([CC6].[Code], [CC6].[Name]) [Category6],
            NULL [Category7ID], -- [CCI].[Category7ID],
            NULL [Category7Code], -- [CC7].[Code] [Category7Code],
            NULL [Category7Name], -- [CC7].[Name] [Category7Name],
            NULL [Category7], -- [dbo].[fCodeNameFormatter]([CC7].[Code], [CC7].[Name]) [Category7],
            NULL [Category8ID], -- [CCI].[Category8ID],
            NULL [Category8Code], -- [CC8].[Code] [Category8Code],
            NULL [Category8Name], -- [CC8].[Name] [Category8Name],
            NULL [Category8], -- [dbo].[fCodeNameFormatter]([CC8].[Code], [CC8].[Name]) [Category8],
            NULL [Category9ID], -- [CCI].[Category9ID],
            NULL [Category9Code], -- [CC9].[Code] [Category9Code],
            NULL [Category9Name], -- [CC9].[Name] [Category9Name],
            NULL [Category9], -- [dbo].[fCodeNameFormatter]([CC9].[Code], [CC9].[Name]) [Category9],
            NULL [Category10ID], -- [CCI].[Category10ID],
            NULL [Category10Code], -- [CC10].[Code] [Category10Code],
            NULL [Category10Name], -- [CC10].[Name] [Category10Name],
            NULL [Category10] -- [dbo].[fCodeNameFormatter]([CC10].[Code], [CC10].[Name]) [Category10]
        FROM
			[dbo].[CustomerCategoryInfo] [CCI] LEFT OUTER JOIN
            [dbo].[CustomerCategory] [CC1] ON ([CCI].[Category1ID] = [CC1].[ID]) LEFT OUTER JOIN
            [dbo].[CustomerCategory] [CC2] ON ([CCI].[Category2ID] = [CC2].[ID]) LEFT OUTER JOIN
            [dbo].[CustomerCategory] [CC3] ON ([CCI].[Category3ID] = [CC3].[ID]) LEFT OUTER JOIN
            [dbo].[CustomerCategory] [CC4] ON ([CCI].[Category4ID] = [CC4].[ID]) LEFT OUTER JOIN
            [dbo].[CustomerCategory] [CC5] ON ([CCI].[Category5ID] = [CC5].[ID]) --LEFT OUTER JOIN
            --[dbo].[CustomerCategory] [CC6] ON ([CCI].[Category6ID] = [CC6].[ID]) LEFT OUTER JOIN
            --[dbo].[CustomerCategory] [CC7] ON ([CCI].[Category7ID] = [CC7].[ID]) LEFT OUTER JOIN
            --[dbo].[CustomerCategory] [CC8] ON ([CCI].[Category8ID] = [CC8].[ID]) LEFT OUTER JOIN
            --[dbo].[CustomerCategory] [CC9] ON ([CCI].[Category9ID] = [CC9].[ID]) LEFT OUTER JOIN
            --[dbo].[CustomerCategory] [CC10] ON ([CCI].[Category10ID] = [CC10].[ID])
		WHERE
            ((@CustomerID IS NULL) OR ([CCI].[CustomerID] = @CustomerID)) AND
            (
                (@CategoryID IS NULL) OR
                (
                    ([CCI].[Category1ID] = @CategoryID) OR
                    ([CCI].[Category2ID] = @CategoryID) OR
                    ([CCI].[Category3ID] = @CategoryID) OR
                    ([CCI].[Category4ID] = @CategoryID) OR
                    ([CCI].[Category5ID] = @CategoryID) OR
                    ([CCI].[Category6ID] = @CategoryID) OR
                    ([CCI].[Category7ID] = @CategoryID) OR
                    ([CCI].[Category8ID] = @CategoryID) OR
                    ([CCI].[Category9ID] = @CategoryID) OR
                    ([CCI].[Category10ID] = @CategoryID)
                )
            ) AND
            (
                (@CategoryCode IS NULL) OR
                (
                    ([CC1].[Code] LIKE '%' + @CategoryCode + '%') OR
                    ([CC2].[Code] LIKE '%' + @CategoryCode + '%') OR
                    ([CC3].[Code] LIKE '%' + @CategoryCode + '%') OR
                    ([CC4].[Code] LIKE '%' + @CategoryCode + '%') OR
                    ([CC5].[Code] LIKE '%' + @CategoryCode + '%') --OR
                --    ([CC6].[Code] LIKE '%' + @CategoryCode + '%') OR
                --    ([CC7].[Code] LIKE '%' + @CategoryCode + '%') OR
                --    ([CC8].[Code] LIKE '%' + @CategoryCode + '%') OR
                --    ([CC9].[Code] LIKE '%' + @CategoryCode + '%') OR
                --    ([CC10].[Code] LIKE '%' + @CategoryCode + '%')
                )
            ) AND
            (
                (@CategoryName IS NULL) OR
                (
                    ([CC1].[Name] LIKE '%' + @CategoryName + '%') OR
                    ([CC2].[Name] LIKE '%' + @CategoryName + '%') OR
                    ([CC3].[Name] LIKE '%' + @CategoryName + '%') OR
                    ([CC4].[Name] LIKE '%' + @CategoryName + '%') OR
                    ([CC5].[Name] LIKE '%' + @CategoryName + '%') --OR
                    --([CC6].[Name] LIKE '%' + @CategoryName + '%') OR
                    --([CC7].[Name] LIKE '%' + @CategoryName + '%') OR
                    --([CC8].[Name] LIKE '%' + @CategoryName + '%') OR
                    --([CC9].[Name] LIKE '%' + @CategoryName + '%') OR
                    --([CC10].[Name] LIKE '%' + @CategoryName + '%')
                )
            )            
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vCustomerCategoryInfo]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vCustomerCategoryInfo];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fCustomerCategoryInfo] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vCustomerCategoryInfo]
AS
(
    SELECT
            [CustomerID],
            [Category1ID],
            [Category1Code],
            [Category1Name],
            [Category1],            
            [Category2ID],
            [Category2Code],
            [Category2Name],
            [Category2],
            [Category3ID],
            [Category3Code],
            [Category3Name],
            [Category3],
            [Category4ID],
            [Category4Code],
            [Category4Name],
            [Category4],
            [Category5ID],
            [Category5Code],
            [Category5Name],
            [Category5],
            [Category6ID],
            [Category6Code],
            [Category6Name],
            [Category6],
            [Category7ID],
            [Category7Code],
            [Category7Name],
            [Category7],
            [Category8ID],
            [Category8Code],
            [Category8Name],
            [Category8],
            [Category9ID],
            [Category9Code],
            [Category9Name],
            [Category9],
            [Category10ID],
            [Category10Code],
            [Category10Name],
            [Category10]            
        FROM
			[dbo].[fCustomerCategoryInfo]
            (
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
