USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fCustomerTaxAddress]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fCustomerTaxAddress];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[CustomerTaxAddress] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fCustomerTaxAddress]
(
    @CustomerID uniqueidentifier,
    @Address nvarchar(100),
    @City nvarchar(50),
    @StateProvince nvarchar(50),
    @CountryID int,
    @CountryName nvarchar(50),
    @ZipCode nvarchar(10),
    @Phone1 nvarchar(20),
    @Phone2 nvarchar(20),
    @Phone3 nvarchar(20),
    @Fax nvarchar(20),
    @Email nvarchar(256)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [CTA].[CustomerID],
            [CTA].[IsSameAsAddress],
            [CTA].[IsSameAsBillAddress],
            [CTA].[Name],
            [CTA].[Address1],
            [CTA].[Address2],
            [CTA].[Address3],
            [dbo].[fAddressFormatter]([CTA].[Address1], [CTA].[Address2], [CTA].[Address3]) [Address],
            [CTA].[City],
            [CTA].[StateProvince],
            [CTA].[CountryID],
            [fC].[Name] [CountryName],
            [CTA].[ZipCode],
            [CTA].[Phone1],
            [CTA].[Phone2],
            [CTA].[Phone3],
            [CTA].[Fax],
            [CTA].[Email]
           
        FROM
			[dbo].[CustomerTaxAddress] [CTA] LEFT OUTER JOIN
            [dbo].[fCountry]
            (
                @CountryID,
                @CountryName,
                NULL,
                NULL
            ) [fC] ON ([CTA].[CountryID] = [fC].[ID])
		WHERE
            ((@CustomerID IS NULL) OR ([CTA].[CustomerID] = @CustomerID)) AND
            (
                (@Address IS NULL) OR
                (
                    ([CTA].[Address1] LIKE '%' + @Address + '%') OR
                    ([CTA].[Address2] LIKE '%' + @Address + '%') OR
                    ([CTA].[Address3] LIKE '%' + @Address + '%')
                )
            ) AND
            ((@City IS NULL) OR ([CTA].[City] LIKE '%' + @City + '%')) AND
            ((@StateProvince IS NULL) OR ([CTA].[StateProvince] LIKE '%' + @StateProvince + '%')) AND
            ((@CountryID IS NULL) OR ([CTA].[CountryID] = @CountryID)) AND
            ((@ZipCode IS NULL) OR ([CTA].[ZipCode] LIKE '%' + @ZipCode + '%')) AND
            ((@Phone1 IS NULL) OR ([CTA].[Phone1] LIKE '%' + @Phone1 + '%')) AND
            ((@Phone2 IS NULL) OR ([CTA].[Phone2] LIKE '%' + @Phone2 + '%')) AND
            ((@Phone3 IS NULL) OR ([CTA].[Phone3] LIKE '%' + @Phone3 + '%')) AND
            ((@Fax IS NULL) OR ([CTA].[Fax] LIKE '%' + @Fax + '%')) AND
            ((@Email IS NULL) OR ([CTA].[Email] LIKE '%' + @Email + '%'))            
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vCustomerTaxAddress]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vCustomerTaxAddress];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fCustomerTaxAddress] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vCustomerTaxAddress]
AS
(
    SELECT
            [CustomerID],
            [IsSameAsAddress],
            [IsSameAsBillAddress],
            [Name],
            [Address1],
            [Address2],
            [Address3],
            [Address],
            [City],
            [StateProvince],
            [CountryID],
            [CountryName],
            [ZipCode],
            [Phone1],
            [Phone2],
            [Phone3],
            [Fax],
            [Email]
        FROM
			[dbo].[fCustomerTaxAddress]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
