USE [IDOS_DEV];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fCustomer]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fCustomer];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[Customer] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fCustomer]
(
    @ID uniqueidentifier,
    @Code nvarchar(20),
    @Name nvarchar(50),
    @SalesmanID uniqueidentifier,
    @SalesmanCode nvarchar(20),
    @SalesmanName nvarchar(50),
    @WarehouseID uniqueidentifier,
    @WarehouseCode nvarchar(10),
    @WarehouseName nvarchar(50),
    @SiteID uniqueidentifier,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),    
    @SiteDistributionTypeID int,
    @WarehouseTypeID int,
    @SalesmanGroupID int,
    @SalesmanCategoryID int,
    @SalesmanStatusID int,
    @TermOfPaymentID int,
    @PriceGroupID int,
    @DiscountGroupID int,
    @DiscountGroupCode nvarchar(10),
    @DiscountGroupName nvarchar(50),
    @DiscountGroupDescription nvarchar(200),
    @DiscountGroupStatusID int,
    @IsTaxNumberAvailable bit,
    @TaxNumber nvarchar(20),
    @Address nvarchar(100),
    @City nvarchar(50),
    @StateProvince nvarchar(50),
    @CountryID int,
    @CountryName nvarchar(50),
    @ZipCode nvarchar(10),
    @Phone1 nvarchar(20),
    @Phone2 nvarchar(20),
    @Phone3 nvarchar(20),
    @Fax nvarchar(20),
    @Email nvarchar(256),
    @AdditionalInfo nvarchar(100),
    @CategoryID int,
    @CategoryCode nvarchar(10),
    @CategoryName nvarchar(50),
    @StatusID int,
    @IsDeleted bit,
    @SalesmanIDRoute uniqueidentifier,
    @WeekIDEqual int,
    @DayIDEqual int,
    @WeekIDNotEqual int,
    @DayIDNotEqual int
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [C].[ID],
            [C].[Code],
            [C].[Name],
            [dbo].[fCodeNameFormatter]([C].[Code], [C].[Name]) [Customer],
            [C].[SalesmanID],
            [fS].[Code] [SalesmanCode],
            [fS].[Name] [SalesmanName],
            [fS].[Salesman],
            [fS].[WarehouseID],
            [fS].[WarehouseCode],
            [fS].[WarehouseName],
            [fS].[Warehouse],
            [fS].[SiteID],
            [fS].[SiteCode],
            [fS].[SiteName],
            [fS].[Site],
            [fS].[CompanyID],
            [fS].[CompanyCode],
            [fS].[CompanyName],
            [fS].[Company],
            [fS].[AreaID],
            [fS].[AreaCode],
            [fS].[AreaName],
            [fS].[Area],
            [fS].[RegionID],
            [fS].[RegionCode],
            [fS].[RegionName],
            [fS].[Region],
            [fS].[TerritoryID],
            [fS].[TerritoryCode],
            [fS].[TerritoryName],
            [fS].[Territory],
            [fS].[SiteDistributionTypeID],
            [fS].[SiteDistributionTypeName],            
            [fS].[WarehouseTypeID],
            [fS].[WarehouseTypeName],
            [fS].[GroupID] [SalesmanGroupID],
            [fS].[GroupName] [SalesmanGroupName],
            [fS].[CategoryID] [SalesmanCategoryID],
            [fS].[CategoryName] [SalesmanCategoryName],
            [fS].[Phone] [SalesmanPhoneID],
            [fS].[SFA] [SalesmanSFA],
            [fS].[StatusID] [SalesmanStatusID],
            [fS].[StatusName] [SalesmanStatusName],
            [fS].[IsDeleted] [IsSalesmanDeleted],
            [C].[RegisteredDate],
            [C].[TermOfPaymentID],
            [fSL].[Name] [TermOfPaymentName],
            [C].[CreditLimit],
            [C].[PriceGroupID],
            [fSL2].[Name] [PriceGroupName],
            [C].[DiscountGroupID],
            [fDG].[Code] [DiscountGroupCode],
            [fDG].[Name] [DiscountGroupName],
            [fDG].[DiscountGroup],
            [fDG].[Description] [DiscountGroupDescription],
            [fDG].[StatusID] [DiscountGroupStatusID],
            [fDG].[StatusName] [DiscountGroupStatusName],
            [C].[IsTaxNumberAvailable],
            [C].[TaxSAPCode],
            [C].[TaxNumber],
            [fCA].[Address1],
            [fCA].[Address2],
            [fCA].[Address3],
            [fCA].[Address],
            [fCA].[City],
            [fCA].[StateProvince],
            [fCA].[CountryID],
            [fCA].[CountryName],
            [fCA].[ZipCode],
            [fCA].[Phone1],
            [fCA].[Phone2],
            [fCA].[Phone3],
            [fCA].[Fax],
            [fCA].[Email],
            [fCA].[Longitude],
            [fCA].[Latitude],
            [fCBA].[IsSameAsAddress] [IsBillSameAsAddress],
            [fCBA].[Name] [BillName],
            [fCBA].[Address1] [BillAddress1],
            [fCBA].[Address2] [BillAddress2],
            [fCBA].[Address3] [BillAddress3],
            [fCBA].[Address] [BillAddress],
            [fCBA].[City] [BillCity],
            [fCBA].[StateProvince] [BillStateProvince],
            [fCBA].[CountryID] [BillCountryID],
            [fCBA].[CountryName] [BillCountryName],
            [fCBA].[ZipCode] [BillZipCode],
            [fCBA].[Phone1] [BillPhone1],
            [fCBA].[Phone2] [BillPhone2],
            [fCBA].[Phone3] [BillPhone3],
            [fCBA].[Fax] [BillFax],
            [fCBA].[Email] [BillEmail],
            [fCTA].[IsSameAsAddress] [IsTaxSameAsAddress],
            [fCTA].[IsSameAsBillAddress] [IsTaxSameAsBillAddress],
            [fCTA].[Name] [TaxName],
            [fCTA].[Address1] [TaxAddress1],
            [fCTA].[Address2] [TaxAddress2],
            [fCTA].[Address3] [TaxAddress3],
            [fCTA].[Address] [TaxAddress],
            [fCTA].[City] [TaxCity],
            [fCTA].[StateProvince] [TaxStateProvince],
            [fCTA].[CountryID] [TaxCountryID],
            [fCTA].[CountryName] [TaxCountryName],
            [fCTA].[ZipCode] [TaxZipCode],
            [fCTA].[Phone1] [TaxPhone1],
            [fCTA].[Phone2] [TaxPhone2],
            [fCTA].[Phone3] [TaxPhone3],
            [fCTA].[Fax] [TaxFax],
            [fCTA].[Email] [TaxEmail],
            [fCAI].[AdditionalInfo1],
            [fCAI].[AdditionalInfo2],
            [fCAI].[AdditionalInfo3],
            [fCAI].[AdditionalInfo4],
            [fCAI].[AdditionalInfo5],
            [fCAI].[AdditionalInfo6],
            [fCAI].[AdditionalInfo7],
            [fCAI].[AdditionalInfo8],
            [fCAI].[AdditionalInfo9],
            [fCAI].[AdditionalInfo10],
            [fCCI].[Category1ID],
            [fCCI].[Category1Code],
            [fCCI].[Category1Name],
            [fCCI].[Category1],
            [fCCI].[Category2ID],
            [fCCI].[Category2Code],
            [fCCI].[Category2Name],
            [fCCI].[Category2],
            [fCCI].[Category3ID],
            [fCCI].[Category3Code],
            [fCCI].[Category3Name],
            [fCCI].[Category3],
            [fCCI].[Category4ID],
            [fCCI].[Category4Code],
            [fCCI].[Category4Name],
            [fCCI].[Category4],
            [fCCI].[Category5ID],
            [fCCI].[Category5Code],
            [fCCI].[Category5Name],
            [fCCI].[Category5],
            [fCCI].[Category6ID],
            [fCCI].[Category6Code],
            [fCCI].[Category6Name],
            [fCCI].[Category6],
            [fCCI].[Category7ID],
            [fCCI].[Category7Code],
            [fCCI].[Category7Name],
            [fCCI].[Category7],
            [fCCI].[Category8ID],
            [fCCI].[Category8Code],
            [fCCI].[Category8Name],
            [fCCI].[Category8],
            [fCCI].[Category9ID],
            [fCCI].[Category9Code],
            [fCCI].[Category9Name],
            [fCCI].[Category9],
            [fCCI].[Category10ID],
            [fCCI].[Category10Code],
            [fCCI].[Category10Name],
            [fCCI].[Category10],
            [C].[Photo],
            [C].[StatusID],
            [fSL3].[Name] [StatusName],
            [C].[CreatedDate],
            [C].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [C].[ModifiedDate],
            [C].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [C].[IsDeleted],
            @SalesmanIDRoute [SalesmanIDRoute],
            @WeekIDEqual [WeekIDEqual],
            @DayIDEqual [DayIDEqual],
            @WeekIDNotEqual [WeekIDNotEqual],
            @DayIDNotEqual [DayIDNotEqual]
        FROM
			[dbo].[Customer] [C] INNER JOIN
            [dbo].[fSalesman]
            (
                @SalesmanID,
                @SalesmanCode,
                @SalesmanName,
                @WarehouseID,
                @WarehouseCode,
                @WarehouseName,
                @SiteID,
                @SiteCode,
                @SiteName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,    
                @SiteDistributionTypeID,
				NULL,
                @WarehouseTypeID,
                @SalesmanGroupID,
                @SalesmanCategoryID,
                NULL,
                NULL,
                @SalesmanStatusID,
                NULL
            ) [fS] ON ([C].[SalesmanID] = [fS].[ID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'CustomerTermOfPayment',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([C].[TermOfPaymentID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'ProductPriceGroup',
                NULL,
                NULL,
                NULL
            ) [fSL2] ON ([C].[PriceGroupID] = [fSL2].[Value_Int32]) INNER JOIN
            [dbo].[fDiscountGroup]
            (
                @DiscountGroupID,
                @DiscountGroupCode,
                @DiscountGroupName,
                @DiscountGroupDescription,
                @DiscountGroupStatusID,
                NULL
            ) [fDG] ON ([C].[DiscountGroupID] = [fDG].[ID]) INNER JOIN
            [dbo].[fCustomerAddress]
            (
                @ID,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            ) [fCA] ON ([C].[ID] = [fCA].[CustomerID]) INNER JOIN
            [dbo].[fCustomerBillAddress]
            (
                @ID,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            ) [fCBA] ON ([C].[ID] = [fCBA].[CustomerID]) INNER JOIN
            [dbo].[fCustomerTaxAddress]
            (
                @ID,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            ) [fCTA] ON ([C].[ID] = [fCTA].[CustomerID]) INNER JOIN
            [dbo].[fCustomerAdditionalInfo]
            (
                @ID,
                @AdditionalInfo
            ) [fCAI] ON ([C].[ID] = [fCAI].[CustomerID])INNER JOIN
            [dbo].[fCustomerCategoryInfo]
            (
                @ID,
                @CategoryID,
                @CategoryCode,
                @CategoryName
            ) [fCCI] ON ([C].[ID] = [fCCI].[CustomerID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'CustomerStatus',
                NULL,
                NULL,
                NULL
            ) [fSL3] ON ([C].[StatusID] = [fSL3].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([C].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([C].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR (@ID = [C].[ID])) AND
            ((@Code IS NULL) OR ([C].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([C].[Name] LIKE '%' + @Name + '%')) AND
            ((@TermOfPaymentID IS NULL) OR ([C].[TermOfPaymentID] = @TermOfPaymentID)) AND
            ((@IsTaxNumberAvailable IS NULL) OR ([C].[IsTaxNumberAvailable] = @IsTaxNumberAvailable)) AND
            ((@TaxNumber IS NULL) OR ([C].[TaxNumber] LIKE '%' + @TaxNumber + '%')) AND
            (
                (@Address IS NULL) OR
                (
                    ([fCA].[Address1] LIKE '%' + @Address + '%') OR
                    ([fCA].[Address2] LIKE '%' + @Address + '%') OR
                    ([fCA].[Address3] LIKE '%' + @Address + '%') OR
                    ([fCBA].[Address1] LIKE '%' + @Address + '%') OR
                    ([fCBA].[Address2] LIKE '%' + @Address + '%') OR
                    ([fCBA].[Address3] LIKE '%' + @Address + '%') OR
                    ([fCTA].[Address1] LIKE '%' + @Address + '%') OR
                    ([fCTA].[Address2] LIKE '%' + @Address + '%') OR
                    ([fCTA].[Address3] LIKE '%' + @Address + '%')
                )
            ) AND
            (
                (@City IS NULL) OR
                (
                    ([fCA].[City] LIKE '%' + @City + '%') OR
                    ([fCBA].[City] LIKE '%' + @City + '%') OR
                    ([fCTA].[City] LIKE '%' + @City + '%')
                )
            ) AND
            (
                (@StateProvince IS NULL) OR
                (
                    ([fCA].[StateProvince] LIKE '%' + @StateProvince + '%') OR
                    ([fCBA].[StateProvince] LIKE '%' + @StateProvince + '%') OR
                    ([fCTA].[StateProvince] LIKE '%' + @StateProvince + '%')
                )
            ) AND
            (
                (@ZipCode IS NULL) OR
                (
                    ([fCA].[ZipCode] LIKE '%' + @ZipCode + '%') OR
                    ([fCBA].[ZipCode] LIKE '%' + @ZipCode + '%') OR
                    ([fCTA].[ZipCode] LIKE '%' + @ZipCode + '%')
                )
            ) AND
            (
                (@Phone1 IS NULL) OR
                (
                    ([fCA].[Phone1] LIKE '%' + @Phone1 + '%') OR
                    ([fCBA].[Phone1] LIKE '%' + @Phone1 + '%') OR
                    ([fCTA].[Phone1] LIKE '%' + @Phone1 + '%')
                )
            ) AND
            (
                (@Phone2 IS NULL) OR
                (
                    ([fCA].[Phone2] LIKE '%' + @Phone2 + '%') OR
                    ([fCBA].[Phone2] LIKE '%' + @Phone2 + '%') OR
                    ([fCTA].[Phone2] LIKE '%' + @Phone2 + '%')
                )
            ) AND
            (
                (@Phone3 IS NULL) OR
                (
                    ([fCA].[Phone3] LIKE '%' + @Phone3 + '%') OR
                    ([fCBA].[Phone3] LIKE '%' + @Phone3 + '%') OR
                    ([fCTA].[Phone3] LIKE '%' + @Phone3 + '%')
                )
            ) AND
            (
                (@Fax IS NULL) OR
                (
                    ([fCA].[Fax] LIKE '%' + @Fax + '%') OR
                    ([fCBA].[Fax] LIKE '%' + @Fax + '%') OR
                    ([fCTA].[Fax] LIKE '%' + @Fax + '%')
                )
            ) AND
            (
                (@Email IS NULL) OR
                (
                    ([fCA].[Email] LIKE '%' + @Email + '%') OR
                    ([fCBA].[Email] LIKE '%' + @Email + '%') OR
                    ([fCTA].[Email] LIKE '%' + @Email + '%')
                )
            ) AND
            ((@StatusID IS NULL) OR ([C].[StatusID] = @StatusID)) AND
            ((@IsDeleted IS NULL) OR ([C].[IsDeleted] = @IsDeleted)) AND
            (
                ((@SalesmanIDRoute IS NULL) OR (@WeekIDEqual IS NULL) OR (@DayIDEqual IS NULL)) OR
                (
                    (@SalesmanIDRoute IS NOT NULL) AND (@WeekIDEqual IS NOT NULL) AND (@DayIDEqual IS NOT NULL) AND
                    (
                        [C].[ID] IN
                        (
                            SELECT [RP].[CustomerID] FROM [dbo].[RoutePlan] [RP]
                                WHERE ([RP].[SalesmanID] = @SalesmanIDRoute) AND ([RP].[WeekID] = @WeekIDEqual) AND ([RP].[DayID] = @DayIDEqual)
                        )
                    )
                )
            ) AND
            (
                ((@SalesmanIDRoute IS NULL) OR (@WeekIDNotEqual IS NULL) OR (@DayIDNotEqual IS NULL)) OR
                (
                    (@SalesmanIDRoute IS NOT NULL) AND (@WeekIDNotEqual IS NOT NULL) AND (@DayIDNotEqual IS NOT NULL) AND
                    (
                        [C].[ID] IN
                        (
                            SELECT [RP].[CustomerID] FROM [dbo].[RoutePlan] [RP]
                                WHERE [RP].[SalesmanID] = @SalesmanIDRoute AND ([RP].[WeekID] != @WeekIDNotEqual OR [RP].[DayID] != @DayIDNotEqual)
                        )
                         AND
                        [C].[ID] NOT IN
                        (
                            SELECT [RP].[CustomerID] FROM [dbo].[RoutePlan] [RP]
                                WHERE [RP].[SalesmanID] = @SalesmanIDRoute AND ([RP].[WeekID] = @WeekIDNotEqual AND [RP].[DayID] = @DayIDNotEqual)
                        )
                    )
                )
            )
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vCustomer]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vCustomer];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fCustomer] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vCustomer]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [Customer],
            [SalesmanID],
            [SalesmanCode],
            [SalesmanName],
            [Salesman],
            [WarehouseID],
            [WarehouseCode],
            [WarehouseName],
            [Warehouse],
            [SiteID],
            [SiteCode],
            [SiteName],
            [Site],
            [CompanyID],
            [CompanyCode],
            [CompanyName],
            [Company],
            [AreaID],
            [AreaCode],
            [AreaName],
            [Area],
            [RegionID],
            [RegionCode],
            [RegionName],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [SiteDistributionTypeID],
            [SiteDistributionTypeName],            
            [WarehouseTypeID],
            [WarehouseTypeName],
            [SalesmanGroupID],
            [SalesmanGroupName],
            [SalesmanCategoryID],
            [SalesmanCategoryName],
            [SalesmanPhoneID],
            [SalesmanSFA],
            [SalesmanStatusID],
            [SalesmanStatusName],
            [IsSalesmanDeleted],
            [RegisteredDate],
            [TermOfPaymentID],
            [TermOfPaymentName],
            [CreditLimit],
            [PriceGroupID],
            [PriceGroupName],
            [DiscountGroupID],
            [DiscountGroupCode],
            [DiscountGroupName],
            [DiscountGroup],
            [DiscountGroupDescription],
            [DiscountGroupStatusID],
            [DiscountGroupStatusName],
            [IsTaxNumberAvailable],
            [TaxSAPCode],
            [TaxNumber],
            [Address1],
            [Address2],
            [Address3],
            [Address],
            [City],
            [StateProvince],
            [CountryID],
            [CountryName],
            [ZipCode],
            [Phone1],
            [Phone2],
            [Phone3],
            [Fax],
            [Email],
            [Longitude],
            [Latitude],
            [IsBillSameAsAddress],
            [BillName],
            [BillAddress1],
            [BillAddress2],
            [BillAddress3],
            [BillAddress],
            [BillCity],
            [BillStateProvince],
            [BillCountryID],
            [BillCountryName],
            [BillZipCode],
            [BillPhone1],
            [BillPhone2],
            [BillPhone3],
            [BillFax],
            [BillEmail],
            [IsTaxSameAsAddress],
            [IsTaxSameAsBillAddress],
            [TaxName],
            [TaxAddress1],
            [TaxAddress2],
            [TaxAddress3],
            [TaxAddress],
            [TaxCity],
            [TaxStateProvince],
            [TaxCountryID],
            [TaxCountryName],
            [TaxZipCode],
            [TaxPhone1],
            [TaxPhone2],
            [TaxPhone3],
            [TaxFax],
            [TaxEmail],
            [AdditionalInfo1],
            [AdditionalInfo2],
            [AdditionalInfo3],
            [AdditionalInfo4],
            [AdditionalInfo5],
            [AdditionalInfo6],
            [AdditionalInfo7],
            [AdditionalInfo8],
            [AdditionalInfo9],
            [AdditionalInfo10],
            [Category1ID],
            [Category1Code],
            [Category1Name],
            [Category1],
            [Category2ID],
            [Category2Code],
            [Category2Name],
            [Category2],
            [Category3ID],
            [Category3Code],
            [Category3Name],
            [Category3],
            [Category4ID],
            [Category4Code],
            [Category4Name],
            [Category4],
            [Category5ID],
            [Category5Code],
            [Category5Name],
            [Category5],
            [Category6ID],
            [Category6Code],
            [Category6Name],
            [Category6],
            [Category7ID],
            [Category7Code],
            [Category7Name],
            [Category7],
            [Category8ID],
            [Category8Code],
            [Category8Name],
            [Category8],
            [Category9ID],
            [Category9Code],
            [Category9Name],
            [Category9],
            [Category10ID],
            [Category10Code],
            [Category10Name],
            [Category10],
            [Photo],
            [StatusID],
            [StatusName],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted],
            [SalesmanIDRoute],
            [WeekIDEqual],
            [DayIDEqual],
            [WeekIDNotEqual],
            [DayIDNotEqual]
        FROM
			[dbo].[fCustomer]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
