USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
	WHERE object_id = OBJECT_ID(N'[dbo].[fCustomerCategory]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
	DROP FUNCTION [dbo].[fCustomerCategory];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 16 Mar 2016 10:55:43
-- Description   : Provide function to retrieve [dbo].[CustomerCategory] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fCustomerCategory]
(
        @ID int,
        @Code nvarchar(10),
        @Name nvarchar(50),
		@ParentID int,
		@ParentCode nvarchar(10),
		@ParentName nvarchar(50),
		@Group nvarchar(20),
        @IsDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [CC].[ID],
            [CC].[Code],
            [CC].[Name],
            [dbo].[fCodeNameFormatter]([CC].[Code], [CC].[Name]) [Category],
			[CC].[ParentID],
			[CC2].[Code] [ParentCode],
			[CC2].[Name] [ParentName],
			[dbo].[fCodeNameFormatter]([CC2].[Code], [CC2].[Name]) [Parent],
			[CC].[Group],
            [CC].[CreatedDate],
            [CC].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [CC].[ModifiedDate],
            [CC].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [CC].[IsDeleted]
        FROM
			[dbo].[CustomerCategory] [CC] LEFT OUTER JOIN
			[dbo].[CustomerCategory] [CC2] ON ([CC].[ParentID] = [CC2].[ID]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([CC].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([CC].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR ([CC].[ID] = @ID)) AND
            ((@Code IS NULL) OR ([CC].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([CC].[Name] LIKE '%' + @Name + '%')) AND
            ((@ParentID IS NULL) OR ([CC].[ParentID] = @ParentID)) AND
            ((@ParentCode IS NULL) OR ([CC2].[Code] = @ParentCode)) AND
            ((@ParentName IS NULL) OR ([CC2].[Name] = @ParentName)) AND			
            ((@Group IS NULL) OR ([CC].[Group] = @Group)) AND
            ((@IsDeleted IS NULL) OR ([CC].[IsDeleted] = @IsDeleted))
);
GO



IF EXISTS(SELECT * FROM sys.objects
	WHERE object_id = OBJECT_ID(N'[dbo].[vCustomerCategory]') AND type IN ( N'V' ))
	DROP VIEW [dbo].[vCustomerCategory];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 16 Mar 2016 10:55:43
-- Description   : Provide view (model) to retrieve [dbo].[fCustomerCategory] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vCustomerCategory]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [Category],
			[ParentID],
            [ParentCode],
            [ParentName],
			[Parent],
			[Group],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted]
        FROM
			[dbo].[fCustomerCategory]
            (
                NULL,
                NULL,
                NULL,
                NULL,
				NULL,
				NULL,
				NULL,
				NULL
            )
);
GO
