USE [IDOS];
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fDailySalesmanInventoryReport]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fDailySalesmanInventoryReport];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[RoutePlan] by Salesman data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fDailySalesmanInventoryReport]
(
    @ReportDateFrom date,
    @ReportDateTo date,
    @SalesmanID uniqueidentifier    
)
RETURNS TABLE 
AS
RETURN 
(
    SELECT
            [WarehouseID],
            [ProductID],
            MIN([Product]) [Product],
            SUM([QtyOnHandGood]) [QtyOnHandGood],
            SUM([QtyOnHandHold]) [QtyOnHandHold],
            SUM([QtyOnHandBad]) [QtyOnHandBad]
        FROM
        (
            SELECT
                    [SOHCA].[WarehouseID],
                    [SOHCA].[ProductID],
                    [SOHCA].[ProductLotID],
                    [dbo].[fCodeNameFormatter]([P].[Code], [P].[Name]) [Product],
                    [PL].[Code] [ProductLotCode],
                    ([SOHCA].[QtyPeriodOnHandGood] + [SOHCA].[QtyTransactionGood]) [QtyOnHandGood],
                    ([SOHCA].[QtyPeriodOnHandHold] + [SOHCA].[QtyTransactionHold]) [QtyOnHandHold],
                    ([SOHCA].[QtyPeriodOnHandBad] + [SOHCA].[QtyTransactionBad]) [QtyOnHandBad]
                FROM
                    [dbo].[Salesman] [S] INNER JOIN
                    [dbo].[fStockOnHandCalc]
                    (
                        NULL,
                        @ReportDateTo,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL,    
                        NULL,
                        NULL
                    ) [SOHCA] ON ([S].[WarehouseID] = [SOHCA].[WarehouseID]) INNER JOIN
                    [dbo].[Product] [P] ON ([SOHCA].[ProductID] = [P].[ID]) INNER JOIN
                    [dbo].[ProductLot] [PL] ON ([SOHCA].[ProductLotID] = [PL].[ID])
                WHERE
                    ((@SalesmanID IS NULL) OR ([S].[ID] = @SalesmanID))
        ) [SOHC]
        WHERE
            ([QtyOnHandGood] > 0) OR ([QtyOnHandHold] > 0) OR ([QtyOnHandBad] > 0)
        GROUP BY
            [WarehouseID],
            [ProductID]
);
GO
