USE [IDOS];
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fDailySalesmanReport]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fDailySalesmanReport];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[RoutePlan] by Salesman data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fDailySalesmanReport]
(
    @ReportDateFrom date,
    @ReportDateTo date,
    @SalesmanID uniqueidentifier    
)
RETURNS TABLE 
AS
RETURN 
(
    WITH
        TBL
        AS
        (
            SELECT
                    [ReportDate],
	                [SODocumentID],
                    [ProductID],
                    [SODocumentCode],
                    [SFAInvoiceDocumentCode],
                    [TerritoryID],
                    [Territory],
	                [RegionID],
                    [Region],
	                [AreaID],
                    [Area],
	                [CompanyID],
                    [Company],
	                [SiteID],
                    [Site],
                    [WarehouseID],
                    [Warehouse],
                    [SalesmanID],
                    [Salesman],
                    [CustomerID],
                    [Customer],
                    [CategoryCustomerType],
                    [CashPaymentAmount],
                    [CreditPaymentAmount],
                    [CreditDueDate],
                    [TrxFormBankName],
                    [TrxFormCode],
                    [TrxFormDueDate],
                    [TrxFormAmount],
                    [AdditionalCost],
                    [CreditBalance],
                    [TotalSalesOrder],
                    [ProductBrandID],
                    [ProductBrand],
                    [ProductShortName],
                    [Qty]
                FROM
                (
                    SELECT
                            [dbo].[ConvertToFirstTimeOfDay]([SO].[TransactionDate]) [ReportDate],
                            [SO].[DocumentID] [SODocumentID],
                            [SOS].[ProductID],
                            [SO].[DocumentCode] [SODocumentCode],
                            [SO].[SFAInvoiceDocumentCode],
                            [R].[TerritoryID],
                            [dbo].[fCodeNameFormatter]([SOX].[TerritoryCode], [SOX].[TerritoryName]) [Territory],
                            [A].[RegionID],
                            [dbo].[fCodeNameFormatter]([SOX].[RegionCode], [SOX].[RegionName]) [Region],
                            [ST].[AreaID],
                            [dbo].[fCodeNameFormatter]([SOX].[AreaCode], [SOX].[AreaName]) [Area],
                            [ST].[CompanyID],
                            [dbo].[fCodeNameFormatter]([SOX].[CompanyCode], [SOX].[CompanyName]) [Company],
                            [W].[SiteID],
                            [dbo].[fCodeNameFormatter]([SOX].[SiteCode], [SOX].[SiteName]) [Site],
                            [SO].[WarehouseID],
                            [dbo].[fCodeNameFormatter]
                            (
                                [SOX].[WarehouseCode],
                                (SELECT CASE WHEN [W].[TypeID] = 1 THEN '[' + [fSL].[Name] + '] ' ELSE '' END) + [SOX].[WarehouseName]
                            ) [Warehouse],
                            [SO].[SalesmanID],
                            [dbo].[fCodeNameFormatter]([SOX].[SalesmanCode], [SOX].[SalesmanName]) [Salesman],
                            [SO].[CustomerID],
                            [dbo].[fCodeNameFormatter]([SOX].[CustomerCode], [SOX].[CustomerName]) [Customer],
                            (                    
                                SELECT CASE
                                    WHEN (CHARINDEX(';', [SOX].[CustomerCategory1]) > 0) THEN SUBSTRING([SOX].[CustomerCategory1], 1, CHARINDEX(';', [SOX].[CustomerCategory1]) - 1)
                                    ELSE ''
                                END
                            ) [CategoryCustomerType],                    
                            CAST((SELECT CASE WHEN ([SO].[TermOfPaymentID] = 1) THEN [SO].[Total] ELSE NULL END) AS float) [CashPaymentAmount],
                            CAST((SELECT CASE WHEN ([SO].[TermOfPaymentID] > 1) THEN [SO].[Total] ELSE NULL END) AS float) [CreditPaymentAmount],
                            CAST(
                            (
                                SELECT CASE
                                    WHEN ([SO].[TermOfPaymentID] = 2) THEN DATEADD(d, 7, [dbo].[ConvertToFirstTimeOfDay]([SO].[TransactionDate]))
                                    WHEN ([SO].[TermOfPaymentID] = 3) THEN DATEADD(d, 14, [dbo].[ConvertToFirstTimeOfDay]([SO].[TransactionDate]))
                                    WHEN ([SO].[TermOfPaymentID] = 4) THEN DATEADD(d, 21, [dbo].[ConvertToFirstTimeOfDay]([SO].[TransactionDate]))
                                    WHEN ([SO].[TermOfPaymentID] = 5) THEN DATEADD(d, 28, [dbo].[ConvertToFirstTimeOfDay]([SO].[TransactionDate]))
                                    WHEN ([SO].[TermOfPaymentID] = 6) THEN DATEADD(d, 60, [dbo].[ConvertToFirstTimeOfDay]([SO].[TransactionDate]))
                                    WHEN ([SO].[TermOfPaymentID] = 7) THEN DATEADD(d, 90, [dbo].[ConvertToFirstTimeOfDay]([SO].[TransactionDate]))
                                    ELSE NULL
                                END
                            ) AS date) [CreditDueDate],
                            CAST('' AS nvarchar(100)) [TrxFormBankName], ----------------------------------
                            CAST('' AS nvarchar(100)) [TrxFormCode], ----------------------------------
                            CAST(NULL AS date) [TrxFormDueDate], ----------------------------------
                            CAST(0 AS float) [TrxFormAmount], ----------------------------------
                            CAST(0 AS float) [AdditionalCost], ----------------------------------
                            CAST(0 AS float) [CreditBalance], ----------------------------------
                            [SO].[Total] [TotalSalesOrder],
                            [PB].[ID] [ProductBrandID],
                            [dbo].[fCodeNameFormatter]([PB].[Code], [PB].[Name]) [ProductBrand],
                            [P].[ShortName] [ProductShortName],
                            ([SOS].[Qty] * -1) [Qty]
                        FROM
                            [dbo].[SalesOrder] [SO] INNER JOIN
                            [dbo].[SalesOrderExt] [SOX] ON ([SO].[DocumentID] = [SOX].[DocumentID]) INNER JOIN
                            [dbo].[SalesOrderSummary] [SOS] ON ([SO].[DocumentID] = [SOS].[DocumentID]) INNER JOIN                                        
                            [dbo].[Warehouse] [W] ON ([SO].[WarehouseID] = [W].[ID]) LEFT OUTER JOIN
                            [dbo].[fSystemLookup]
                            (
                                NULL,
                                NULL,
                                NULL,
                                NULL,
                                NULL,
                                NULL,
                                NULL,
                                NULL,
                                NULL,
                                'WarehouseType',
                                NULL,
                                NULL,
                                NULL
                            ) [fSL] ON ([W].[TypeID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
                            [dbo].[Site] [ST] ON ([W].[SiteID] = [ST].[ID]) LEFT OUTER JOIN
                            [dbo].[Company] [CP] ON ([ST].[CompanyID] = [CP].[ID]) LEFT OUTER JOIN
                            [dbo].[Area] [A] ON ([ST].[AreaID] = [A].[ID]) LEFT OUTER JOIN
                            [dbo].[Region] [R] ON ([A].[RegionID] = [R].[ID]) INNER JOIN
                            [dbo].[Product] [P] ON ([SOS].[ProductID] = [P].[ID]) INNER JOIN
                            [dbo].[ProductBrand] [PB] ON ([P].[BrandID] = [PB].[ID])
                        WHERE
                            ([SO].[DocumentStatusID] = 2) AND
                            ((@ReportDateFrom IS NULL) OR ([SO].[TransactionDate] >= [dbo].[ConvertToFirstTimeOfDay](@ReportDateFrom))) AND
                            ((@ReportDateTo IS NULL) OR ([SO].[TransactionDate] <= [dbo].[ConvertToLastTimeOfDay](@ReportDateTo))) AND
                            ((@SalesmanID IS NULL) OR ([SalesmanID] = @SalesmanID))
                ) [RSOS]
        )
        SELECT
                [vROW].[RowNumber],
                [vDSM].[SODocumentID],
                [vDSM].[RowArea1],
                [vDSM].[RowArea2],
                [vDSM].[ColumnArea1],
                [vDSM].[ColumnArea2],
                [vDSM].[DataArea1],
                [vDSM].[DataArea2],
                [vDSM].[DataArea3],
                [vDSM].[DataArea4],
                [vDSM].[DataArea5]
            FROM
            (
                SELECT
                        CAST(ROW_NUMBER() OVER (ORDER BY [SODocumentID]) AS int) [RowNumber],
                        [SODocumentID]
                    FROM
                        TBL
                    GROUP BY
                        [SODocumentID]
            ) [vROW] INNER JOIN
            (
                SELECT
                        [SODocumentID],
                        MIN([Customer]) [RowArea1],
                        MIN([CategoryCustomerType]) [RowArea2],
                        '{1_Sales}' [ColumnArea1],
                        '{1_SalesFields}' [ColumnArea2],
                        CAST(MIN([SODocumentCode]) AS nvarchar(100)) [DataArea1],
                        CAST(MIN([SFAInvoiceDocumentCode]) AS nvarchar(100)) [DataArea2],
                        CAST(MIN(ISNULL([CashPaymentAmount], 0)) AS nvarchar(100)) [DataArea3],
                        CAST(MIN(ISNULL([CreditPaymentAmount], 0)) AS nvarchar(100)) [DataArea4],
                        CAST(MIN(RIGHT('0000' + CAST(YEAR([CreditDueDate]) AS nvarchar(4)), 4) + '-' + RIGHT('00' + CAST(MONTH([CreditDueDate]) AS nvarchar(2)), 2) + '-' + RIGHT('00' + CAST(DAY([CreditDueDate]) AS nvarchar(2)), 2)) AS nvarchar(100)) [DataArea5]
                    FROM
                        TBL
                    GROUP BY
                        [SODocumentID],
                        [SalesmanID],
                        [CustomerID]
                UNION ALL
                SELECT
                        [SODocumentID],
                        MIN([Customer]) [RowArea1],
                        MIN([CategoryCustomerType]) [RowArea2],
                        '{2_Payments}' [ColumnArea1],
                        '{1_PaymentCash}' [ColumnArea2],
                        CAST(MIN([CashPaymentAmount]) AS nvarchar(100)) [DataArea1],
                        CAST(NULL AS nvarchar(100)) [DataArea2],
                        CAST(NULL AS nvarchar(100)) [DataArea3],
                        CAST(NULL AS nvarchar(100)) [DataArea4],
                        CAST(NULL AS nvarchar(100)) [DataArea5]
                    FROM
                        TBL
                    GROUP BY
                        [SODocumentID],
                        [SalesmanID],
                        [CustomerID]
                UNION ALL
                SELECT
                        [SODocumentID],
                        MIN([Customer]) [RowArea1],
                        MIN([CategoryCustomerType]) [RowArea2],
                        '{2_Payments}' [ColumnArea1],
                        '{2_PaymentTransferForm}' [ColumnArea2],                
                        CAST(MIN([TrxFormBankName]) AS nvarchar(100)) [DataArea1],
                        CAST(MIN([TrxFormCode]) AS nvarchar(100)) [DataArea2],
                        CAST(MIN(RIGHT('0000' + CAST(YEAR([TrxFormDueDate]) AS nvarchar(4)), 4) + '-' + RIGHT('00' + CAST(MONTH([TrxFormDueDate]) AS nvarchar(2)), 2) + '-' + RIGHT('00' + CAST(DAY([TrxFormDueDate]) AS nvarchar(2)), 2)) AS nvarchar(100)) [DataArea3],
                        CAST(MIN(ISNULL([TrxFormAmount], 0)) AS nvarchar(100)) [DataArea4],
                        CAST(NULL AS nvarchar(100)) [DataArea5]
                    FROM
                        TBL
                    GROUP BY
                        [SODocumentID],
                        [SalesmanID],
                        [CustomerID]
                UNION ALL
                SELECT
                        [SODocumentID],
                        MIN([Customer]) [RowArea1],
                        MIN([CategoryCustomerType]) [RowArea2],
                        '{2_Payments}' [ColumnArea1],
                        '{3_AdditionalCost}' [ColumnArea2],
                        CAST(MIN([AdditionalCost]) AS nvarchar(100)) [DataArea1],
                        CAST(NULL AS nvarchar(100)) [DataArea2],
                        CAST(NULL AS nvarchar(100)) [DataArea3],
                        CAST(NULL AS nvarchar(100)) [DataArea4],
                        CAST(NULL AS nvarchar(100)) [DataArea5]
                    FROM
                        TBL
                    GROUP BY
                        [SODocumentID],
                        [SalesmanID],
                        [CustomerID]
                UNION ALL
                SELECT
                        [SODocumentID],
                        MIN([Customer]) [RowArea1],
                        MIN([CategoryCustomerType]) [RowArea2],
                        '{3}' [ColumnArea1],
                        '{1_CreditBalance}' [ColumnArea2],
                        CAST(MIN(ISNULL([CreditBalance], 0)) AS nvarchar(100)) [DataArea1],
                        CAST(NULL AS nvarchar(100)) [DataArea2],
                        CAST(NULL AS nvarchar(100)) [DataArea3],
                        CAST(NULL AS nvarchar(100)) [DataArea4],
                        CAST(NULL AS nvarchar(100)) [DataArea5]
                    FROM
                        TBL
                    GROUP BY
                        [SODocumentID],
                        [SalesmanID],
                        [CustomerID]
                UNION ALL
                SELECT
                        [SODocumentID],
                        MIN([Customer]) [RowArea1],
                        MIN([CategoryCustomerType]) [RowArea2],
                        MIN([ProductBrand]) [ColumnArea1],
                        MIN([ProductShortName]) [ColumnArea2],
                        CAST(SUM([Qty]) AS nvarchar(100)) [DataArea1],
                        CAST(NULL AS nvarchar(100)) [DataArea2],
                        CAST(NULL AS nvarchar(100)) [DataArea3],
                        CAST(NULL AS nvarchar(100)) [DataArea4],
                        CAST(NULL AS nvarchar(100)) [DataArea5]
                    FROM
                        TBL
                    GROUP BY
                        [SODocumentID],
                        [SalesmanID],
                        [CustomerID],
                        [ProductBrandID],
                        [ProductID]
            ) [vDSM] ON ([vROW].[SODocumentID] = [vDSM].[SODocumentID])
);
GO
