USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fDiscountStrata]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fDiscountStrata];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 22:02:31
-- Description   : Provide function to retrieve [dbo].[DiscountStrata] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fDiscountStrata]
(
    @ID int,
    @Code nvarchar(20),
    @Name nvarchar(50),
    @ValidDateFrom datetime,
    @ValidDateTo datetime,
    @StatusID int,
    @IsDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [DS].[ID],
            [DS].[Code],
            [DS].[Name],
            [dbo].[fCodeNameFormatter]([DS].[Code], [DS].[Name]) [DiscountStrata],
            [DS].[ValidDateFrom],
            [DS].[ValidDateTo],
            [DS].[StatusID],
            [fSL].[Name] [StatusName],
            [DS].[CreatedDate],
            [DS].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [DS].[ModifiedDate],
            [DS].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [DS].[IsDeleted]
        FROM
			[dbo].[DiscountStrata] [DS] LEFT OUTER JOIN            
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'DiscountStrataStatus',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([DS].[StatusID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([DS].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([DS].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR ([DS].[ID] = @ID)) AND
            ((@Code IS NULL) OR ([DS].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([DS].[Name] LIKE '%' + @Name + '%')) AND
            (
                ([dbo].[ValidateMaxDate]([DS].[ValidDateFrom]) >= [dbo].[ValidateMinDate](@ValidDateFrom)) OR
                ([dbo].[ValidateMinDate]([DS].[ValidDateTo]) <= [dbo].[ValidateMaxDate](@ValidDateTo))
            ) AND
            ((@StatusID IS NULL) OR ([DS].[StatusID] = @StatusID)) AND
            ((@IsDeleted IS NULL) OR ([DS].[IsDeleted] = @IsDeleted))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vDiscountStrata]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vDiscountStrata];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 22:02:32
-- Description   : Provide view (model) to retrieve [dbo].[fDiscountStrata] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vDiscountStrata]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [DiscountStrata],
            [ValidDateFrom],
            [ValidDateTo],
            [StatusID],
            [StatusName],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted]
        FROM
			[dbo].[fDiscountStrata]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
