USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fDiscountStrataDetails]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fDiscountStrataDetails];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 22:14:40
-- Description   : Provide function to retrieve [dbo].[DiscountStrataDetails] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fDiscountStrataDetails]
(
    @ID int,
    @StrataID int
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [DSD].[ID],
            [DSD].[StrataID],
            [DSD].[Minimum],
            [DSD].[Maximum],
            [DSD].[DiscountPercentage]
        FROM
			[dbo].[DiscountStrataDetails] [DSD]            
		WHERE
            ((@ID IS NULL) OR ([DSD].[ID] = @ID)) AND
            ((@StrataID IS NULL) OR ([DSD].[StrataID] = @StrataID))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vDiscountStrataDetails]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vDiscountStrataDetails];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 22:14:40
-- Description   : Provide view (model) to retrieve [dbo].[fDiscountStrataDetails] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vDiscountStrataDetails]
AS
(
    SELECT
            [ID],
            [StrataID],
            [Minimum],
            [Maximum],
            [DiscountPercentage]
        FROM
			[dbo].[fDiscountStrataDetails]
            (
                NULL,
                NULL
            )
);
GO
