USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fDiscountGroup]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fDiscountGroup];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:11:40
-- Description   : Provide function to retrieve [dbo].[DiscountGroup] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fDiscountGroup]
(
    @ID int,
    @Code nvarchar(10),
    @Name nvarchar(50),
    @Description nvarchar(200),
    @StatusID int,
    @IsDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [DG].[ID],
            [DG].[Code],
            [DG].[Name],
            [dbo].[fCodeNameFormatter]([DG].[Code], [DG].[Name]) [DiscountGroup],
            [DG].[Description],
            [DG].[StatusID],
            [fSL].[Name] [StatusName],
            [DG].[CreatedDate],
            [DG].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [DG].[ModifiedDate],
            [DG].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [DG].[IsDeleted]
        FROM
			[dbo].[DiscountGroup] [DG] LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'DiscountGroupStatus',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([DG].[StatusID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([DG].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([DG].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR ([DG].[ID] = @ID)) AND
            ((@Code IS NULL) OR ([DG].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([DG].[Name] LIKE '%' + @Name + '%')) AND
            ((@Description IS NULL) OR ([DG].[Description] LIKE '%' + @Description + '%')) AND
            ((@StatusID IS NULL) OR ([DG].[StatusID] = @StatusID)) AND
            ((@IsDeleted IS NULL) OR ([DG].[IsDeleted] = @IsDeleted))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vDiscountGroup]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vDiscountGroup];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:11:40
-- Description   : Provide view (model) to retrieve [dbo].[fDiscountGroup] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vDiscountGroup]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [DiscountGroup],
            [Description],
            [StatusID],
            [StatusName],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted]
        FROM
			[dbo].[fDiscountGroup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
