USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fInvoice]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fInvoice];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide function to retrieve [dbo].[Invoice] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fInvoice]
(
    @DocumentID uniqueidentifier,
    @DocumentCode nvarchar(30),
    @TransactionDateFrom datetime,
    @TransactionDateTo datetime,
    @RefDocumentID uniqueidentifier,
    @RefTransactionTypeID int,
    @DocumentStatusID int,
    @PostedDateFrom datetime,
    @PostedDateTo datetime
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [I].[DocumentID],
            [I].[DocumentCode],
            [I].[TransactionDate],
            [I].[DocumentStatusID],
            [I].[RefDocumentID],
            [I].[RefTransactionTypeID],
            [fSL].[Name] [DocumentStatusName],
            [I].[PostedDate],
            [I].[CreatedDate],
            [I].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [I].[ModifiedDate],
            [I].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName]
        FROM
			[dbo].[Invoice] [I] LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'DocumentStatus',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([I].[DocumentStatusID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([I].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([I].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@DocumentID IS NULL) OR ([I].[DocumentID] = @DocumentID)) AND
            ((@DocumentCode IS NULL) OR ([I].[DocumentCode] LIKE '%' + @DocumentCode + '%')) AND
            ((@RefDocumentID IS NULL) OR ([I].[RefDocumentID] = @RefDocumentID)) AND
            ((@RefTransactionTypeID IS NULL) OR ([I].[RefTransactionTypeID] = @RefTransactionTypeID)) AND
            ([dbo].[ValidateMaxDate]([I].[TransactionDate]) >= [dbo].[ValidateMinDate](@TransactionDateFrom)) AND
            ([dbo].[ValidateMinDate]([I].[TransactionDate]) <= [dbo].[ValidateMaxDate](@TransactionDateTo)) AND
            ((@DocumentStatusID IS NULL) OR ([I].[DocumentStatusID] = @DocumentStatusID)) AND
            ([dbo].[ValidateMaxDate]([I].[PostedDate]) >= [dbo].[ValidateMinDate](@PostedDateFrom)) AND
            ([dbo].[ValidateMinDate]([I].[PostedDate]) <= [dbo].[ValidateMaxDate](@PostedDateTo))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vInvoice]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vInvoice];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide view (model) to retrieve [dbo].[fInvoice] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vInvoice]
AS
(
    SELECT
            [DocumentID],
            [DocumentCode],
            [TransactionDate],
            [RefDocumentID],
            [RefTransactionTypeID],
            [DocumentStatusID],
            [DocumentStatusName],
            [PostedDate],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName]
        FROM
			[dbo].[fInvoice]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL                
            )
);
GO
