USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fProductAdditionalInfo]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fProductAdditionalInfo];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[ProductAdditionalInfo] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fProductAdditionalInfo]
(
    @ProductID int,
    @AdditionalInfo nvarchar(100)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [PAI].[ProductID],
            [PAI].[AdditionalInfo1],
            [PAI].[AdditionalInfo2],
            [PAI].[AdditionalInfo3],
            [PAI].[AdditionalInfo4],
            [PAI].[AdditionalInfo5],
            [PAI].[AdditionalInfo6],
            [PAI].[AdditionalInfo7],
            [PAI].[AdditionalInfo8],
            [PAI].[AdditionalInfo9],
            [PAI].[AdditionalInfo10] 
        FROM
			[dbo].[ProductAdditionalInfo] [PAI]
		WHERE
            ((@ProductID IS NULL) OR ([PAI].[ProductID] = @ProductID)) AND
            (
                (@AdditionalInfo IS NULL) OR
                (
                    ([PAI].[AdditionalInfo1] LIKE '%' + @AdditionalInfo + '%') OR
                    ([PAI].[AdditionalInfo2] LIKE '%' + @AdditionalInfo + '%') OR
                    ([PAI].[AdditionalInfo3] LIKE '%' + @AdditionalInfo + '%') OR
                    ([PAI].[AdditionalInfo4] LIKE '%' + @AdditionalInfo + '%') OR
                    ([PAI].[AdditionalInfo5] LIKE '%' + @AdditionalInfo + '%') OR
                    ([PAI].[AdditionalInfo6] LIKE '%' + @AdditionalInfo + '%') OR
                    ([PAI].[AdditionalInfo7] LIKE '%' + @AdditionalInfo + '%') OR
                    ([PAI].[AdditionalInfo8] LIKE '%' + @AdditionalInfo + '%') OR
                    ([PAI].[AdditionalInfo9] LIKE '%' + @AdditionalInfo + '%') OR
                    ([PAI].[AdditionalInfo10] LIKE '%' + @AdditionalInfo + '%')
                )
            )
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vProductAdditionalInfo]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vProductAdditionalInfo];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fProductAdditionalInfo] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vProductAdditionalInfo]
AS
(
    SELECT
            [ProductID],
            [AdditionalInfo1],
            [AdditionalInfo2],
            [AdditionalInfo3],
            [AdditionalInfo4],
            [AdditionalInfo5],
            [AdditionalInfo6],
            [AdditionalInfo7],
            [AdditionalInfo8],
            [AdditionalInfo9],
            [AdditionalInfo10] 
        FROM
			[dbo].[fProductAdditionalInfo]
            (
                NULL,
                NULL
            )
);
GO
