USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fProductBrand]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fProductBrand];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:11:40
-- Description   : Provide function to retrieve [dbo].[ProductBrand] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fProductBrand]
(
    @ID int,
    @Code nvarchar(10),
    @Name nvarchar(50),
    @IsDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [PB].[ID],
            [PB].[Code],
            [PB].[Name],
            [dbo].[fCodeNameFormatter]([PB].[Code], [PB].[Name]) [Brand],
            [PB].[CreatedDate],
            [PB].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [PB].[ModifiedDate],
            [PB].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [PB].[IsDeleted]
        FROM
			[dbo].[ProductBrand] [PB] LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([PB].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([PB].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR ([PB].[ID] = @ID)) AND
            ((@Code IS NULL) OR ([PB].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([PB].[Name] LIKE '%' + @Name + '%')) AND
            ((@IsDeleted IS NULL) OR ([PB].[IsDeleted] = @IsDeleted))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vProductBrand]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vProductBrand];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:11:40
-- Description   : Provide view (model) to retrieve [dbo].[fProductBrand] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vProductBrand]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [Brand],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted]
        FROM
			[dbo].[fProductBrand]
            (
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
