USE [IDOS]
GO

INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (19, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (21, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (22, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (23, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (24, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (26, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (27, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (28, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (29, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (31, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (33, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (34, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (35, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (36, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (37, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (38, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (39, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (41, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (42, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (43, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [dbo].[ProductAdditionalInfo] ([ProductID], [AdditionalInfo1], [AdditionalInfo2], [AdditionalInfo3], [AdditionalInfo4], [AdditionalInfo5], [AdditionalInfo6], [AdditionalInfo7], [AdditionalInfo8], [AdditionalInfo9], [AdditionalInfo10]) VALUES (44, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
GO
