USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fProduct]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fProduct];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:12:32
-- Description   : Provide function to retrieve [dbo].[Product] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fProduct]
(
    @ID int,
    @Code nvarchar(10),
    @Name nvarchar(50),
    @BrandID int,
    @BrandCode nvarchar(10),
    @BrandName nvarchar(50),
    @ShortName nvarchar(30),
    @StatusID int,
    @AdditionalInfo nvarchar(100),
    @IsDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [P].[ID],
            [P].[Code],
            [P].[Name],
            [dbo].[fCodeNameFormatter]([P].[Code], [P].[Name]) [Product],
            [P].[BrandID],
            [fPB].[Code] [BrandCode],
            [fPB].[Name] [BrandName],
            [fPB].[Brand],
            [P].[ShortName],
            [P].[UOMLID],
            [fSL1].[Name] [UOMLName],
            [P].[UOMMID],
            [fSL2].[Name] [UOMMName],
            [P].[UOMSID],
            [fSL3].[Name] [UOMSName],
            [P].[Weight],
            [P].[DimensionL],
            [P].[DimensionW],
            [P].[DimensionH],
            [P].[ConversionL],
            [P].[ConversionM],
            [P].[ConversionS],
            [P].[StatusID],
            [fSL4].[Name] [StatusName],
            [fPAI].[AdditionalInfo1],
            [fPAI].[AdditionalInfo2],
            [fPAI].[AdditionalInfo3],
            [fPAI].[AdditionalInfo4],
            [fPAI].[AdditionalInfo5],
            [fPAI].[AdditionalInfo6],
            [fPAI].[AdditionalInfo7],
            [fPAI].[AdditionalInfo8],
            [fPAI].[AdditionalInfo9],
            [fPAI].[AdditionalInfo10],
            [P].[CreatedDate],
            [P].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [P].[ModifiedDate],
            [P].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [P].[IsDeleted]
        FROM
			[dbo].[Product] [P] INNER JOIN
            [dbo].[fProductBrand]
            (
                @BrandID,
                @BrandCode,
                @BrandName,
                NULL
            ) [fPB] ON ([P].[BrandID] = [fPB].[ID]) INNER JOIN
            [dbo].[fProductAdditionalInfo]
            (
                @ID,
                @AdditionalInfo
            ) [fPAI] ON ([P].[ID] = [fPAI].[ProductID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'ProductUOM',
                NULL,
                NULL,
                NULL
            ) [fSL1] ON ([P].[UOMLID] = [fSL1].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'ProductUOM',
                NULL,
                NULL,
                NULL
            ) [fSL2] ON ([P].[UOMMID] = [fSL2].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'ProductUOM',
                NULL,
                NULL,
                NULL
            ) [fSL3] ON ([P].[UOMSID] = [fSL3].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'ProductStatus',
                NULL,
                NULL,
                NULL
            ) [fSL4] ON ([P].[StatusID] = [fSL4].[Value_Int32]) LEFT OUTER JOIN        
            [dbo].[User] [CU] ON ([P].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([P].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR ([P].[ID] = @ID)) AND
            ((@Code IS NULL) OR ([P].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([P].[Name] LIKE '%' + @Name + '%')) AND
            ((@ShortName IS NULL) OR ([P].[ShortName] LIKE '%' + @ShortName + '%')) AND
            ((@StatusID IS NULL) OR ([P].[StatusID] = @StatusID)) AND
            ((@IsDeleted IS NULL) OR ([P].[IsDeleted] = @IsDeleted))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vProduct]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vProduct];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:12:32
-- Description   : Provide view (model) to retrieve [dbo].[fProduct] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vProduct]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [Product],
            [BrandID],
            [BrandCode],
            [BrandName],
            [Brand],
            [ShortName],
            [UOMLID],
            [UOMLName],
            [UOMMID],
            [UOMMName],
            [UOMSID],
            [UOMSName],
            [Weight],
            [DimensionL],
            [DimensionW],
            [DimensionH],
            [ConversionL],
            [ConversionM],
            [ConversionS],
            [StatusID],
            [StatusName],
            [AdditionalInfo1],
            [AdditionalInfo2],
            [AdditionalInfo3],
            [AdditionalInfo4],
            [AdditionalInfo5],
            [AdditionalInfo6],
            [AdditionalInfo7],
            [AdditionalInfo8],
            [AdditionalInfo9],
            [AdditionalInfo10],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted]
        FROM
			[dbo].[fProduct]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
