USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fPromoMaterialActivity]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fPromoMaterialActivity];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide function to retrieve [dbo].[PromoMaterialActivity] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fPromoMaterialActivity]
(
    @ID uniqueidentifier,
    @ActivityDateFrom datetime,
    @ActivityDateTo datetime,
    @SalesmanID uniqueidentifier,
    @CallDateFrom datetime,
    @CallDateTo datetime,
    @CustomerID uniqueidentifier    
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [PMA].[ID],
            [PMA].[ActivityDate],
            [PMA].[SalesmanCallID],            
            [SC].[SalesmanID],
            [SC].[CallDate],
            [SC].[CustomerID],
            [PMA].[AttachmentFile],
            [PMA].[CreatedDate],
            [PMA].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName]
        FROM
			[dbo].[PromoMaterialActivity] [PMA] INNER JOIN
            [dbo].[SalesmanCall] [SC] ON ([PMA].[SalesmanCallID] = [SC].[ID]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([PMA].[CreatedByUserID] = [CU].[ID])
		WHERE
            ((@ActivityDateFrom IS NULL) OR ([dbo].[ValidateMaxDate]([PMA].[ActivityDate]) >= [dbo].[ValidateMinDate](@ActivityDateFrom))) AND
            ((@ActivityDateTo IS NULL) OR ([dbo].[ValidateMinDate]([PMA].[ActivityDate]) <= [dbo].[ValidateMaxDate](@ActivityDateTo))) AND
            ((@SalesmanID IS NULL) OR (@SalesmanID = [SC].[ID])) AND
            ((@CallDateFrom IS NULL) OR ([dbo].[ConvertToFirstTimeOfDay]([SC].[CallDate]) >= [dbo].[ConvertToFirstTimeOfDay](@CallDateFrom))) AND
            ((@CallDateTo IS NULL) OR ([dbo].[ConvertToLastTimeOfDay]([SC].[CallDate]) <= [dbo].[ConvertToLastTimeOfDay](@CallDateTo))) AND
            ((@CustomerID IS NULL) OR ([SC].[CustomerID] = @CustomerID))            
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vPromoMaterialActivity]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vPromoMaterialActivity];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide view (model) to retrieve [dbo].[fPromoMaterialActivity] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vPromoMaterialActivity]
AS
(
    SELECT
            [ID],
            [ActivityDate],
            [SalesmanCallID],            
            [SalesmanID],
            [CallDate],
            [CustomerID],
            [AttachmentFile],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName]
        FROM
			[dbo].[fPromoMaterialActivity]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL                
            )
);
GO
