USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fRegion]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fRegion];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:12:32
-- Description   : Provide function to retrieve [dbo].[Region] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fRegion]
(
    @ID int,
    @Code nvarchar(10),
    @Name nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),
    @IsDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [R].[ID],
            [R].[Code],
            [R].[Name],
            [dbo].[fCodeNameFormatter]([R].[Code], [R].[Name]) [Region],
            [R].[TerritoryID],
            [fT].[Code] [TerritoryCode],
            [fT].[Name] [TerritoryName],
            [fT].[Territory],
            [R].[CreatedDate],
            [R].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [R].[ModifiedDate],
            [R].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [R].[IsDeleted]
        FROM
			[dbo].[Region] [R] INNER JOIN
            [dbo].[fTerritory]
            (
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,
                NULL
            ) [fT] ON ([R].[TerritoryID] = [fT].[ID]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([R].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([R].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR ([R].[ID] = @ID)) AND
            ((@Code IS NULL) OR ([R].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([R].[Name] LIKE '%' + @Name + '%')) AND
            ((@IsDeleted IS NULL) OR ([R].[IsDeleted] = @IsDeleted))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vRegion]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vRegion];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:12:32
-- Description   : Provide view (model) to retrieve [dbo].[fRegion] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vRegion]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted]
        FROM
			[dbo].[fRegion]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
