USE [IDOS];
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fRoutePlanCustomer]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fRoutePlanCustomer];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[RoutePlan] by Customer data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fRoutePlanCustomer]
(
    @CustomerID uniqueidentifier,
    @SalesmanID uniqueidentifier,
    @WeekID int,
    @DayID int,
    @CustomerCode nvarchar(20),
    @CustomerName nvarchar(50),
    @SalesmanCode nvarchar(20),
    @SalesmanName nvarchar(50),
    @WarehouseID uniqueidentifier,
    @WarehouseCode nvarchar(10),
    @WarehouseName nvarchar(50),
    @SiteID uniqueidentifier,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),    
    @SiteDistributionTypeID int,
    @WarehouseTypeID int,
    @SalesmanGroupID int,
    @SalesmanCategoryID int,
    @SalesmanStatusID int,
    @OrderBySalesmanID uniqueidentifier,
    @FilterByKeywords nvarchar(MAX)
)
RETURNS TABLE 
AS
RETURN 
(
    SELECT
	        [fC].[ID] [CustomerID],
            ISNULL([RPC].[SalesmanID], CAST('00000000-0000-0000-0000-000000000000' AS uniqueidentifier)) [SalesmanID],
            [fC].[Code] [CustomerCode],
            [fC].[Name] [CustomerName],
            [fC].[Customer],
            [fC].[Address1] [CustomerAddress1],
            [fC].[Address2] [CustomerAddress2],
            [fC].[Address3] [CustomerAddress3],
            [fC].[Address] [CustomerAddress],
            [fS].[Code] [SalesmanCode],
            [fS].[Name] [SalesmanName],
            [fS].[Salesman],
            [fS].[WarehouseID],
            [fS].[WarehouseCode],
            [fS].[WarehouseName],
            [fS].[Warehouse],
            [fC].[SiteID],
            [fC].[SiteCode],
            [fC].[SiteName],
            [fC].[Site],
            [fC].[CompanyID],
            [fC].[CompanyCode],
            [fC].[CompanyName],
            [fC].[Company],
            [fC].[AreaID],
            [fC].[AreaCode],
            [fC].[AreaName],
            [fC].[Area],
            [fC].[RegionID],
            [fC].[RegionCode],
            [fC].[RegionName],
            [fC].[Region],
            [fC].[TerritoryID],
            [fC].[TerritoryCode],
            [fC].[TerritoryName],
            [fC].[Territory],
            [RPC].[OddWeek1], 
		    [RPC].[OddWeek2], 
		    [RPC].[OddWeek3], 
		    [RPC].[OddWeek4], 
		    [RPC].[OddWeek5], 
		    [RPC].[OddWeek6], 
		    [RPC].[OddWeek7],
		    [RPC].[EvenWeek1], 
		    [RPC].[EvenWeek2], 
		    [RPC].[EvenWeek3], 
		    [RPC].[EvenWeek4], 
		    [RPC].[EvenWeek5], 
		    [RPC].[EvenWeek6], 
		    [RPC].[EvenWeek7],
            @OrderBySalesmanID [OrderBySalesmanID],
            (SELECT CASE WHEN (@OrderBySalesmanID IS NOT NULL) AND (@OrderBySalesmanID = [fC].[SalesmanID]) THEN 0 ELSE 1 END) [SortIndex],
            @FilterByKeywords [FilterByKeywords]
        FROM
            [dbo].[fCustomer]
            (
                @CustomerID,
                @CustomerCode,
                @CustomerName,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                @SiteID,
                @SiteCode,
                @SiteName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,    
                @SiteDistributionTypeID,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                0,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            ) [fC] LEFT OUTER JOIN                       
	        (
	            SELECT 
		                [CustomerID],
                        [SalesmanID],
		                [1_1] [OddWeek1], 
		                [1_2] [OddWeek2], 
		                [1_3] [OddWeek3], 
		                [1_4] [OddWeek4], 
		                [1_5] [OddWeek5], 
		                [1_6] [OddWeek6], 
		                [1_7] [OddWeek7],
		                [2_1] [EvenWeek1], 
		                [2_2] [EvenWeek2], 
		                [2_3] [EvenWeek3], 
		                [2_4] [EvenWeek4], 
		                [2_5] [EvenWeek5], 
		                [2_6] [EvenWeek6], 
		                [2_7] [EvenWeek7]
	                FROM
		                (
		                    SELECT
			                        [RP].[CustomerID],
                                    [C].[SalesmanID],
                                    1 [IsCustomerCall],
			                        CAST([fSL].[Value_Int32] AS nvarchar(3)) + '_' + CAST([fSL2].[Value_Int32] AS nvarchar(3)) [Week_Day]                                    
		                        FROM
			                        [dbo].[RoutePlan] [RP] INNER JOIN
                                    [dbo].[fSalesman]
                                    (
                                        @SalesmanID,
                                        @SalesmanCode,
                                        @SalesmanName,
                                        @WarehouseID,
                                        @WarehouseCode,
                                        @WarehouseName,
                                        @SiteID,
                                        @SiteCode,
                                        @SiteName,
                                        @CompanyID,
                                        @CompanyCode,
                                        @CompanyName,
                                        @AreaID,
                                        @AreaCode,
                                        @AreaName,
                                        @RegionID,
                                        @RegionCode,
                                        @RegionName,
                                        @TerritoryID,
                                        @TerritoryCode,
                                        @TerritoryName,    
                                        @SiteDistributionTypeID,
				                        NULL,
                                        @WarehouseTypeID,
                                        @SalesmanGroupID,
                                        @SalesmanCategoryID,
                                        NULL,
                                        NULL,
                                        @SalesmanStatusID,
                                        NULL
	                                ) [fS] ON ([RP].[SalesmanID] = [fS].[ID]) INNER JOIN
                                    [dbo].[Customer] [C] ON ([RP].[CustomerID] = [C].[ID]) LEFT OUTER JOIN
                                    [dbo].[fSystemLookup]
                                    (
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        'Week',
                                        NULL,
                                        NULL,
                                        NULL
                                    ) [fSL] ON ([RP].[WeekID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
                                    [dbo].[fSystemLookup]
                                    (
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        'Day',
                                        NULL,
                                        NULL,
                                        NULL
                                    ) [fSL2] ON ([RP].[DayID] = [fSL2].[Value_Int32])
		                        WHERE
			                        ((@CustomerID IS NULL) OR ([RP].[CustomerID] = @CustomerID)) AND			                        
			                        ((@CustomerCode IS NULL) OR ([C].[Code] LIKE '%' + @CustomerCode + '%')) AND
                                    ((@CustomerName IS NULL) OR ([C].[Name] LIKE '%' + @CustomerName + '%')) AND
                                    ((@SalesmanID IS NULL) OR ([RP].[SalesmanID] = @SalesmanID)) AND
                                    ((@WeekID IS NULL) OR ([RP].[WeekID] = @WeekID)) AND
                                    ((@DayID IS NULL) OR ([RP].[DayID] = @DayID))			                        
                                GROUP BY
			                        [RP].[CustomerID],
                                    [C].[SalesmanID],                                    
                                    CAST([fSL].[Value_Int32] AS nvarchar(3)) + '_' + CAST([fSL2].[Value_Int32] AS nvarchar(3))
		                ) [Unpivot]
	                    PIVOT
		                (
                            AVG([IsCustomerCall]) FOR [Week_Day] IN ([1_1], [1_2], [1_3], [1_4], [1_5], [1_6], [1_7], [2_1], [2_2], [2_3], [2_4], [2_5], [2_6], [2_7])
		                ) [Pivot]
	        ) [RPC] ON ([fC].[ID] = [RPC].[CustomerID]) LEFT OUTER JOIN
            [dbo].[fSalesman]
            (
                @SalesmanID,
                @SalesmanCode,
                @SalesmanName,
                @WarehouseID,
                @WarehouseCode,
                @WarehouseName,
                @SiteID,
                @SiteCode,
                @SiteName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,    
                @SiteDistributionTypeID,
				NULL,
                @WarehouseTypeID,
                @SalesmanGroupID,
                @SalesmanCategoryID,
                NULL,
                NULL,
                @SalesmanStatusID,
                0
	        ) [fS] ON ([RPC].[SalesmanID] = [fS].[ID])
        WHERE            
            (
                (@FilterByKeywords IS NULL) OR
                ([dbo].[SearchText]([fC].[Customer], @FilterByKeywords) = 1) OR
                ([dbo].[SearchText]([fC].[Address], @FilterByKeywords) = 1)
            )
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vRoutePlanCustomer]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vRoutePlanCustomer];
GO

---- ===================================================================================
---- Author        : System
---- Created date  : 17 Mar 2016 20:37:01
---- Description   : Provide view (model) to retrieve [dbo].[fRoutePlanCustomer] data.
----
---- NOTE: This View is initially generated by system and can be modified following
----       the requirement.
---- ===================================================================================

CREATE VIEW [dbo].[vRoutePlanCustomer]
AS
(
    SELECT
            [CustomerID],
            [SalesmanID],
            [CustomerCode],
            [CustomerName],
            [Customer],
            [CustomerAddress1],
            [CustomerAddress2],
            [CustomerAddress3],
            [CustomerAddress],
            [SalesmanCode],
            [SalesmanName],
            [Salesman],
            [WarehouseID],
            [WarehouseCode],
            [WarehouseName],
            [Warehouse],
            [SiteID],
            [SiteCode],
            [SiteName],
            [Site],
            [CompanyID],
            [CompanyCode],
            [CompanyName],
            [Company],
            [AreaID],
            [AreaCode],
            [AreaName],
            [Area],
            [RegionID],
            [RegionCode],
            [RegionName],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [OddWeek1], 
            [OddWeek2], 
            [OddWeek3], 
            [OddWeek4], 
            [OddWeek5], 
            [OddWeek6], 
            [OddWeek7],
            [EvenWeek1], 
            [EvenWeek2], 
            [EvenWeek3], 
            [EvenWeek4], 
            [EvenWeek5], 
            [EvenWeek6], 
            [EvenWeek7],
            [OrderBySalesmanID],
            [SortIndex],
            [FilterByKeywords]
        FROM
			[dbo].[fRoutePlanCustomer]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
