USE [IDOS];
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fRoutePlanSalesman]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fRoutePlanSalesman];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[RoutePlan] by Salesman data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fRoutePlanSalesman]
(
    @SalesmanID uniqueidentifier,
    @CustomerID uniqueidentifier,    
    @WeekID int,
    @DayID int,
    @SalesmanCode nvarchar(20),
    @SalesmanName nvarchar(50),
    @WarehouseID uniqueidentifier,
    @WarehouseCode nvarchar(10),
    @WarehouseName nvarchar(50),
    @SiteID uniqueidentifier,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),    
    @SiteDistributionTypeID int,
    @WarehouseTypeID int,
    @SalesmanGroupID int,
    @SalesmanCategoryID int,
    @SalesmanStatusID int,
    @CustomerCode nvarchar(20),
    @CustomerName nvarchar(50)
)
RETURNS TABLE 
AS
RETURN 
(
    SELECT
	        [fS].[ID] [SalesmanID],
            [fS].[Code] [SalesmanCode],
            [fS].[Name] [SalesmanName],
            [fS].[Salesman],
            [fS].[WarehouseID],
            [fS].[WarehouseCode],
            [fS].[WarehouseName],
            [fS].[Warehouse],
            [fS].[SiteID],
            [fS].[SiteCode],
            [fS].[SiteName],
            [fS].[Site],
            [fS].[CompanyID],
            [fS].[CompanyCode],
            [fS].[CompanyName],
            [fS].[Company],
            [fS].[AreaID],
            [fS].[AreaCode],
            [fS].[AreaName],
            [fS].[Area],
            [fS].[RegionID],
            [fS].[RegionCode],
            [fS].[RegionName],
            [fS].[Region],
            [fS].[TerritoryID],
            [fS].[TerritoryCode],
            [fS].[TerritoryName],
            [fS].[Territory],
            [RPS].[OddWeek1], 
		    [RPS].[OddWeek2], 
		    [RPS].[OddWeek3], 
		    [RPS].[OddWeek4], 
		    [RPS].[OddWeek5], 
		    [RPS].[OddWeek6], 
		    [RPS].[OddWeek7],
		    [RPS].[EvenWeek1], 
		    [RPS].[EvenWeek2], 
		    [RPS].[EvenWeek3], 
		    [RPS].[EvenWeek4], 
		    [RPS].[EvenWeek5], 
		    [RPS].[EvenWeek6], 
		    [RPS].[EvenWeek7],
            @CustomerID [CustomerID]
        FROM
            [dbo].[fSalesman]
            (
                @SalesmanID,
                @SalesmanCode,
                @SalesmanName,
                @WarehouseID,
                @WarehouseCode,
                @WarehouseName,
                @SiteID,
                @SiteCode,
                @SiteName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,    
                @SiteDistributionTypeID,
				NULL,
                @WarehouseTypeID,
                @SalesmanGroupID,
                @SalesmanCategoryID,
                NULL,
                NULL,
                @SalesmanStatusID,
                0
	        ) [fS] LEFT OUTER JOIN
	        (
	            SELECT 
		                [SalesmanID],
		                [1_1] [OddWeek1], 
		                [1_2] [OddWeek2], 
		                [1_3] [OddWeek3], 
		                [1_4] [OddWeek4], 
		                [1_5] [OddWeek5], 
		                [1_6] [OddWeek6], 
		                [1_7] [OddWeek7],
		                [2_1] [EvenWeek1], 
		                [2_2] [EvenWeek2], 
		                [2_3] [EvenWeek3], 
		                [2_4] [EvenWeek4], 
		                [2_5] [EvenWeek5], 
		                [2_6] [EvenWeek6], 
		                [2_7] [EvenWeek7]
	                FROM
		                (
		                    SELECT
			                        [RP].[SalesmanID],
                                    COUNT([RP].[CustomerID]) [CountCustomerCalls],
			                        CAST([fSL].[Value_Int32] AS nvarchar(3)) + '_' + CAST([fSL2].[Value_Int32] AS nvarchar(3)) [Week_Day]
		                        FROM
			                        [dbo].[RoutePlan] [RP] INNER JOIN
                                    [dbo].[fSalesman]
                                    (
                                        @SalesmanID,
                                        @SalesmanCode,
                                        @SalesmanName,
                                        @WarehouseID,
                                        @WarehouseCode,
                                        @WarehouseName,
                                        @SiteID,
                                        @SiteCode,
                                        @SiteName,
                                        @CompanyID,
                                        @CompanyCode,
                                        @CompanyName,
                                        @AreaID,
                                        @AreaCode,
                                        @AreaName,
                                        @RegionID,
                                        @RegionCode,
                                        @RegionName,
                                        @TerritoryID,
                                        @TerritoryCode,
                                        @TerritoryName,    
                                        @SiteDistributionTypeID,
				                        NULL,
                                        @WarehouseTypeID,
                                        @SalesmanGroupID,
                                        @SalesmanCategoryID,
                                        NULL,
                                        NULL,
                                        @SalesmanStatusID,
                                        NULL
	                                ) [fS] ON ([RP].[SalesmanID] = [fS].[ID]) INNER JOIN
                                    [dbo].[Customer] [C] ON ([RP].[CustomerID] = [C].[ID]) LEFT OUTER JOIN
                                    [dbo].[fSystemLookup]
                                    (
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        'Week',
                                        NULL,
                                        NULL,
                                        NULL
                                    ) [fSL] ON ([RP].[WeekID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
                                    [dbo].[fSystemLookup]
                                    (
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        NULL,
                                        'Day',
                                        NULL,
                                        NULL,
                                        NULL
                                    ) [fSL2] ON ([RP].[DayID] = [fSL2].[Value_Int32])
		                        WHERE
			                        ((@SalesmanID IS NULL) OR ([RP].[SalesmanID] = @SalesmanID)) AND
                                    (
                                        ((@CustomerID IS NULL) AND (@CustomerCode IS NULL) AND (@CustomerName IS NULL)) OR
                                        [RP].[SalesmanID] IN
                                        (
                                            SELECT
                                                    [qRP].[SalesmanID]
                                                FROM
                                                    [dbo].[RoutePlan] [qRP] INNER JOIN
                                                    [dbo].[Customer] [qC] ON ([qRP].[CustomerID] = [qC].[ID])
                                                WHERE
                                                    ((@CustomerID IS NULL) OR ([qRP].[CustomerID] = @CustomerID)) AND
                                                    ((@CustomerCode IS NULL) OR ([qC].[Code] LIKE '%' + @CustomerCode + '%')) AND
                                                    ((@CustomerName IS NULL) OR ([qC].[Name] LIKE '%' + @CustomerName + '%')) AND
                                                    ((@WeekID IS NULL) OR ([RP].[WeekID] = @WeekID)) AND
			                                        ((@DayID IS NULL) OR ([RP].[DayID] = @DayID))
                                        )
                                    ) AND
                                    ((@WeekID IS NULL) OR ([RP].[WeekID] = @WeekID)) AND
			                        ((@DayID IS NULL) OR ([RP].[DayID] = @DayID))			            
		                        GROUP BY
			                        [RP].[SalesmanID],
                                    CAST([fSL].[Value_Int32] AS nvarchar(3)) + '_' + CAST([fSL2].[Value_Int32] AS nvarchar(3))
		                ) [Unpivot]
	                    PIVOT
		                (
                            AVG([CountCustomerCalls]) FOR [Week_Day] IN ([1_1], [1_2], [1_3], [1_4], [1_5], [1_6], [1_7], [2_1], [2_2], [2_3], [2_4], [2_5], [2_6], [2_7])
		                ) [Pivot]
	         ) [RPS] ON ([fS].[ID] = [RPS].[SalesmanID])
        WHERE
            (
                ((@CustomerID IS NULL) AND (@CustomerCode IS NULL) AND (@CustomerName IS NULL)) OR
                (
                    (ISNULL([RPS].[OddWeek1], 0) > 0) OR
		            (ISNULL([RPS].[OddWeek2], 0) > 0) OR 
		            (ISNULL([RPS].[OddWeek3], 0) > 0) OR 
		            (ISNULL([RPS].[OddWeek4], 0) > 0) OR 
		            (ISNULL([RPS].[OddWeek5], 0) > 0) OR 
		            (ISNULL([RPS].[OddWeek6], 0) > 0) OR 
		            (ISNULL([RPS].[OddWeek7], 0) > 0) OR
		            (ISNULL([RPS].[EvenWeek1], 0) > 0) OR 
		            (ISNULL([RPS].[EvenWeek2], 0) > 0) OR 
		            (ISNULL([RPS].[EvenWeek3], 0) > 0) OR 
		            (ISNULL([RPS].[EvenWeek4], 0) > 0) OR 
		            (ISNULL([RPS].[EvenWeek5], 0) > 0) OR 
		            (ISNULL([RPS].[EvenWeek6], 0) > 0) OR 
		            (ISNULL([RPS].[EvenWeek7], 0) > 0)
                )
            )
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vRoutePlanSalesman]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vRoutePlanSalesman];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fRoutePlanSalesman] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vRoutePlanSalesman]
AS
(
    SELECT
            [SalesmanID],
            [SalesmanCode],
            [SalesmanName],
            [Salesman],
            [WarehouseID],
            [WarehouseCode],
            [WarehouseName],
            [Warehouse],
            [SiteID],
            [SiteCode],
            [SiteName],
            [Site],
            [CompanyID],
            [CompanyCode],
            [CompanyName],
            [Company],
            [AreaID],
            [AreaCode],
            [AreaName],
            [Area],
            [RegionID],
            [RegionCode],
            [RegionName],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [OddWeek1], 
		    [OddWeek2], 
		    [OddWeek3], 
		    [OddWeek4], 
		    [OddWeek5], 
		    [OddWeek6], 
		    [OddWeek7],
		    [EvenWeek1], 
		    [EvenWeek2], 
		    [EvenWeek3], 
		    [EvenWeek4], 
		    [EvenWeek5], 
		    [EvenWeek6], 
		    [EvenWeek7],
            [CustomerID]
        FROM
			[dbo].[fRoutePlanSalesman]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
