USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fSalesOrderFOC]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fSalesOrderFOC];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide function to retrieve [dbo].[SalesOrderFOC] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fSalesOrderFOC]
(
    @DocumentID uniqueidentifier,
    @DocumentCode nvarchar(30),
    @TransactionDateFrom datetime,
    @TransactionDateTo datetime,
    @PODocumentID uniqueidentifier,
    @PODocumentCode nvarchar(30),
    @SalesmanID uniqueidentifier,
    @SalesmanCode nvarchar(10),
    @SalesmanName nvarchar(50),    
    @WarehouseID uniqueidentifier,
    @WarehouseCode nvarchar(10),
    @WarehouseName nvarchar(50),
    @SiteID uniqueidentifier,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),    
    @SiteDistributionTypeID int,
    @WarehouseTypeID int,
    @IsSiteLotNumberEntryRequired bit,
    @CustomerID uniqueidentifier,
    @CustomerCode nvarchar(10),
    @CustomerName nvarchar(50),
    @PriceGroupID int,
    @DiscountGroupID int,
    @DiscountGroupCode nvarchar(10),
    @DiscountGroupName nvarchar(50),
    @TermOfPaymentID int,
    @ReferenceNumber nvarchar(30),
    @DODocumentID uniqueidentifier,
    @DODocumentCode nvarchar(30),
    @DOShipmentDateFrom datetime,
    @DOShipmentDateTo datetime,
    @DOReceivedDateFrom datetime,
    @DOReceivedDateTo datetime,
    @DOLastPrintedDateFrom datetime,
    @DOLastPrintedDateTo datetime,
    @InvoiceDocumentID uniqueidentifier,
    @InvoiceDocumentCode nvarchar(30),
    @DocumentStatusID int,
    @DocumentStatusReason nvarchar(200),
    @SFAInvoiceDocumentCode nvarchar(30),
    @PostedDateFrom datetime,
    @PostedDateTo datetime
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [SOFOC].[DocumentID],
            [SOFOC].[DocumentCode],
            [SOFOC].[TransactionDate],
            [SOFOC].[PODocumentID],
            [PO].[DocumentCode] [PODocumentCode],
            [PO].[TransactionDate] [POTransactionDate],
            [SOFOC].[SalesmanID],
            [S].[Code] [SalesmanCode],
            [S].[Name] [SalesmanName],
            [dbo].[fCodeNameFormatter]([S].[Code], [S].[Name]) [Salesman],
            [SOFOC].[WarehouseID],
            [fW].[Code] [WarehouseCode],
            [fW].[Name] [WarehouseName],
            [fW].[Warehouse],
            [fW].[SiteID],
            [fW].[SiteCode],
            [fW].[SiteName],
            [fW].[Site],
            [fW].[CompanyID],
            [fW].[CompanyCode],
            [fW].[CompanyName],
            [fW].[Company],
            [fW].[AreaID],
            [fW].[AreaCode],
            [fW].[AreaName],
            [fW].[Area],
            [fW].[RegionID],
            [fW].[RegionCode],
            [fW].[RegionName],
            [fW].[Region],
            [fW].[TerritoryID],
            [fW].[TerritoryCode],
            [fW].[TerritoryName],
            [fW].[Territory],
            [fW].[SiteDistributionTypeID],
            [fW].[SiteDistributionTypeName],
            [fW].[TypeID] [WarehouseTypeID],
            [fW].[TypeName] [WarehouseTypeName],
            [fW].[IsSiteLotNumberEntryRequired],
            [SOFOC].[CustomerID],
            [C].[Code] [CustomerCode],
            [C].[Name] [CustomerName],
            [dbo].[fCodeNameFormatter]([C].[Code], [C].[Name]) [Customer],
            [SOFOC].[PriceGroupID],
            [fSL].[Name] [PriceGroupName],
            [SOFOC].[DiscountGroupID],
            [DG].[Code] [DiscountGroupCode],
            [DG].[Name] [DiscountGroupName],
            [dbo].[fCodeNameFormatter]([DG].[Code], [DG].[Name]) [DiscountGroup],
            [DG].[Description] [DiscountGroupDescription],
            [SOFOC].[TermOfPaymentID],
            [fSL2].[Name] [TermOfPaymentName],            
            [SOFOC].[ReferenceNumber],
            [SOFOC].[DODocumentID],
            [DO].[DocumentCode] [DODocumentCode],
            [DO].[ShipmentDate] [DOShipmentDate],
            [DO].[ReceivedDate] [DOReceivedDate],
            [DO].[PrintedCount] [DOPrintedCount],
            [DO].[LastPrintedDate] [DOLastPrintedDate],
            [SOFOC].[InvoiceDocumentID],
            [I].[DocumentCode] [InvoiceDocumentCode],
            [SOFOC].[RawTotalGrossPrice],    
            [SOFOC].[RawTotalPrice],
            [SOFOC].[RawTotalDiscountStrata1Amount],
            [SOFOC].[RawTotalDiscountStrata2Amount],
            [SOFOC].[RawTotalDiscountStrata3Amount],
            [SOFOC].[RawTotalDiscountStrata4Amount],
            [SOFOC].[RawTotalDiscountStrata5Amount],
            [SOFOC].[RawTotalAddDiscountStrataAmount],
            [SOFOC].[RawTotalGross],
            [SOFOC].[RawTotalTax],
            [SOFOC].[RawTotal],
            [SOFOC].[TotalGrossPrice],    
            [SOFOC].[TotalPrice],
            [SOFOC].[TotalDiscountStrata1Amount],
            [SOFOC].[TotalDiscountStrata2Amount],
            [SOFOC].[TotalDiscountStrata3Amount],
            [SOFOC].[TotalDiscountStrata4Amount],
            [SOFOC].[TotalDiscountStrata5Amount],
            [SOFOC].[TotalAddDiscountStrataAmount],
            [SOFOC].[TotalGross],
            [SOFOC].[TotalTax],
            [SOFOC].[Total],
            [SOFOC].[TotalWeight],
            [SOFOC].[TotalDimension],
            [SOFOC].[AddDiscountStrataReason],
            [SOFOC].[DocumentStatusID],
            [fSL3].[Name] [DocumentStatusName],
            [SOFOC].[DocumentStatusReason],
            [SOFOC].[SFAInvoiceDocumentCode],
            [SOFOC].[PrintCount],
            [SOFOC].[PostedDate],
            [SOFOC].[CreatedDate],
            [SOFOC].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [SOFOC].[ModifiedDate],
            [SOFOC].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName]
        FROM
			[dbo].[SalesOrderFOC] [SOFOC] LEFT OUTER JOIN
            [dbo].[PurchaseOrder] [PO] ON ([SOFOC].[PODocumentID] = [PO].[DocumentID]) INNER JOIN
            [dbo].[Salesman] [S] ON ([SOFOC].[SalesmanID] = [S].[ID]) INNER JOIN
            [dbo].[fWarehouse]
            (
                @WarehouseID,
                @WarehouseCode,
                @WarehouseName,
                @SiteID,
                @SiteCode,
                @SiteName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @SiteDistributionTypeID,
                @WarehouseTypeID,
                @IsSiteLotNumberEntryRequired,
                NULL,
                NULL,
                NULL
            ) [fW] ON ([SOFOC].[WarehouseID] = [fW].[ID]) INNER JOIN
            [dbo].[Customer] [C] ON ([SOFOC].[CustomerID] = [C].[ID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'ProductPriceGroup',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([SOFOC].[PriceGroupID] = [fSL].[Value_Int32]) INNER JOIN
            [dbo].[DiscountGroup] [DG] ON ([SOFOC].[DiscountGroupID] = [DG].[ID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'CustomerTermOfPayment',
                NULL,
                NULL,
                NULL
            ) [fSL2] ON ([SOFOC].[TermOfPaymentID] = [fSL2].[Value_Int32]) INNER JOIN
            [dbo].[DeliveryOrder] [DO] ON ([SOFOC].[DODocumentID] = [DO].[DocumentID]) LEFT OUTER JOIN
            [dbo].[Invoice] [I] ON ([SOFOC].[InvoiceDocumentID] = [I].[DocumentID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'DocumentStatus',
                NULL,
                NULL,
                NULL
            ) [fSL3] ON ([SOFOC].[DocumentStatusID] = [fSL3].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([SOFOC].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([SOFOC].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@DocumentID IS NULL) OR ([SOFOC].[DocumentID] = @DocumentID)) AND
            ((@DocumentCode IS NULL) OR ([SOFOC].[DocumentCode] LIKE '%' + @DocumentCode + '%')) AND
            ((@TransactionDateFrom IS NULL) OR ([SOFOC].[TransactionDate] >= [dbo].[ConvertToFirstTimeOfDay](@TransactionDateFrom))) AND
            ((@TransactionDateTo IS NULL) OR ([SOFOC].[TransactionDate] <= [dbo].[ConvertToLastTimeOfDay](@TransactionDateTo))) AND
            ((@PODocumentID IS NULL) OR ([SOFOC].[PODocumentID] = @PODocumentID)) AND
            ((@PODocumentCode IS NULL) OR ([PO].[DocumentCode] LIKE '%' + @PODocumentCode + '%')) AND
            ((@SalesmanID IS NULL) OR ([SOFOC].[SalesmanID] = @SalesmanID)) AND
            ((@SalesmanCode IS NULL) OR ([S].[Code] LIKE '%' + @SalesmanCode + '%')) AND
            ((@SalesmanName IS NULL) OR ([S].[Name] LIKE '%' + @SalesmanName + '%')) AND
            ((@WarehouseID IS NULL) OR ([SOFOC].[WarehouseID] = @WarehouseID)) AND
            ((@CustomerID IS NULL) OR ([SOFOC].[CustomerID] = @CustomerID)) AND
            ((@CustomerCode IS NULL) OR ([C].[Code] LIKE '%' + @CustomerCode + '%')) AND
            ((@CustomerName IS NULL) OR ([C].[Name] LIKE '%' + @CustomerName + '%')) AND
            ((@PriceGroupID IS NULL) OR ([SOFOC].[PriceGroupID] = @PriceGroupID)) AND
            ((@DiscountGroupID IS NULL) OR ([SOFOC].[DiscountGroupID] = @DiscountGroupID)) AND
            ((@DiscountGroupCode IS NULL) OR ([DG].[Code] LIKE '%' + @DiscountGroupCode + '%')) AND
            ((@DiscountGroupName IS NULL) OR ([DG].[Name] LIKE '%' + @DiscountGroupName + '%')) AND
            ((@TermOfPaymentID IS NULL) OR ([SOFOC].[TermOfPaymentID] = @TermOfPaymentID)) AND
            ((@ReferenceNumber IS NULL) OR ([SOFOC].[ReferenceNumber] LIKE '%' + @ReferenceNumber + '%')) AND
            ((@DODocumentID IS NULL) OR ([SOFOC].[DODocumentID] = @DODocumentID)) AND
            ((@DODocumentCode IS NULL) OR ([DO].[DocumentCode] LIKE '%' + @DODocumentCode + '%')) AND
            ((@InvoiceDocumentID IS NULL) OR ([SOFOC].[InvoiceDocumentID] = @InvoiceDocumentID)) AND
            ((@DocumentStatusID IS NULL) OR ([SOFOC].[DocumentStatusID] = @DocumentStatusID)) AND
            ((@DocumentStatusReason IS NULL) OR ([SOFOC].[DocumentStatusReason] LIKE '%' + @DocumentStatusReason + '%')) AND
            ((@SFAInvoiceDocumentCode IS NULL) OR ([SOFOC].[SFAInvoiceDocumentCode] LIKE '%' + @SFAInvoiceDocumentCode + '%')) AND
            ((@PostedDateFrom IS NULL) OR ([dbo].[ValidateMaxDate]([SOFOC].[PostedDate]) >= [dbo].[ValidateMinDate](@PostedDateFrom))) AND
            ((@PostedDateTo IS NULL) OR ([dbo].[ValidateMinDate]([SOFOC].[PostedDate]) <= [dbo].[ValidateMaxDate](@PostedDateTo)))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vSalesOrderFOC]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vSalesOrderFOC];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide view (model) to retrieve [dbo].[fSalesOrderFOC] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vSalesOrderFOC]
AS
(
    SELECT
            [DocumentID],
            [DocumentCode],
            [TransactionDate],
            [PODocumentID],
            [PODocumentCode],
            [POTransactionDate],
            [SalesmanID],
            [SalesmanCode],
            [SalesmanName],
            [Salesman],
            [WarehouseID],
            [WarehouseCode],
            [WarehouseName],
            [Warehouse],
            [SiteID],
            [SiteCode],
            [SiteName],
            [Site],
            [CompanyID],
            [CompanyCode],
            [CompanyName],
            [Company],
            [AreaID],
            [AreaCode],
            [AreaName],
            [Area],
            [RegionID],
            [RegionCode],
            [RegionName],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [SiteDistributionTypeID],
            [SiteDistributionTypeName],
            [WarehouseTypeID],
            [WarehouseTypeName],
            [IsSiteLotNumberEntryRequired],
            [CustomerID],
            [CustomerCode],
            [CustomerName],
            [Customer],
            [PriceGroupID],
            [PriceGroupName],
            [DiscountGroupID],
            [DiscountGroupCode],
            [DiscountGroupName],
            [DiscountGroup],
            [DiscountGroupDescription],
            [TermOfPaymentID],
            [TermOfPaymentName],            
            [ReferenceNumber],
            [DODocumentID],
            [DODocumentCode],
            [DOShipmentDate],
            [DOReceivedDate],
            [DOPrintedCount],
            [DOLastPrintedDate],
            [InvoiceDocumentID],
            [InvoiceDocumentCode],
            [RawTotalGrossPrice],    
            [RawTotalPrice],
            [RawTotalDiscountStrata1Amount],
            [RawTotalDiscountStrata2Amount],
            [RawTotalDiscountStrata3Amount],
            [RawTotalDiscountStrata4Amount],
            [RawTotalDiscountStrata5Amount],
            [RawTotalAddDiscountStrataAmount],
            [RawTotalGross],
            [RawTotalTax],
            [RawTotal],
            [TotalGrossPrice],    
            [TotalPrice],
            [TotalDiscountStrata1Amount],
            [TotalDiscountStrata2Amount],
            [TotalDiscountStrata3Amount],
            [TotalDiscountStrata4Amount],
            [TotalDiscountStrata5Amount],
            [TotalAddDiscountStrataAmount],
            [TotalGross],
            [TotalTax],
            [Total],
            [TotalWeight],
            [TotalDimension],
            [AddDiscountStrataReason],
            [DocumentStatusID],
            [DocumentStatusName],
            [DocumentStatusReason],
            [SFAInvoiceDocumentCode],
            [PrintCount],
            [PostedDate],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName]
        FROM
			[dbo].[fSalesOrderFOC]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL                
            )
);
GO
