USE [IDOS];
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fSalesBySiteByBrandReport]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fSalesBySiteByBrandReport];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[RoutePlan] by Salesman data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fSalesBySiteByBrandReport]
(
    @ReportDateFrom date,
    @ReportDateTo date,
    @CategoryAreaCode nvarchar(10),
    @TerritoryID int,
    @RegionID int,
    @AreaID int,
    @CompanyID int,
    @SiteID uniqueidentifier,
    @SiteDistributionTypeID int,
    @ProductBrandID int,
    @ProductID int
)
RETURNS TABLE 
AS
RETURN 
(
    SELECT
            ISNULL([C].[SiteID], ISNULL([LM].[SiteID], [LY].[SiteID])) [SiteID],
            ISNULL([C].[ProductBrandID], ISNULL([LM].[ProductBrandID], [LY].[ProductBrandID])) [ProductBrandID],
            ISNULL([C].[Site], ISNULL([LM].[Site], [LY].[Site])) [Site],
            ISNULL([C].[ProductBrand], ISNULL([LM].[ProductBrand], [LY].[ProductBrand])) [ProductBrand],
            CAST(ISNULL([C].[TargetSalesOrderQty], 0) AS float) [TargetSalesOrderQty],
            CAST(ISNULL([C].[TotalSalesOrderQty], 0) AS float) [TotalSalesOrderQty],
            CAST(ISNULL([C].[TotalSalesOrderReturnQty], 0) AS float) [TotalSalesOrderReturnQty],
            CAST(ISNULL([C].[ActualSalesOrderQty], 0) AS float) [ActualSalesOrderQty],
            CAST(ISNULL(CAST(ISNULL([C].[ActualSalesOrderQty], 0) AS float) / ABS(NULLIF([C].[TargetSalesOrderQty], 0)) * 100, 0) AS float) [AchActualSalesOrderQty],
            CAST(ISNULL([LM].[TotalSalesOrderQty], 0) AS float) [LMTotalSalesOrderQty],
            CAST(ISNULL([LM].[TotalSalesOrderReturnQty], 0) AS float) [LMTotalSalesOrderReturnQty],
            CAST(ISNULL([LM].[ActualSalesOrderQty], 0) AS float) [LMActualSalesOrderQty],
            CAST(ISNULL([LY].[TotalSalesOrderQty], 0) AS float) [LYTotalSalesOrderQty],
            CAST(ISNULL([LY].[TotalSalesOrderReturnQty], 0) AS float) [LYTotalSalesOrderReturnQty],
            CAST(ISNULL([LY].[ActualSalesOrderQty], 0) AS float) [LYActualSalesOrderQty],
            CAST(ISNULL(CAST((ISNULL([C].[ActualSalesOrderQty], 0) - ISNULL([LM].[ActualSalesOrderQty], 0)) AS float) / ABS(NULLIF([LM].[ActualSalesOrderQty], 0)) * 100, 0) AS float) [GrowthLMActualSalesOrderQty],
            CAST(ISNULL(CAST((ISNULL([C].[ActualSalesOrderQty], 0) - ISNULL([LY].[ActualSalesOrderQty], 0)) AS float) / ABS(NULLIF([LY].[ActualSalesOrderQty], 0)) * 100, 0) AS float) [GrowthLYActualSalesOrderQty],
            CAST(ISNULL([C].[ActualSalesOrderQty], 0) - ISNULL([C].[TargetSalesOrderQty], 0) AS float) [GapTargetVsActualSalesOrderQty]
        FROM
        (
            SELECT
                    [SiteID],
                    [ProductBrandID],
                    MIN([Site]) [Site],
                    MIN(ProductBrand) [ProductBrand],                    
                    SUM([TargetSalesOrderQty] * [ProductEquivalent]) [TargetSalesOrderQty],
                    SUM([TotalSalesOrderQty] * [ProductEquivalent]) [TotalSalesOrderQty],
                    SUM([TotalSalesOrderReturnQty] * [ProductEquivalent]) [TotalSalesOrderReturnQty],
                    SUM([ActualSalesOrderQty] * [ProductEquivalent]) [ActualSalesOrderQty]
                FROM
                (
                    SELECT
                            [SiteID],
                            [ProductBrandID],
                            MIN([Site]) [Site],
                            MIN(ProductBrand) [ProductBrand],
                            MIN([ProductEquivalent]) [ProductEquivalent],
                            MIN([TargetSalesOrderQty]) [TargetSalesOrderQty],
                            SUM([TotalSalesOrderQty]) [TotalSalesOrderQty],
                            SUM([TotalSalesOrderReturnQty]) [TotalSalesOrderReturnQty],
                            SUM([ActualSalesOrderQty]) [ActualSalesOrderQty]
                        FROM
                            [dbo].[ReportSellOut]
                        WHERE
                            ((@ReportDateFrom IS NULL) OR ([ReportDate] >= [dbo].[ConvertToFirstTimeOfDay](@ReportDateFrom))) AND
                            ((@ReportDateTo IS NULL) OR ([ReportDate] <= [dbo].[ConvertToLastTimeOfDay](@ReportDateTo))) AND
                            ((@ProductID IS NULL) OR ([ProductID] = @ProductID)) AND
                            ((@TerritoryID IS NULL) OR ([TerritoryID] = @TerritoryID)) AND
                            ((@RegionID IS NULL) OR ([RegionID] = @RegionID)) AND
                            ((@AreaID IS NULL) OR ([AreaID] = @AreaID)) AND
                            ((@CompanyID IS NULL) OR ([CompanyID] = @CompanyID)) AND
                            ((@SiteID IS NULL) OR ([SiteID] = @SiteID)) AND
                            ((@SiteDistributionTypeID IS NULL) OR ([SiteDistributionTypeID] = @SiteDistributionTypeID)) AND                    
                            ((@ProductBrandID IS NULL) OR ([ProductBrandID] = @ProductBrandID))
                        GROUP BY
                            [SiteID],
                            [ProductBrandID],
                            [ProductGroup]
                ) [vC]
                GROUP BY
                    [SiteID],
                    [ProductBrandID]
        ) [C] FULL OUTER JOIN
        (
            SELECT
                    [SiteID],
                    [ProductBrandID],
                    MIN([Site]) [Site],
                    MIN(ProductBrand) [ProductBrand],                    
                    SUM([TargetSalesOrderQty] * [ProductEquivalent]) [TargetSalesOrderQty],
                    SUM([TotalSalesOrderQty] * [ProductEquivalent]) [TotalSalesOrderQty],
                    SUM([TotalSalesOrderReturnQty] * [ProductEquivalent]) [TotalSalesOrderReturnQty],
                    SUM([ActualSalesOrderQty] * [ProductEquivalent]) [ActualSalesOrderQty]
                FROM
                (
                    SELECT
                            [SiteID],
                            [ProductBrandID],
                            MIN([Site]) [Site],
                            MIN(ProductBrand) [ProductBrand],
                            MIN([ProductEquivalent]) [ProductEquivalent],
                            MIN([TargetSalesOrderQty]) [TargetSalesOrderQty],
                            SUM([TotalSalesOrderQty]) [TotalSalesOrderQty],
                            SUM([TotalSalesOrderReturnQty]) [TotalSalesOrderReturnQty],
                            SUM([ActualSalesOrderQty]) [ActualSalesOrderQty]
                        FROM
                            [dbo].[ReportSellOut]
                        WHERE
                            (
                                (
                                    (@ReportDateFrom IS NOT NULL) AND (@ReportDateTo IS NOT NULL) AND
                                    [dbo].[ConvertToFirstTimeOfDay](@ReportDateFrom) = [dbo].[ConvertToFirstDayOfMonth](@ReportDateFrom) AND
                                    [dbo].[ConvertToLastTimeOfDay](@ReportDateTo) = [dbo].[ConvertToLastDayOfMonth](@ReportDateTo) AND                        
                                    [ReportDate] >= [dbo].[ConvertToFirstDayOfMonth](DATEADD(m, -1, [dbo].[ConvertToFirstTimeOfDay](@ReportDateFrom))) AND
                                    [ReportDate] <= [dbo].[ConvertToLastDayOfMonth](DATEADD(m, -1, [dbo].[ConvertToFirstTimeOfDay](@ReportDateTo)))
                                )                        
                                OR
                                (
                                    (@ReportDateFrom IS NOT NULL) AND ([ReportDate] >= DATEADD(m, -1, [dbo].[ConvertToFirstTimeOfDay](@ReportDateFrom))) AND
                                    (@ReportDateTo IS NOT NULL) AND ([ReportDate] <= DATEADD(m, -1, [dbo].[ConvertToLastTimeOfDay](@ReportDateTo)))
                                )
                            ) AND
                            ((@ProductID IS NULL) OR ([ProductID] = @ProductID)) AND
                            ((@TerritoryID IS NULL) OR ([TerritoryID] = @TerritoryID)) AND
                            ((@RegionID IS NULL) OR ([RegionID] = @RegionID)) AND
                            ((@AreaID IS NULL) OR ([AreaID] = @AreaID)) AND
                            ((@CompanyID IS NULL) OR ([CompanyID] = @CompanyID)) AND
                            ((@SiteID IS NULL) OR ([SiteID] = @SiteID)) AND
                            ((@SiteDistributionTypeID IS NULL) OR ([SiteDistributionTypeID] = @SiteDistributionTypeID)) AND                    
                            ((@ProductBrandID IS NULL) OR ([ProductBrandID] = @ProductBrandID))
                        GROUP BY
                            [SiteID],
                            [ProductBrandID],
                            [ProductGroup]
                ) [vLM]
                GROUP BY
                    [SiteID],
                    [ProductBrandID]
        ) [LM] ON
        (
            [C].[SiteID] = [LM].[SiteID] AND
            [C].[ProductBrandID] = [LM].[ProductBrandID]
        ) FULL OUTER JOIN
        (
            SELECT
                    [SiteID],
                    [ProductBrandID],
                    MIN([Site]) [Site],
                    MIN(ProductBrand) [ProductBrand],                    
                    SUM([TargetSalesOrderQty] * [ProductEquivalent]) [TargetSalesOrderQty],
                    SUM([TotalSalesOrderQty] * [ProductEquivalent]) [TotalSalesOrderQty],
                    SUM([TotalSalesOrderReturnQty] * [ProductEquivalent]) [TotalSalesOrderReturnQty],
                    SUM([ActualSalesOrderQty] * [ProductEquivalent]) [ActualSalesOrderQty]
                FROM
                (
                    SELECT
                            [SiteID],
                            [ProductBrandID],
                            MIN([Site]) [Site],
                            MIN(ProductBrand) [ProductBrand],
                            MIN([ProductEquivalent]) [ProductEquivalent],
                            MIN([TargetSalesOrderQty]) [TargetSalesOrderQty],
                            SUM([TotalSalesOrderQty]) [TotalSalesOrderQty],
                            SUM([TotalSalesOrderReturnQty]) [TotalSalesOrderReturnQty],
                            SUM([ActualSalesOrderQty]) [ActualSalesOrderQty]
                        FROM
                            [dbo].[ReportSellOut]
                        WHERE
                            ((@ReportDateFrom IS NULL) OR ([ReportDate] >= DATEADD(yyyy, -1, [dbo].[ConvertToFirstTimeOfDay](@ReportDateFrom)))) AND
                            ((@ReportDateTo IS NULL) OR ([ReportDate] <= DATEADD(yyyy, -1, [dbo].[ConvertToLastTimeOfDay](@ReportDateTo)))) AND
                            ((@ProductID IS NULL) OR ([ProductID] = @ProductID)) AND
                            ((@TerritoryID IS NULL) OR ([TerritoryID] = @TerritoryID)) AND
                            ((@RegionID IS NULL) OR ([RegionID] = @RegionID)) AND
                            ((@AreaID IS NULL) OR ([AreaID] = @AreaID)) AND
                            ((@CompanyID IS NULL) OR ([CompanyID] = @CompanyID)) AND
                            ((@SiteID IS NULL) OR ([SiteID] = @SiteID)) AND
                            ((@SiteDistributionTypeID IS NULL) OR ([SiteDistributionTypeID] = @SiteDistributionTypeID)) AND                    
                            ((@ProductBrandID IS NULL) OR ([ProductBrandID] = @ProductBrandID))
                        GROUP BY
                            [SiteID],
                            [ProductBrandID],
                            [ProductGroup]
                ) [vLY]
                GROUP BY
                    [SiteID],
                    [ProductBrandID]
        ) [LY] ON
        (
            [C].[SiteID] = [LY].[SiteID] AND
            [C].[ProductBrandID] = [LY].[ProductBrandID]
        )
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vSalesBySiteByBrandReport]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vSalesBySiteByBrandReport];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fSalesBySiteByBrandReport] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vSalesBySiteByBrandReport]
AS
(
    SELECT
            [SiteID],
            [ProductBrandID],
            [Site],
            [ProductBrand],
            [TargetSalesOrderQty],      
            [TotalSalesOrderQty],
            [TotalSalesOrderReturnQty],
            [ActualSalesOrderQty],
            [AchActualSalesOrderQty],
            [LMTotalSalesOrderQty],
            [LMTotalSalesOrderReturnQty],
            [LMActualSalesOrderQty],
            [LYTotalSalesOrderQty],
            [LYTotalSalesOrderReturnQty],
            [LYActualSalesOrderQty],
            [GrowthLMActualSalesOrderQty],
            [GrowthLYActualSalesOrderQty],
            [GapTargetVsActualSalesOrderQty]
        FROM
			[dbo].[fSalesBySiteByBrandReport]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
