USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fSalesOrderSwap]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fSalesOrderSwap];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide function to retrieve [dbo].[SalesOrderSwap] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fSalesOrderSwap]
(
    @DocumentID uniqueidentifier,
    @DocumentCode nvarchar(30),
    @TransactionDateFrom datetime,
    @TransactionDateTo datetime,
    @SalesmanID uniqueidentifier,
    @SalesmanCode nvarchar(10),
    @SalesmanName nvarchar(50),    
    @WarehouseID uniqueidentifier,
    @WarehouseCode nvarchar(10),
    @WarehouseName nvarchar(50),
    @SiteID uniqueidentifier,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),    
    @SiteDistributionTypeID int,
    @WarehouseTypeID int,
    @IsSiteLotNumberEntryRequired bit,
    @CustomerID uniqueidentifier,
    @CustomerCode nvarchar(10),
    @CustomerName nvarchar(50),
    @ReferenceNumber nvarchar(30),
    @DODocumentID uniqueidentifier,
    @DODocumentCode nvarchar(30),
    @DOShipmentDateFrom datetime,
    @DOShipmentDateTo datetime,
    @DOReceivedDateFrom datetime,
    @DOReceivedDateTo datetime,
    @DOLastPrintedDateFrom datetime,
    @DOLastPrintedDateTo datetime,
    @DocumentStatusID int,
    @DocumentStatusReason nvarchar(200),
    @SFAInvoiceDocumentCode nvarchar(30),
    @PostedDateFrom datetime,
    @PostedDateTo datetime
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [SOS].[DocumentID],
            [SOS].[DocumentCode],
            [SOS].[TransactionDate],
            [SOS].[SalesmanID],
            [S].[Code] [SalesmanCode],
            [S].[Name] [SalesmanName],
            [dbo].[fCodeNameFormatter]([S].[Code], [S].[Name]) [Salesman],
            [SOS].[WarehouseID],
            [fW].[Code] [WarehouseCode],
            [fW].[Name] [WarehouseName],
            [fW].[Warehouse],
            [fW].[SiteID],
            [fW].[SiteCode],
            [fW].[SiteName],
            [fW].[Site],
            [fW].[CompanyID],
            [fW].[CompanyCode],
            [fW].[CompanyName],
            [fW].[Company],
            [fW].[AreaID],
            [fW].[AreaCode],
            [fW].[AreaName],
            [fW].[Area],
            [fW].[RegionID],
            [fW].[RegionCode],
            [fW].[RegionName],
            [fW].[Region],
            [fW].[TerritoryID],
            [fW].[TerritoryCode],
            [fW].[TerritoryName],
            [fW].[Territory],
            [fW].[SiteDistributionTypeID],
            [fW].[SiteDistributionTypeName],
            [fW].[TypeID] [WarehouseTypeID],
            [fW].[TypeName] [WarehouseTypeName],
            [fW].[IsSiteLotNumberEntryRequired],
            [SOS].[CustomerID],
            [C].[Code] [CustomerCode],
            [C].[Name] [CustomerName],
            [dbo].[fCodeNameFormatter]([C].[Code], [C].[Name]) [Customer],
            [SOS].[ReferenceNumber],
            [SOS].[AttachmentFile],            
            [SOS].[DODocumentID],
            [DO].[DocumentCode] [DODocumentCode],
            [DO].[ShipmentDate] [DOShipmentDate],
            [DO].[ReceivedDate] [DOReceivedDate],
            [DO].[PrintedCount] [DOPrintedCount],
            [DO].[LastPrintedDate] [DOLastPrintedDate],
            [SOS].[TotalWeight],
            [SOS].[TotalDimension],
            [SOS].[DocumentStatusID],
            [fSL].[Name] [DocumentStatusName],
            [SOS].[DocumentStatusReason],
            [SOS].[SFAInvoiceDocumentCode],
            [SOS].[PrintCount],
            [SOS].[PostedDate],
            [SOS].[CreatedDate],
            [SOS].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [SOS].[ModifiedDate],
            [SOS].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName]
        FROM
			[dbo].[SalesOrderSwap] [SOS] INNER JOIN
            [dbo].[Salesman] [S] ON ([SOS].[SalesmanID] = [S].[ID]) INNER JOIN
            [dbo].[fWarehouse]
            (
                @WarehouseID,
                @WarehouseCode,
                @WarehouseName,
                @SiteID,
                @SiteCode,
                @SiteName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @SiteDistributionTypeID,
                @WarehouseTypeID,
                @IsSiteLotNumberEntryRequired,
                NULL,
                NULL,
                NULL
            ) [fW] ON ([SOS].[WarehouseID] = [fW].[ID]) INNER JOIN
            [dbo].[Customer] [C] ON ([SOS].[CustomerID] = [C].[ID]) INNER JOIN
            [dbo].[DeliveryOrder] [DO] ON ([SOS].[DODocumentID] = [DO].[DocumentID]) LEFT OUTER JOIN            
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'DocumentStatus',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([SOS].[DocumentStatusID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([SOS].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([SOS].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@DocumentID IS NULL) OR ([SOS].[DocumentID] = @DocumentID)) AND
            ((@DocumentCode IS NULL) OR ([SOS].[DocumentCode] LIKE '%' + @DocumentCode + '%')) AND
            ((@TransactionDateFrom IS NULL) OR ([SOS].[TransactionDate] >= [dbo].[ConvertToFirstTimeOfDay](@TransactionDateFrom))) AND
            ((@TransactionDateTo IS NULL) OR ([SOS].[TransactionDate] <= [dbo].[ConvertToLastTimeOfDay](@TransactionDateTo))) AND
            ((@SalesmanID IS NULL) OR ([SOS].[SalesmanID] = @SalesmanID)) AND
            ((@SalesmanCode IS NULL) OR ([S].[Code] LIKE '%' + @SalesmanCode + '%')) AND
            ((@SalesmanName IS NULL) OR ([S].[Name] LIKE '%' + @SalesmanName + '%')) AND            
            ((@WarehouseID IS NULL) OR ([SOS].[WarehouseID] = @WarehouseID)) AND
            ((@CustomerID IS NULL) OR ([SOS].[CustomerID] = @CustomerID)) AND
            ((@CustomerCode IS NULL) OR ([C].[Code] LIKE '%' + @CustomerCode + '%')) AND
            ((@CustomerName IS NULL) OR ([C].[Name] LIKE '%' + @CustomerName + '%')) AND
            ((@ReferenceNumber IS NULL) OR ([SOS].[ReferenceNumber] LIKE '%' + @ReferenceNumber + '%')) AND
            ((@DODocumentID IS NULL) OR ([SOS].[DODocumentID] = @DODocumentID)) AND
            ((@DODocumentCode IS NULL) OR ([DO].[DocumentCode] LIKE '%' + @DODocumentCode + '%')) AND
            ((@DocumentStatusID IS NULL) OR ([SOS].[DocumentStatusID] = @DocumentStatusID)) AND
            ((@DocumentStatusReason IS NULL) OR ([SOS].[DocumentStatusReason] LIKE '%' + @DocumentStatusReason + '%')) AND
            ((@SFAInvoiceDocumentCode IS NULL) OR ([SOS].[SFAInvoiceDocumentCode] LIKE '%' + @SFAInvoiceDocumentCode + '%')) AND
            ((@PostedDateFrom IS NULL) OR ([dbo].[ValidateMaxDate]([SOS].[PostedDate]) >= [dbo].[ValidateMinDate](@PostedDateFrom))) AND
            ((@PostedDateTo IS NULL) OR ([dbo].[ValidateMinDate]([SOS].[PostedDate]) <= [dbo].[ValidateMaxDate](@PostedDateTo)))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vSalesOrderSwap]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vSalesOrderSwap];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide view (model) to retrieve [dbo].[fSalesOrderSwap] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vSalesOrderSwap]
AS
(
    SELECT
            [DocumentID],
            [DocumentCode],
            [TransactionDate],
            [SalesmanID],
            [SalesmanCode],
            [SalesmanName],
            [Salesman],
            [WarehouseID],
            [WarehouseCode],
            [WarehouseName],
            [Warehouse],
            [SiteID],
            [SiteCode],
            [SiteName],
            [Site],
            [CompanyID],
            [CompanyCode],
            [CompanyName],
            [Company],
            [AreaID],
            [AreaCode],
            [AreaName],
            [Area],
            [RegionID],
            [RegionCode],
            [RegionName],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [SiteDistributionTypeID],
            [SiteDistributionTypeName],
            [WarehouseTypeID],
            [WarehouseTypeName],
            [IsSiteLotNumberEntryRequired],
            [CustomerID],
            [CustomerCode],
            [CustomerName],
            [Customer],
            [ReferenceNumber],
            [AttachmentFile],
            [DODocumentID],
            [DODocumentCode],
            [DOShipmentDate],
            [DOReceivedDate],
            [DOPrintedCount],
            [DOLastPrintedDate],
            [TotalWeight],
            [TotalDimension],
            [DocumentStatusID],
            [DocumentStatusName],
            [DocumentStatusReason],
            [SFAInvoiceDocumentCode],
            [PrintCount],
            [PostedDate],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName]
        FROM
			[dbo].[fSalesOrderSwap]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL                
            )
);
GO
