USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fSalesman]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fSalesman];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[Salesman] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fSalesman]
(
    @ID uniqueidentifier,
    @Code nvarchar(20),
    @Name nvarchar(50),
    @WarehouseID uniqueidentifier,
    @WarehouseCode nvarchar(10),
    @WarehouseName nvarchar(50),
    @SiteID uniqueidentifier,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),    
    @SiteDistributionTypeID int,
    @IsSiteLotNumberEntryRequired bit,
    @WarehouseTypeID int,
    @GroupID int,
    @CategoryID int,
    @Phone nvarchar(20),
    @SFA nvarchar(50),
    @StatusID int,
    @IsDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [S].[ID],
            [S].[Code],
            [S].[Name],
            [dbo].[fCodeNameFormatter]([S].[Code], [S].[Name]) [Salesman],
            [S].[WarehouseID],
            [fW].[Code] [WarehouseCode],
            [fW].[Name] [WarehouseName],
            [fW].[Warehouse],
            [fW].[SiteID],
            [fW].[SiteCode],
            [fW].[SiteName],
            [fW].[Site],
            [fW].[CompanyID],
            [fW].[CompanyCode],
            [fW].[CompanyName],
            [fW].[Company],
            [fW].[AreaID],
            [fW].[AreaCode],
            [fW].[AreaName],
            [fW].[Area],
            [fW].[RegionID],
            [fW].[RegionCode],
            [fW].[RegionName],
            [fW].[Region],
            [fW].[TerritoryID],
            [fW].[TerritoryCode],
            [fW].[TerritoryName],
            [fW].[Territory],
            [fW].[SiteDistributionTypeID],
            [fW].[SiteDistributionTypeName],
            [fW].[IsSiteLotNumberEntryRequired],
            [fW].[TypeID] [WarehouseTypeID],
            [fW].[TypeName] [WarehouseTypeName],
            [S].[GroupID],
            [fSL].[Name] [GroupName],
            [S].[CategoryID],
            [fSL2].[Name] [CategoryName],
            [S].[Phone],
            [S].[SFAFlag],
            [S].[SFA],
            [S].[StatusID],
            [fSL3].[Name] [StatusName],
            [S].[CreatedDate],
            [S].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [S].[ModifiedDate],
            [S].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [S].[IsDeleted]
        FROM
			[dbo].[Salesman] [S] INNER JOIN
            [dbo].[fWarehouse]
            (
                @WarehouseID,
                @WarehouseCode,
                @WarehouseName,
                @SiteID,
                @SiteCode,
                @SiteName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @SiteDistributionTypeID,
                @IsSiteLotNumberEntryRequired,
                @WarehouseTypeID,
                NULL,
                NULL,
                NULL
            ) [fW] ON ([S].[WarehouseID] = [fW].[ID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'SalesmanGroup',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([S].[GroupID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'SalesmanCategory',
                NULL,
                NULL,
                NULL
            ) [fSL2] ON ([S].[CategoryID] = [fSL2].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'SalesmanStatus',
                NULL,
                NULL,
                NULL
            ) [fSL3] ON ([S].[StatusID] = [fSL3].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([S].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([S].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR (@ID = [S].[ID])) AND
            ((@Code IS NULL) OR ([S].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([S].[Name] LIKE '%' + @Name + '%')) AND
            ((@GroupID IS NULL) OR ([S].[GroupID] = @GroupID)) AND
            ((@CategoryID IS NULL) OR ([S].[CategoryID] = @CategoryID)) AND
            ((@Phone IS NULL) OR ([S].[Phone] LIKE '%' + @Phone + '%')) AND
            ((@SFA IS NULL) OR ([S].[SFA] LIKE '%' + @SFA + '%')) AND
            ((@StatusID IS NULL) OR ([S].[StatusID] = @StatusID)) AND
            ((@IsDeleted IS NULL) OR ([S].[IsDeleted] = @IsDeleted))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vSalesman]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vSalesman];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fSalesman] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vSalesman]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [Salesman],
            [WarehouseID],
            [WarehouseCode],
            [WarehouseName],
            [Warehouse],
            [SiteID],
            [SiteCode],
            [SiteName],
            [Site],
            [CompanyID],
            [CompanyCode],
            [CompanyName],
            [Company],
            [AreaID],
            [AreaCode],
            [AreaName],
            [Area],
            [RegionID],
            [RegionCode],
            [RegionName],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [SiteDistributionTypeID],
            [SiteDistributionTypeName],
            [IsSiteLotNumberEntryRequired],
            [WarehouseTypeID],
            [WarehouseTypeName],
            [GroupID],
            [GroupName],
            [CategoryID],
            [CategoryName],
            [Phone],
            [SFAFlag],
            [SFA],
            [StatusID],
            [StatusName],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted]
        FROM
			[dbo].[fSalesman]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
