USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fSalesOrderReturnSummary]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fSalesOrderReturnSummary];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide function to retrieve [dbo].[SalesOrderReturnSummary] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fSalesOrderReturnSummary]
(
    @DocumentID uniqueidentifier,
    @ProductID int,
    @ProductCode nvarchar(10),
    @ProductName nvarchar(50),
    @ProductBrandID int,
    @ProductBrandCode nvarchar(10),
    @ProductBrandName nvarchar(50),
    @ProductShortName nvarchar(30),
    @ProductStatusID int,
    @ProductAdditionalInfo nvarchar(100)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [SORS].[DocumentID],            
            [SORS].[ProductID],
            [SORS].[PriceDate],
            [fP].[Code] [ProductCode],
            [fP].[Name] [ProductName],
            [fP].[Product],
            [fP].[BrandID] [ProductBrandID],
            [fP].[BrandCode] [ProductBrandCode],
            [fP].[BrandName] [ProductBrandName],
            [fP].[Brand] [ProductBrand],
            [fP].[ShortName] [ProductShortName],
            [fP].[UOMLID] [ProductUOMLID],
            [fP].[UOMMID] [ProductUOMMID],
            [fP].[UOMSID] [ProductUOMSID],
            [fP].[UOMLName] [ProductUOMLName],
            [fP].[UOMMName] [ProductUOMMName],
            [fP].[UOMSName] [ProductUOMSName],
            [fP].[Weight] [ProductWeight],
            [fP].[DimensionL] [ProductDimensionL],
            [fP].[DimensionW] [ProductDimensionW],
            [fP].[DimensionH] [ProductDimensionH],
            [fP].[ConversionL] [ProductConversionL],
            [fP].[ConversionM] [ProductConversionM],
            [fP].[ConversionS] [ProductConversionS],
            [fP].[StatusID] [ProductStatusID],
            [fP].[StatusName] [ProductStatusName],
            [fP].[AdditionalInfo1] [ProductAdditionalInfo1],
            [fP].[AdditionalInfo2] [ProductAdditionalInfo2],
            [fP].[AdditionalInfo3] [ProductAdditionalInfo3],
            [fP].[AdditionalInfo4] [ProductAdditionalInfo4],
            [fP].[AdditionalInfo5] [ProductAdditionalInfo5],
            [fP].[AdditionalInfo6] [ProductAdditionalInfo6],
            [fP].[AdditionalInfo7] [ProductAdditionalInfo7],
            [fP].[AdditionalInfo8] [ProductAdditionalInfo8],
            [fP].[AdditionalInfo9] [ProductAdditionalInfo9],
            [fP].[AdditionalInfo10] [ProductAdditionalInfo10],
            (
                SELECT CASE
                    WHEN [SOR].[DocumentStatusID] = 1 THEN
                    ISNULL(
                    (
                        SELECT
                                SUM([fSOHA].[QtyOnHandHold]) [QtyOnHand]
                            FROM
                                [dbo].[fStockOnHandAvailable]
                                (
                                    [SOR].[WarehouseID],
                                    NULL,
                                    [SORS].[ProductID],
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    @ProductCode,
                                    @ProductName,
                                    @ProductBrandID,
                                    @ProductBrandCode,
                                    @ProductBrandName,
                                    @ProductShortName,
                                    @ProductStatusID,
                                    @ProductAdditionalInfo,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL                
                                ) [fSOHA]
                            GROUP BY
                                [fSOHA].[WarehouseID],
                                [fSOHA].[ProductID]
                    ), 0)
                    ELSE
                        [SORS].[QtyOnHand]
                END
            ) [QtyOnHand],
            [SORS].[QtyConvL],
            [SORS].[QtyConvM],
            [SORS].[QtyConvS],
            [SORS].[Qty],
            (CAST([SORS].[QtyConvL] AS nvarchar(10)) + '/' +  CAST([SORS].[QtyConvM] AS nvarchar(10)) + '/' + CAST([SORS].[QtyConvS] AS nvarchar(10))) [QtyOrderConv],
            ([SORS].[Qty] * -1) [QtyOrder],
            [SORS].[UnitGrossPrice],    
            [SORS].[UnitPrice],
            [SORS].[DiscountStrata1Percentage],
            [SORS].[DiscountStrata2Percentage],
            [SORS].[DiscountStrata3Percentage],
            [SORS].[DiscountStrata4Percentage],
            [SORS].[DiscountStrata5Percentage],
            [SORS].[AddDiscountStrataPercentage],
            [SORS].[TaxPercentage],
            [SORS].[RawSubtotalGrossPrice],
            [SORS].[RawSubtotalPrice],
            [SORS].[RawSubtotalDiscountStrata1],
            ([SORS].[RawSubtotalPrice] - [SORS].[RawSubtotalDiscountStrata1]) [RawDiscountStrata1Amount],            
            [SORS].[RawSubtotalDiscountStrata2],
            ([SORS].[RawSubtotalDiscountStrata1] - [SORS].[RawSubtotalDiscountStrata2]) [RawDiscountStrata2Amount],
            [SORS].[RawSubtotalDiscountStrata3],
            ([SORS].[RawSubtotalDiscountStrata2] - [SORS].[RawSubtotalDiscountStrata3]) [RawDiscountStrata3Amount],
            [SORS].[RawSubtotalDiscountStrata4],
            ([SORS].[RawSubtotalDiscountStrata3] - [SORS].[RawSubtotalDiscountStrata4]) [RawDiscountStrata4Amount],
            [SORS].[RawSubtotalDiscountStrata5],
            ([SORS].[RawSubtotalDiscountStrata4] - [SORS].[RawSubtotalDiscountStrata5]) [RawDiscountStrata5Amount],
            ([SORS].[RawSubtotalDiscountStrata5] - [SORS].[RawSubtotal]) [RawAddDiscountStrataAmount],
            [SORS].[RawSubtotalGross],
            [SORS].[RawSubtotalTax],
            [SORS].[RawSubtotal],
            [SORS].[SubtotalGrossPrice],
            [SORS].[SubtotalPrice],
            [SORS].[SubtotalDiscountStrata1],
            ([SORS].[SubtotalPrice] - [SORS].[SubtotalDiscountStrata1]) [DiscountStrata1Amount],            
            [SORS].[SubtotalDiscountStrata2],
            ([SORS].[SubtotalDiscountStrata1] - [SORS].[SubtotalDiscountStrata2]) [DiscountStrata2Amount],
            [SORS].[SubtotalDiscountStrata3],
            ([SORS].[SubtotalDiscountStrata2] - [SORS].[SubtotalDiscountStrata3]) [DiscountStrata3Amount],
            [SORS].[SubtotalDiscountStrata4],
            ([SORS].[SubtotalDiscountStrata3] - [SORS].[SubtotalDiscountStrata4]) [DiscountStrata4Amount],
            [SORS].[SubtotalDiscountStrata5],
            ([SORS].[SubtotalDiscountStrata4] - [SORS].[SubtotalDiscountStrata5]) [DiscountStrata5Amount],
            ([SORS].[SubtotalDiscountStrata5] - [SORS].[Subtotal]) [AddDiscountStrataAmount],
            [SORS].[SubtotalGross],
            [SORS].[SubtotalTax],
            [SORS].[Subtotal],
            [SORS].[SubtotalWeight],
            [SORS].[SubtotalDimension]
        FROM
			[dbo].[SalesOrderReturnSummary] [SORS] INNER JOIN
            [dbo].[SalesOrderReturn] [SOR] ON ([SORS].[DocumentID] = [SOR].[DocumentID]) INNER JOIN
            [dbo].[fProduct]
            (
                @ProductID,
                @ProductCode,
                @ProductName,
                @ProductBrandID,
                @ProductBrandCode,
                @ProductBrandName,
                @ProductShortName,
                @ProductStatusID,
                @ProductAdditionalInfo,
                NULL
            ) [fP] ON ([SORS].[ProductID] = [fP].[ID])
		WHERE
            ((@DocumentID IS NULL) OR ([SORS].[DocumentID] = @DocumentID)) AND
            ((@ProductID IS NULL) OR ([SORS].[ProductID] = @ProductID))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vSalesOrderReturnSummary]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vSalesOrderReturnSummary];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide view (model) to retrieve [dbo].[fSalesOrderReturnSummary] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vSalesOrderReturnSummary]
AS
(
    SELECT
            [DocumentID],            
            [ProductID],
            [PriceDate],
            [ProductCode],
            [ProductName],
            [Product],
            [ProductBrandID],
            [ProductBrandCode],
            [ProductBrandName],
            [ProductBrand],
            [ProductShortName],
            [ProductUOMLID],
            [ProductUOMMID],
            [ProductUOMSID],
            [ProductUOMLName],
            [ProductUOMMName],
            [ProductUOMSName],
            [ProductWeight],
            [ProductDimensionL],
            [ProductDimensionW],
            [ProductDimensionH],
            [ProductConversionL],
            [ProductConversionM],
            [ProductConversionS],
            [ProductStatusID],
            [ProductStatusName],
            [ProductAdditionalInfo1],
            [ProductAdditionalInfo2],
            [ProductAdditionalInfo3],
            [ProductAdditionalInfo4],
            [ProductAdditionalInfo5],
            [ProductAdditionalInfo6],
            [ProductAdditionalInfo7],
            [ProductAdditionalInfo8],
            [ProductAdditionalInfo9],
            [ProductAdditionalInfo10],
            [QtyOnHand],
            [QtyConvL],
            [QtyConvM],
            [QtyConvS],
            [Qty],
            [QtyOrderConv],
            [QtyOrder],
            [UnitGrossPrice],    
            [UnitPrice],
            [DiscountStrata1Percentage],
            [DiscountStrata2Percentage],
            [DiscountStrata3Percentage],
            [DiscountStrata4Percentage],
            [DiscountStrata5Percentage],
            [AddDiscountStrataPercentage],
            [TaxPercentage],
            [RawSubtotalGrossPrice],
            [RawSubtotalPrice],
            [RawSubtotalDiscountStrata1],
            [RawDiscountStrata1Amount],
            [RawSubtotalDiscountStrata2],
            [RawDiscountStrata2Amount],
            [RawSubtotalDiscountStrata3],
            [RawDiscountStrata3Amount],
            [RawSubtotalDiscountStrata4],
            [RawDiscountStrata4Amount],
            [RawSubtotalDiscountStrata5],
            [RawDiscountStrata5Amount],
            [RawAddDiscountStrataAmount],
            [RawSubtotalGross],
            [RawSubtotalTax],
            [RawSubtotal],
            [SubtotalGrossPrice],
            [SubtotalPrice],
            [SubtotalDiscountStrata1],
            [DiscountStrata1Amount],
            [SubtotalDiscountStrata2],
            [DiscountStrata2Amount],
            [SubtotalDiscountStrata3],
            [DiscountStrata3Amount],
            [SubtotalDiscountStrata4],
            [DiscountStrata4Amount],
            [SubtotalDiscountStrata5],
            [DiscountStrata5Amount],
            [AddDiscountStrataAmount],
            [SubtotalGross],
            [SubtotalTax],
            [Subtotal],
            [SubtotalWeight],
            [SubtotalDimension]
        FROM
			[dbo].[fSalesOrderReturnSummary]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
