USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fSalesOrderSummary]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fSalesOrderSummary];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide function to retrieve [dbo].[SalesOrderSummary] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fSalesOrderSummary]
(
    @DocumentID uniqueidentifier,
    @ProductID int,
    @ProductCode nvarchar(10),
    @ProductName nvarchar(50),
    @ProductBrandID int,
    @ProductBrandCode nvarchar(10),
    @ProductBrandName nvarchar(50),
    @ProductShortName nvarchar(30),
    @ProductStatusID int,
    @ProductAdditionalInfo nvarchar(100)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [SOS].[DocumentID],            
            [SOS].[ProductID],
            [SOS].[PriceDate],
            [fP].[Code] [ProductCode],
            [fP].[Name] [ProductName],
            [fP].[Product],
            [fP].[BrandID] [ProductBrandID],
            [fP].[BrandCode] [ProductBrandCode],
            [fP].[BrandName] [ProductBrandName],
            [fP].[Brand] [ProductBrand],
            [fP].[ShortName] [ProductShortName],
            [fP].[UOMLID] [ProductUOMLID],
            [fP].[UOMMID] [ProductUOMMID],
            [fP].[UOMSID] [ProductUOMSID],
            [fP].[UOMLName] [ProductUOMLName],
            [fP].[UOMMName] [ProductUOMMName],
            [fP].[UOMSName] [ProductUOMSName],
            [fP].[Weight] [ProductWeight],
            [fP].[DimensionL] [ProductDimensionL],
            [fP].[DimensionW] [ProductDimensionW],
            [fP].[DimensionH] [ProductDimensionH],
            [fP].[ConversionL] [ProductConversionL],
            [fP].[ConversionM] [ProductConversionM],
            [fP].[ConversionS] [ProductConversionS],
            [fP].[StatusID] [ProductStatusID],
            [fP].[StatusName] [ProductStatusName],
            [fP].[AdditionalInfo1] [ProductAdditionalInfo1],
            [fP].[AdditionalInfo2] [ProductAdditionalInfo2],
            [fP].[AdditionalInfo3] [ProductAdditionalInfo3],
            [fP].[AdditionalInfo4] [ProductAdditionalInfo4],
            [fP].[AdditionalInfo5] [ProductAdditionalInfo5],
            [fP].[AdditionalInfo6] [ProductAdditionalInfo6],
            [fP].[AdditionalInfo7] [ProductAdditionalInfo7],
            [fP].[AdditionalInfo8] [ProductAdditionalInfo8],
            [fP].[AdditionalInfo9] [ProductAdditionalInfo9],
            [fP].[AdditionalInfo10] [ProductAdditionalInfo10],
            (
                SELECT CASE
                    WHEN [SO].[DocumentStatusID] = 1 THEN
                    ISNULL(
                    (
                        SELECT
                                SUM([fSOHA].[QtyOnHandGood]) [QtyOnHand]
                            FROM
                                [dbo].[fStockOnHandAvailable]
                                (
                                    [SO].[WarehouseID],
                                    NULL,
                                    [SOS].[ProductID],
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    @ProductCode,
                                    @ProductName,
                                    @ProductBrandID,
                                    @ProductBrandCode,
                                    @ProductBrandName,
                                    @ProductShortName,
                                    @ProductStatusID,
                                    @ProductAdditionalInfo,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL,
                                    NULL                
                                ) [fSOHA]
                            GROUP BY
                                [fSOHA].[WarehouseID],
                                [fSOHA].[ProductID]
                    ), 0)
                    ELSE
                        [SOS].[QtyOnHand]
                END
            ) [QtyOnHand],
            [SOS].[QtyConvL],
            [SOS].[QtyConvM],
            [SOS].[QtyConvS],
            [SOS].[Qty],
            (CAST([SOS].[QtyConvL] AS nvarchar(10)) + '/' +  CAST([SOS].[QtyConvM] AS nvarchar(10)) + '/' + CAST([SOS].[QtyConvS] AS nvarchar(10))) [QtyOrderConv],
            ([SOS].[Qty] * -1) [QtyOrder],
            [SOS].[UnitGrossPrice],    
            [SOS].[UnitPrice],
            [SOS].[DiscountStrata1Percentage],
            [SOS].[DiscountStrata2Percentage],
            [SOS].[DiscountStrata3Percentage],
            [SOS].[DiscountStrata4Percentage],
            [SOS].[DiscountStrata5Percentage],
            [SOS].[AddDiscountStrataPercentage],
            [SOS].[TaxPercentage],
            [SOS].[RawSubtotalGrossPrice],
            [SOS].[RawSubtotalPrice],
            [SOS].[RawSubtotalDiscountStrata1],
            ([SOS].[RawSubtotalPrice] - [SOS].[RawSubtotalDiscountStrata1]) [RawDiscountStrata1Amount],            
            [SOS].[RawSubtotalDiscountStrata2],
            ([SOS].[RawSubtotalDiscountStrata1] - [SOS].[RawSubtotalDiscountStrata2]) [RawDiscountStrata2Amount],
            [SOS].[RawSubtotalDiscountStrata3],
            ([SOS].[RawSubtotalDiscountStrata2] - [SOS].[RawSubtotalDiscountStrata3]) [RawDiscountStrata3Amount],
            [SOS].[RawSubtotalDiscountStrata4],
            ([SOS].[RawSubtotalDiscountStrata3] - [SOS].[RawSubtotalDiscountStrata4]) [RawDiscountStrata4Amount],
            [SOS].[RawSubtotalDiscountStrata5],
            ([SOS].[RawSubtotalDiscountStrata4] - [SOS].[RawSubtotalDiscountStrata5]) [RawDiscountStrata5Amount],
            ([SOS].[RawSubtotalDiscountStrata5] - [SOS].[RawSubtotal]) [RawAddDiscountStrataAmount],
            [SOS].[RawSubtotalGross],
            [SOS].[RawSubtotalTax],
            [SOS].[RawSubtotal],
            [SOS].[SubtotalGrossPrice],
            [SOS].[SubtotalPrice],
            [SOS].[SubtotalDiscountStrata1],
            ([SOS].[SubtotalPrice] - [SOS].[SubtotalDiscountStrata1]) [DiscountStrata1Amount],            
            [SOS].[SubtotalDiscountStrata2],
            ([SOS].[SubtotalDiscountStrata1] - [SOS].[SubtotalDiscountStrata2]) [DiscountStrata2Amount],
            [SOS].[SubtotalDiscountStrata3],
            ([SOS].[SubtotalDiscountStrata2] - [SOS].[SubtotalDiscountStrata3]) [DiscountStrata3Amount],
            [SOS].[SubtotalDiscountStrata4],
            ([SOS].[SubtotalDiscountStrata3] - [SOS].[SubtotalDiscountStrata4]) [DiscountStrata4Amount],
            [SOS].[SubtotalDiscountStrata5],
            ([SOS].[SubtotalDiscountStrata4] - [SOS].[SubtotalDiscountStrata5]) [DiscountStrata5Amount],
            ([SOS].[SubtotalDiscountStrata5] - [SOS].[Subtotal]) [AddDiscountStrataAmount],
            [SOS].[SubtotalGross],
            [SOS].[SubtotalTax],
            [SOS].[Subtotal],
            [SOS].[SubtotalWeight],
            [SOS].[SubtotalDimension]
        FROM
			[dbo].[SalesOrderSummary] [SOS] INNER JOIN
            [dbo].[SalesOrder] [SO] ON ([SOS].[DocumentID] = [SO].[DocumentID]) INNER JOIN            
            [dbo].[fProduct]
            (
                @ProductID,
                @ProductCode,
                @ProductName,
                @ProductBrandID,
                @ProductBrandCode,
                @ProductBrandName,
                @ProductShortName,
                @ProductStatusID,
                @ProductAdditionalInfo,
                NULL
            ) [fP] ON ([SOS].[ProductID] = [fP].[ID])
		WHERE
            ((@DocumentID IS NULL) OR ([SOS].[DocumentID] = @DocumentID)) AND
            ((@ProductID IS NULL) OR ([SOS].[ProductID] = @ProductID))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vSalesOrderSummary]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vSalesOrderSummary];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide view (model) to retrieve [dbo].[fSalesOrderSummary] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vSalesOrderSummary]
AS
(
    SELECT
            [DocumentID],            
            [ProductID],
            [PriceDate],
            [ProductCode],
            [ProductName],
            [Product],
            [ProductBrandID],
            [ProductBrandCode],
            [ProductBrandName],
            [ProductBrand],
            [ProductShortName],
            [ProductUOMLID],
            [ProductUOMMID],
            [ProductUOMSID],
            [ProductUOMLName],
            [ProductUOMMName],
            [ProductUOMSName],
            [ProductWeight],
            [ProductDimensionL],
            [ProductDimensionW],
            [ProductDimensionH],
            [ProductConversionL],
            [ProductConversionM],
            [ProductConversionS],
            [ProductStatusID],
            [ProductStatusName],
            [ProductAdditionalInfo1],
            [ProductAdditionalInfo2],
            [ProductAdditionalInfo3],
            [ProductAdditionalInfo4],
            [ProductAdditionalInfo5],
            [ProductAdditionalInfo6],
            [ProductAdditionalInfo7],
            [ProductAdditionalInfo8],
            [ProductAdditionalInfo9],
            [ProductAdditionalInfo10],
            [QtyOnHand],
            [QtyConvL],
            [QtyConvM],
            [QtyConvS],
            [Qty],
            [QtyOrderConv],
            [QtyOrder],
            [UnitGrossPrice],    
            [UnitPrice],
            [DiscountStrata1Percentage],
            [DiscountStrata2Percentage],
            [DiscountStrata3Percentage],
            [DiscountStrata4Percentage],
            [DiscountStrata5Percentage],
            [AddDiscountStrataPercentage],
            [TaxPercentage],
            [RawSubtotalGrossPrice],
            [RawSubtotalPrice],
            [RawSubtotalDiscountStrata1],
            [RawDiscountStrata1Amount],
            [RawSubtotalDiscountStrata2],
            [RawDiscountStrata2Amount],
            [RawSubtotalDiscountStrata3],
            [RawDiscountStrata3Amount],
            [RawSubtotalDiscountStrata4],
            [RawDiscountStrata4Amount],
            [RawSubtotalDiscountStrata5],
            [RawDiscountStrata5Amount],
            [RawAddDiscountStrataAmount],
            [RawSubtotalGross],
            [RawSubtotalTax],
            [RawSubtotal],
            [SubtotalGrossPrice],
            [SubtotalPrice],
            [SubtotalDiscountStrata1],
            [DiscountStrata1Amount],
            [SubtotalDiscountStrata2],
            [DiscountStrata2Amount],
            [SubtotalDiscountStrata3],
            [DiscountStrata3Amount],
            [SubtotalDiscountStrata4],
            [DiscountStrata4Amount],
            [SubtotalDiscountStrata5],
            [DiscountStrata5Amount],
            [AddDiscountStrataAmount],
            [SubtotalGross],
            [SubtotalTax],
            [Subtotal],
            [SubtotalWeight],
            [SubtotalDimension]
        FROM
			[dbo].[fSalesOrderSummary]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
