USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fSalesmanInitialCall]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fSalesmanInitialCall];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide function to retrieve [dbo].[SalesmanInitialCall] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fSalesmanInitialCall]
(
    @SalesmanID uniqueidentifier,    
    @CallDateFrom datetime,
    @CallDateTo datetime,
    @SalesmanCode nvarchar(10),
    @SalesmanName nvarchar(50),
    @WarehouseID uniqueidentifier,
    @WarehouseCode nvarchar(10),
    @WarehouseName nvarchar(50),        
    @SiteID uniqueidentifier,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),    
    @SiteDistributionTypeID int,
    @WarehouseTypeID int,
    @SalesmanGroupID int,
    @SalesmanCategoryID int,
    @SalesmanStatusID int,
    @IsSiteLotNumberEntryRequired bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [SIC].[SalesmanID],
            [SIC].[CallDate],            
            [fS].[Code] [SalesmanCode],
            [fS].[Name] [SalesmanName],
            [fS].[Salesman],
            [fS].[WarehouseID],
            [fS].[WarehouseCode],
            [fS].[WarehouseName],
            [fS].[Warehouse],
            [fS].[SiteID],
            [fS].[SiteCode],
            [fS].[SiteName],
            [fS].[Site],
            [fS].[CompanyID],
            [fS].[CompanyCode],
            [fS].[CompanyName],
            [fS].[Company],
            [fS].[AreaID],
            [fS].[AreaCode],
            [fS].[AreaName],
            [fS].[Area],
            [fS].[RegionID],
            [fS].[RegionCode],
            [fS].[RegionName],
            [fS].[Region],
            [fS].[TerritoryID],
            [fS].[TerritoryCode],
            [fS].[TerritoryName],
            [fS].[Territory],
            [fS].[SiteDistributionTypeID],
            [fS].[SiteDistributionTypeName],            
            [fS].[WarehouseTypeID],
            [fS].[WarehouseTypeName],
            [fS].[GroupID] [SalesmanGroupID],
            [fS].[GroupName] [SalesmanGroupName],
            [fS].[CategoryID] [SalesmanCategoryID],
            [fS].[CategoryName] [SalesmanCategoryName],
            [fS].[Phone] [SalesmanPhoneID],
            [fS].[SFA] [SalesmanSFA],
            [fS].[StatusID] [SalesmanStatusID],
            [fS].[StatusName] [SalesmanStatusName],
            [fS].[IsDeleted] [IsSalesmanDeleted],
            [SIC].[StartOdometer],
            [SIC].[EndOdometer],
            [SIC].[EndOfDayPrintCount],            
            [SIC].[CreatedDate],
            [SIC].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [SIC].[ModifiedDate],
            [SIC].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName]
        FROM
			[dbo].[SalesmanInitialCall] [SIC] INNER JOIN
            [dbo].[fSalesman]
            (
                @SalesmanID,
                @SalesmanCode,
                @SalesmanName,
                @WarehouseID,
                @WarehouseCode,
                @WarehouseName,
                @SiteID,
                @SiteCode,
                @SiteName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,    
                @SiteDistributionTypeID,
				NULL,
                @WarehouseTypeID,
                @SalesmanGroupID,
                @SalesmanCategoryID,
                NULL,
                NULL,
                @SalesmanStatusID,
                NULL
            ) [fS] ON ([SIC].[SalesmanID] = [fS].[ID]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([SIC].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([SIC].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@CallDateFrom IS NULL) OR ([dbo].[ValidateMaxDate]([SIC].[CallDate]) >= [dbo].[ValidateMinDate](@CallDateFrom))) AND
            ((@CallDateTo IS NULL) OR ([dbo].[ValidateMinDate]([SIC].[CallDate]) <= [dbo].[ValidateMaxDate](@CallDateTo))) AND
            ((@SalesmanID IS NULL) OR ([SIC].[SalesmanID] = @SalesmanID))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vSalesmanInitialCall]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vSalesmanInitialCall];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide view (model) to retrieve [dbo].[fSalesmanInitialCall] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vSalesmanInitialCall]
AS
(
    SELECT
            [SalesmanID],
            [CallDate],            
            [SalesmanCode],
            [SalesmanName],
            [Salesman],
            [WarehouseID],
            [WarehouseCode],
            [WarehouseName],
            [Warehouse],
            [SiteID],
            [SiteCode],
            [SiteName],
            [Site],
            [CompanyID],
            [CompanyCode],
            [CompanyName],
            [Company],
            [AreaID],
            [AreaCode],
            [AreaName],
            [Area],
            [RegionID],
            [RegionCode],
            [RegionName],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [SiteDistributionTypeID],
            [SiteDistributionTypeName],            
            [WarehouseTypeID],
            [WarehouseTypeName],
            [SalesmanGroupID],
            [SalesmanGroupName],
            [SalesmanCategoryID],
            [SalesmanCategoryName],
            [SalesmanPhoneID],
            [SalesmanSFA],
            [SalesmanStatusID],
            [SalesmanStatusName],
            [IsSalesmanDeleted],
            [StartOdometer],
            [EndOdometer],
            [EndOfDayPrintCount],            
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName]
        FROM
			[dbo].[fSalesmanInitialCall]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
