USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fSalesmanCall]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fSalesmanCall];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide function to retrieve [dbo].[SalesmanCall] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fSalesmanCall]
(
    @ID uniqueidentifier,
    @SalesmanID uniqueidentifier,    
    @CallDateFrom datetime,
    @CallDateTo datetime,
    @CustomerID uniqueidentifier,
    @SalesmanCode nvarchar(10),
    @SalesmanName nvarchar(50),
    @WarehouseID uniqueidentifier,
    @WarehouseCode nvarchar(10),
    @WarehouseName nvarchar(50),        
    @SiteID uniqueidentifier,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),    
    @SiteDistributionTypeID int,
    @WarehouseTypeID int,
    @SalesmanGroupID int,
    @SalesmanCategoryID int,
    @SalesmanStatusID int,
    @IsSiteLotNumberEntryRequired bit,
    @CustomerCode nvarchar(10),
    @CustomerName nvarchar(50),
    @IsInRoute bit,
    @StatusID int,
    @IsTransactionPaid bit,
    @NoTransactionReasonID int
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [SC].[ID],
            [SC].[SalesmanID],
            [SC].[CallDate],
            [SC].[CustomerID],            
            [fS].[Code] [SalesmanCode],
            [fS].[Name] [SalesmanName],
            [fS].[Salesman],
            [fS].[WarehouseID],
            [fS].[WarehouseCode],
            [fS].[WarehouseName],
            [fS].[Warehouse],
            [fS].[SiteID],
            [fS].[SiteCode],
            [fS].[SiteName],
            [fS].[Site],
            [fS].[CompanyID],
            [fS].[CompanyCode],
            [fS].[CompanyName],
            [fS].[Company],
            [fS].[AreaID],
            [fS].[AreaCode],
            [fS].[AreaName],
            [fS].[Area],
            [fS].[RegionID],
            [fS].[RegionCode],
            [fS].[RegionName],
            [fS].[Region],
            [fS].[TerritoryID],
            [fS].[TerritoryCode],
            [fS].[TerritoryName],
            [fS].[Territory],
            [fS].[SiteDistributionTypeID],
            [fS].[SiteDistributionTypeName],            
            [fS].[WarehouseTypeID],
            [fS].[WarehouseTypeName],
            [fS].[GroupID] [SalesmanGroupID],
            [fS].[GroupName] [SalesmanGroupName],
            [fS].[CategoryID] [SalesmanCategoryID],
            [fS].[CategoryName] [SalesmanCategoryName],
            [fS].[Phone] [SalesmanPhoneID],
            [fS].[SFA] [SalesmanSFA],
            [fS].[StatusID] [SalesmanStatusID],
            [fS].[StatusName] [SalesmanStatusName],
            [fS].[IsDeleted] [IsSalesmanDeleted],            
            [C].[Code] [CustomerCode],
            [C].[Name] [CustomerName],
            [dbo].[fCodeNameFormatter]([C].[Code], [C].[Name]) [Customer],
            [SC].[IsInRoute],
            [SC].[MerchandiseDisplayActivityNote],
            [SC].[PromoMaterialActivityNote],
            [SC].[StatusID],
            [fSL].[Name] [StatusName],
            [SC].[IsTransactionPaid],
            [SC].[NoTransactionReasonID],
            [fSL2].[Name] [NoTransactionReasonName],
            [SC].[CreatedDate],
            [SC].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [SC].[ModifiedDate],
            [SC].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName]
        FROM
			[dbo].[SalesmanCall] [SC] INNER JOIN
            [dbo].[fSalesman]
            (
                @SalesmanID,
                @SalesmanCode,
                @SalesmanName,
                @WarehouseID,
                @WarehouseCode,
                @WarehouseName,
                @SiteID,
                @SiteCode,
                @SiteName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,    
                @SiteDistributionTypeID,
				NULL,
                @WarehouseTypeID,
                @SalesmanGroupID,
                @SalesmanCategoryID,
                NULL,
                NULL,
                @SalesmanStatusID,
                NULL
            ) [fS] ON ([SC].[SalesmanID] = [fS].[ID]) INNER JOIN            
            [dbo].[Customer] [C] ON ([SC].[CustomerID] = [C].[ID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'SalesmanCallStatus',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([SC].[StatusID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'SalesmanCallNoTrxReason',
                NULL,
                NULL,
                NULL
            ) [fSL2] ON ([SC].[NoTransactionReasonID] = [fSL2].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([SC].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([SC].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@CallDateFrom IS NULL) OR ([dbo].[ValidateMaxDate]([SC].[CallDate]) >= [dbo].[ValidateMinDate](@CallDateFrom))) AND
            ((@CallDateTo IS NULL) OR ([dbo].[ValidateMinDate]([SC].[CallDate]) <= [dbo].[ValidateMaxDate](@CallDateTo))) AND
            ((@SalesmanID IS NULL) OR ([SC].[SalesmanID] = @SalesmanID)) AND
            ((@CustomerID IS NULL) OR ([SC].[CustomerID] = @CustomerID)) AND
            ((@IsInRoute IS NULL) OR ([SC].[IsInRoute] = @IsInRoute)) AND
            ((@StatusID IS NULL) OR ([SC].[StatusID] = @StatusID)) AND
            ((@IsTransactionPaid IS NULL) OR ([SC].[IsTransactionPaid] = @IsTransactionPaid)) AND
            ((@NoTransactionReasonID IS NULL) OR ([SC].[NoTransactionReasonID] = @NoTransactionReasonID))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vSalesmanCall]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vSalesmanCall];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide view (model) to retrieve [dbo].[fSalesmanCall] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vSalesmanCall]
AS
(
    SELECT
            [ID],
            [SalesmanID],
            [CallDate],
            [CustomerID],            
            [SalesmanCode],
            [SalesmanName],
            [Salesman],
            [WarehouseID],
            [WarehouseCode],
            [WarehouseName],
            [Warehouse],
            [SiteID],
            [SiteCode],
            [SiteName],
            [Site],
            [CompanyID],
            [CompanyCode],
            [CompanyName],
            [Company],
            [AreaID],
            [AreaCode],
            [AreaName],
            [Area],
            [RegionID],
            [RegionCode],
            [RegionName],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [SiteDistributionTypeID],
            [SiteDistributionTypeName],            
            [WarehouseTypeID],
            [WarehouseTypeName],
            [SalesmanGroupID],
            [SalesmanGroupName],
            [SalesmanCategoryID],
            [SalesmanCategoryName],
            [SalesmanPhoneID],
            [SalesmanSFA],
            [SalesmanStatusID],
            [SalesmanStatusName],
            [IsSalesmanDeleted],            
            [CustomerCode],
            [CustomerName],
            [Customer],
            [IsInRoute],
            [MerchandiseDisplayActivityNote],
            [PromoMaterialActivityNote],
            [StatusID],
            [StatusName],
            [IsTransactionPaid],
            [NoTransactionReasonID],
            [NoTransactionReasonName],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName]
        FROM
			[dbo].[fSalesmanCall]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
