USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fSiteAdditionalInfo]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fSiteAdditionalInfo];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[SiteAdditionalInfo] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fSiteAdditionalInfo]
(
    @SiteID uniqueidentifier,
    @AdditionalInfo nvarchar(100)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [SAI].[SiteID],
            [SAI].[AdditionalInfo1],
            [SAI].[AdditionalInfo2],
            [SAI].[AdditionalInfo3],
            [SAI].[AdditionalInfo4],
            [SAI].[AdditionalInfo5],
            [SAI].[AdditionalInfo6],
            [SAI].[AdditionalInfo7],
            [SAI].[AdditionalInfo8],
            [SAI].[AdditionalInfo9],
            [SAI].[AdditionalInfo10] 
        FROM
			[dbo].[SiteAdditionalInfo] [SAI]
		WHERE
            ((@SiteID IS NULL) OR ([SAI].[SiteID] = @SiteID)) AND
            (
                (@AdditionalInfo IS NULL) OR
                (
                    ([SAI].[AdditionalInfo1] LIKE '%' + @AdditionalInfo + '%') OR
                    ([SAI].[AdditionalInfo2] LIKE '%' + @AdditionalInfo + '%') OR
                    ([SAI].[AdditionalInfo3] LIKE '%' + @AdditionalInfo + '%') OR
                    ([SAI].[AdditionalInfo4] LIKE '%' + @AdditionalInfo + '%') OR
                    ([SAI].[AdditionalInfo5] LIKE '%' + @AdditionalInfo + '%') OR
                    ([SAI].[AdditionalInfo6] LIKE '%' + @AdditionalInfo + '%') OR
                    ([SAI].[AdditionalInfo7] LIKE '%' + @AdditionalInfo + '%') OR
                    ([SAI].[AdditionalInfo8] LIKE '%' + @AdditionalInfo + '%') OR
                    ([SAI].[AdditionalInfo9] LIKE '%' + @AdditionalInfo + '%') OR
                    ([SAI].[AdditionalInfo10] LIKE '%' + @AdditionalInfo + '%')
                )
            )
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vSiteAdditionalInfo]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vSiteAdditionalInfo];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fSiteAdditionalInfo] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vSiteAdditionalInfo]
AS
(
    SELECT
            [SiteID],
            [AdditionalInfo1],
            [AdditionalInfo2],
            [AdditionalInfo3],
            [AdditionalInfo4],
            [AdditionalInfo5],
            [AdditionalInfo6],
            [AdditionalInfo7],
            [AdditionalInfo8],
            [AdditionalInfo9],
            [AdditionalInfo10] 
        FROM
			[dbo].[fSiteAdditionalInfo]
            (
                NULL,
                NULL
            )
);
GO
