USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [dbo].[SiteProduct]
(
    [SiteID] [uniqueidentifier] NOT NULL,
	[ProductID] [int] NOT NULL,
	CONSTRAINT [PK_SiteProduct] PRIMARY KEY CLUSTERED
    (
	    [SiteID] ASC,
        [ProductID]
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

ALTER TABLE [dbo].[SiteProduct] WITH CHECK ADD CONSTRAINT [FK_SiteProduct_Site] FOREIGN KEY
(
    [SiteID]
) REFERENCES [dbo].[Site] ([ID]) ON UPDATE NO ACTION;
GO

ALTER TABLE [dbo].[SiteProduct] CHECK CONSTRAINT [FK_SiteProduct_Site];
GO

ALTER TABLE [dbo].[SiteProduct] WITH CHECK ADD CONSTRAINT [FK_SiteProduct_Product] FOREIGN KEY
(
    [ProductID]
) REFERENCES [dbo].[Product] ([ID]) ON UPDATE CASCADE;
GO

ALTER TABLE [dbo].[SiteProduct] CHECK CONSTRAINT [FK_SiteProduct_Product];
GO

ALTER TABLE [dbo].[SiteProduct] 
ENABLE CHANGE_TRACKING 
