USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fSiteAddress]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fSiteAddress];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[SiteAddress] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fSiteAddress]
(
    @SiteID uniqueidentifier,
    @Address nvarchar(100),
    @City nvarchar(50),
    @StateProvince nvarchar(50),
    @CountryID int,
    @CountryName nvarchar(50),
    @ZipCode nvarchar(10),
    @Phone1 nvarchar(20),
    @Phone2 nvarchar(20),
    @Fax nvarchar(20),
    @Email nvarchar(256)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [SA].[SiteID],
            [SA].[Address1],
            [SA].[Address2],
            [SA].[Address3],
            [dbo].[fAddressFormatter]([SA].[Address1], [SA].[Address2], [SA].[Address3]) [Address],
            [SA].[City],
            [SA].[StateProvince],
            [SA].[CountryID],
            [fC].[Name] [CountryName],
            [SA].[ZipCode],
            [SA].[Phone1],
            [SA].[Phone2],
            [SA].[Fax],
            [SA].[Email]            
        FROM
			[dbo].[SiteAddress] [SA] INNER JOIN
            [dbo].[fCountry]
            (
                @CountryID,
                @CountryName,
                NULL,
                NULL
            ) [fC] ON ([SA].[CountryID] = [fC].[ID])
		WHERE
            ((@SiteID IS NULL) OR ([SA].[SiteID] = @SiteID)) AND
            (
                (@Address IS NULL) OR
                (
                    ([SA].[Address1] LIKE '%' + @Address + '%') OR
                    ([SA].[Address2] LIKE '%' + @Address + '%') OR
                    ([SA].[Address3] LIKE '%' + @Address + '%')
                )
            ) AND
            ((@City IS NULL) OR ([SA].[City] LIKE '%' + @City + '%')) AND
            ((@StateProvince IS NULL) OR ([SA].[StateProvince] LIKE '%' + @StateProvince + '%')) AND
            ((@ZipCode IS NULL) OR ([SA].[ZipCode] LIKE '%' + @ZipCode + '%')) AND
            ((@Phone1 IS NULL) OR ([SA].[Phone1] LIKE '%' + @Phone1 + '%')) AND
            ((@Phone2 IS NULL) OR ([SA].[Phone2] LIKE '%' + @Phone2 + '%')) AND
            ((@Fax IS NULL) OR ([SA].[Fax] LIKE '%' + @Fax + '%')) AND
            ((@Email IS NULL) OR ([SA].[Email] LIKE '%' + @Email + '%'))            
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vSiteAddress]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vSiteAddress];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fSiteAddress] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vSiteAddress]
AS
(
    SELECT
            [SiteID],
            [Address1],
            [Address2],
            [Address3],
            [Address],
            [City],
            [StateProvince],
            [CountryID],
            [CountryName],
            [ZipCode],
            [Phone1],
            [Phone2],
            [Fax],
            [Email]            
        FROM
			[dbo].[fSiteAddress]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
