USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fStockOnHandAvailable]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fStockOnHandAvailable];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:11:40
-- Description   : Provide function to retrieve [dbo].[StockOnHandAvailable] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fStockOnHandAvailable]
(    
    @WarehouseID uniqueidentifier,
    @TransactionDate datetime,
    @ProductID int,
    @ProductLotID int,
    @WarehouseCode nvarchar(10),
    @WarehouseName nvarchar(50),
    @SiteID uniqueidentifier,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @SiteDistributionTypeID int,
    @IsSiteLotNumberEntryRequired bit,
    @WarehouseTypeID int,
    @IsWarehouseSOAllowed bit,
    @WarehouseStatusID int,
    @IsWarehouseDeleted bit,
    @ProductCode nvarchar(10),
    @ProductName nvarchar(50),
    @ProductBrandID int,
    @ProductBrandCode nvarchar(10),
    @ProductBrandName nvarchar(50),
    @ProductShortName nvarchar(30),
    @ProductStatusID int,
    @ProductAdditionalInfo nvarchar(100),
    @ProductLotCode nvarchar(20),
    @ProductLotExpiredDateFrom datetime,
    @ProductLotExpiredDateTo datetime,
    @ProductLotStatusID int,
    @IsProductLotDeleted bit
)
RETURNS @result TABLE
(
    [WarehouseID] uniqueidentifier,
    [ProductID] int,
    [ProductLotID] int,
    [QtyPeriodOnHandGood] int,
    [QtyPeriodOnHandHold] int,
    [QtyPeriodOnHandBad] int,
    [QtyTransactionGood] int,
    [QtyTransactionHold] int,
    [QtyTransactionBad] int,
    [QtyOnHandGood] int,
    [QtyOnHandHold] int,
    [QtyOnHandBad] int,
    [ProductCode] nvarchar(10),
    [ProductName] nvarchar(50),
    [Product] nvarchar(60),
    [ProductBrandID] int,
    [ProductBrandCode] nvarchar(10),
    [ProductBrandName] nvarchar(50),
    [ProductBrand] nvarchar(60),
    [ProductShortName] nvarchar(30),
    [ProductUOMLID] int,
    [ProductUOMMID] int,
    [ProductUOMSID] int,
    [ProductUOMLName] nvarchar(128),
    [ProductUOMMName] nvarchar(128),
    [ProductUOMSName] nvarchar(128),
    [ProductWeight] float,
    [ProductDimensionL] int,
    [ProductDimensionW] int,
    [ProductDimensionH] int,
    [ProductConversionL] int,
    [ProductConversionM] int,
    [ProductConversionS] int,
    [ProductStatusID] int NOT NULL,
    [ProductStatusName] nvarchar(128),
    [ProductAdditionalInfo1] nvarchar(100),
    [ProductAdditionalInfo2] nvarchar(100),
    [ProductAdditionalInfo3] nvarchar(100),
    [ProductAdditionalInfo4] nvarchar(100),
    [ProductAdditionalInfo5] nvarchar(100),
    [ProductAdditionalInfo6] nvarchar(100),
    [ProductAdditionalInfo7] nvarchar(100),
    [ProductAdditionalInfo8] nvarchar(100),
    [ProductAdditionalInfo9] nvarchar(100),
    [ProductAdditionalInfo10] nvarchar(100),
    [ProductLotCode] nvarchar(20),
    [ProductLotExpiredDate] datetime,
    [ProductLot] nvarchar(100),
    [ProductLotStatusID] int,
    [ProductLotStatusName] nvarchar(128),
    [IsProductLotCodeDeleted] bit
)
AS
BEGIN
    IF (@TransactionDate IS NULL)
        INSERT INTO @result
            SELECT
                    [WarehouseID],
                    [ProductID],
                    [ProductLotID],
                    CAST(0 AS int) [QtyPeriodOnHandGood],
                    CAST(0 AS int) [QtyPeriodOnHandHold],
                    CAST(0 AS int) [QtyPeriodOnHandBad],
                    [QtyOnHandGood] [QtyTransactionGood],
                    [QtyOnHandHold] [QtyTransactionHold],
                    [QtyOnHandBad] [QtyTransactionBad],
                    [QtyOnHandGood],
                    [QtyOnHandHold],
                    [QtyOnHandBad],                    
                    [ProductCode],
                    [ProductName],
                    [Product],
                    [ProductBrandID],
                    [ProductBrandCode],
                    [ProductBrandName],
                    [ProductBrand],
                    [ProductShortName],
                    [ProductUOMLID],
                    [ProductUOMMID],
                    [ProductUOMSID],
                    [ProductUOMLName],
                    [ProductUOMMName],
                    [ProductUOMSName],
                    [ProductWeight],
                    [ProductDimensionL],
                    [ProductDimensionW],
                    [ProductDimensionH],
                    [ProductConversionL],
                    [ProductConversionM],
                    [ProductConversionS],
                    [ProductStatusID],
                    [ProductStatusName],
                    [ProductAdditionalInfo1],
                    [ProductAdditionalInfo2],
                    [ProductAdditionalInfo3],
                    [ProductAdditionalInfo4],
                    [ProductAdditionalInfo5],
                    [ProductAdditionalInfo6],
                    [ProductAdditionalInfo7],
                    [ProductAdditionalInfo8],
                    [ProductAdditionalInfo9],
                    [ProductAdditionalInfo10],
                    [ProductLotCode],
                    [ProductLotExpiredDate],
                    [ProductLot],
                    [ProductLotStatusID],
                    [ProductLotStatusName],
                    [IsProductLotCodeDeleted]
                FROM
			        [dbo].[fStockOnHandCurrent]
                    (
                        @WarehouseID,
                        @ProductID,
                        @ProductLotID,
                        @WarehouseCode,
                        @WarehouseName,
                        @SiteID,
                        @SiteCode,
                        @SiteName,
                        @AreaID,
                        @AreaCode,
                        @AreaName,
                        @RegionID,
                        @RegionCode,
                        @RegionName,
                        @TerritoryID,
                        @TerritoryCode,
                        @TerritoryName,
                        @CompanyID,
                        @CompanyCode,
                        @CompanyName,
                        @SiteDistributionTypeID,
                        @IsSiteLotNumberEntryRequired,
                        @WarehouseTypeID,
                        @IsWarehouseSOAllowed,
                        @WarehouseStatusID,
                        @IsWarehouseDeleted,
                        @ProductCode,
                        @ProductName,
                        @ProductBrandID,
                        @ProductBrandCode,
                        @ProductBrandName,
                        @ProductShortName,
                        @ProductStatusID,
                        @ProductAdditionalInfo,
                        @ProductLotCode,
                        @ProductLotExpiredDateFrom,
                        @ProductLotExpiredDateTo,
                        @ProductLotStatusID,
                        @IsProductLotDeleted
                    )        
        ELSE
            INSERT INTO @result
                SELECT
                        [fSOHC].[WarehouseID],
                        [fSOHC].[ProductID],
                        [fSOHC].[ProductLotID],
                        [fSOHC].[QtyPeriodOnHandGood],
                        [fSOHC].[QtyPeriodOnHandHold],
                        [fSOHC].[QtyPeriodOnHandBad],
                        [fSOHC].[QtyTransactionGood],
                        [fSOHC].[QtyTransactionHold],
                        [fSOHC].[QtyTransactionBad],
                        [fSOHC].[QtyPeriodOnHandGood] + [fSOHC].[QtyTransactionGood] [QtyOnHandGood],
                        [fSOHC].[QtyPeriodOnHandHold] + [fSOHC].[QtyTransactionHold] [QtyOnHandHold],
                        [fSOHC].[QtyPeriodOnHandBad] + [fSOHC].[QtyTransactionBad] [QtyOnHandBad],
                        [fPL].[ProductCode],
                        [fPL].[ProductName],
                        [fPL].[Product],
                        [fPL].[ProductBrandID],
                        [fPL].[ProductBrandCode],
                        [fPL].[ProductBrandName],
                        [fPL].[ProductBrand],
                        [fPL].[ProductShortName],
                        [fPL].[ProductUOMLID],
                        [fPL].[ProductUOMMID],
                        [fPL].[ProductUOMSID],
                        [fPL].[ProductUOMLName],
                        [fPL].[ProductUOMMName],
                        [fPL].[ProductUOMSName],        
                        [fPL].[ProductWeight],
                        [fPL].[ProductDimensionL],
                        [fPL].[ProductDimensionW],
                        [fPL].[ProductDimensionH],
                        [fPL].[ProductConversionL],
                        [fPL].[ProductConversionM],
                        [fPL].[ProductConversionS],
                        [fPL].[ProductStatusID],
                        [fPL].[ProductStatusName],
                        [fPL].[ProductAdditionalInfo1],
                        [fPL].[ProductAdditionalInfo2],
                        [fPL].[ProductAdditionalInfo3],
                        [fPL].[ProductAdditionalInfo4],
                        [fPL].[ProductAdditionalInfo5],
                        [fPL].[ProductAdditionalInfo6],
                        [fPL].[ProductAdditionalInfo7],
                        [fPL].[ProductAdditionalInfo8],
                        [fPL].[ProductAdditionalInfo9],
                        [fPL].[ProductAdditionalInfo10],
                        [fPL].[Code] [ProductLotCode],
                        [fPL].[ExpiredDate] [ProductLotExpiredDate],
                        [fPL].[ProductLot] [ProductLot],
                        [fPL].[StatusID] [ProductLotStatusID],
                        [fPL].[StatusName] [ProductLotStatusName],
                        [fPL].[IsDeleted] [IsProductLotCodeDeleted]
                    FROM            
                        [dbo].[fStockOnHandCalc]
                        (
                            @WarehouseID,
                            @TransactionDate,
                            @ProductID,
                            @ProductLotID,
                            @WarehouseCode,
                            @WarehouseName,
                            @SiteID,
                            @SiteCode,
                            @SiteName,
                            @AreaID,
                            @AreaCode,
                            @AreaName,
                            @RegionID,
                            @RegionCode,
                            @RegionName,
                            @TerritoryID,
                            @TerritoryCode,
                            @TerritoryName,
                            @CompanyID,
                            @CompanyCode,
                            @CompanyName,
                            @SiteDistributionTypeID,
                            @IsSiteLotNumberEntryRequired,
                            @WarehouseTypeID,
                            @IsWarehouseSOAllowed,
                            @WarehouseStatusID,
                            @IsWarehouseDeleted,
                            @ProductCode,
                            @ProductName,
                            @ProductBrandID,
                            @ProductBrandCode,
                            @ProductBrandName,
                            @ProductShortName,
                            @ProductStatusID,
                            @ProductAdditionalInfo,
                            @ProductLotCode,
                            @ProductLotExpiredDateFrom,
                            @ProductLotExpiredDateTo,
                            @ProductLotStatusID,
                            @IsProductLotDeleted
                        ) [fSOHC] INNER JOIN
                        [dbo].[fProductLot]
                        (
                            @ProductLotID,
                            @ProductLotCode,
                            @ProductID,
                            @ProductCode,
                            @ProductName,
                            @ProductBrandID,
                            @ProductBrandCode,
                            @ProductBrandName,
                            @ProductShortName,
                            @ProductStatusID,
                            @ProductAdditionalInfo,
                            @ProductLotExpiredDateFrom,
                            @ProductLotExpiredDateTo,                
                            @ProductLotStatusID,
                            @IsProductLotDeleted
                        ) [fPL] ON
                        (
                            [fSOHC].[ProductID] = [fPL].[ProductID] AND
                            [fSOHC].[ProductLotID] = [fPL].[ID]
                        )
    
    RETURN;
END
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vStockOnHandAvailable]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vStockOnHandAvailable];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 22:02:32
-- Description   : Provide view (model) to retrieve [dbo].[fStockOnHandAvailable] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vStockOnHandAvailable]
AS
(
    SELECT
            [WarehouseID],
            [ProductID],
            [ProductLotID],
            [QtyPeriodOnHandGood],
            [QtyPeriodOnHandHold],
            [QtyPeriodOnHandBad],
            [QtyTransactionGood],
            [QtyTransactionHold],
            [QtyTransactionBad],
            [QtyOnHandGood],
            [QtyOnHandHold],
            [QtyOnHandBad],
            [ProductCode],
            [ProductName],
            [Product],
            [ProductBrandID],
            [ProductBrandCode],
            [ProductBrandName],
            [ProductBrand],
            [ProductShortName],
            [ProductUOMLID],
            [ProductUOMMID],
            [ProductUOMSID],
            [ProductUOMLName],
            [ProductUOMMName],
            [ProductUOMSName],
            [ProductWeight],
            [ProductDimensionL],
            [ProductDimensionW],
            [ProductDimensionH],
            [ProductConversionL],
            [ProductConversionM],
            [ProductConversionS],
            [ProductStatusID],
            [ProductStatusName],
            [ProductAdditionalInfo1],
            [ProductAdditionalInfo2],
            [ProductAdditionalInfo3],
            [ProductAdditionalInfo4],
            [ProductAdditionalInfo5],
            [ProductAdditionalInfo6],
            [ProductAdditionalInfo7],
            [ProductAdditionalInfo8],
            [ProductAdditionalInfo9],
            [ProductAdditionalInfo10],
            [ProductLotCode],
            [ProductLotExpiredDate],
            [ProductLot],
            [ProductLotStatusID],
            [ProductLotStatusName],
            [IsProductLotCodeDeleted]
        FROM
			[dbo].[fStockOnHandAvailable]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
