USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fStockTransferDetails]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fStockTransferDetails];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 22:14:40
-- Description   : Provide function to retrieve [dbo].[StockTransferDetails] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fStockTransferDetails]
(
    @DocumentID uniqueidentifier,
    @ProductID int,
    @ProductLotID int,
    @ProductCode nvarchar(10),
    @ProductName nvarchar(50),
    @ProductBrandID int,
    @ProductBrandCode nvarchar(10),
    @ProductBrandName nvarchar(50),    
    @ProductShortName nvarchar(30),
    @ProductStatusID int,
    @ProductAdditionalInfo nvarchar(100),
    @ProductLotCode nvarchar(20),
    @ProductLotExpiredDateFrom datetime,
    @ProductLotExpiredDateTo datetime,    
    @ProductLotStatusID int    
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [STD].[DocumentID],
            [STD].[ProductID],
            [STD].[ProductLotID],
            [fPL].[ProductCode],
            [fPL].[ProductName],
            [fPL].[Product],
            [fPL].[ProductBrandID],
            [fPL].[ProductBrandCode],
            [fPL].[ProductBrandName],
            [fPL].[ProductBrand],
            [fPL].[ProductShortName],
            [fPL].[ProductUOMLID],
            [fPL].[ProductUOMMID],
            [fPL].[ProductUOMSID],
            [fPL].[ProductUOMLName],
            [fPL].[ProductUOMMName],
            [fPL].[ProductUOMSName],
            [fPL].[ProductWeight],
            [fPL].[ProductDimensionL],
            [fPL].[ProductDimensionW],
            [fPL].[ProductDimensionH],
            [fPL].[ProductConversionL],
            [fPL].[ProductConversionM],
            [fPL].[ProductConversionS],
            [fPL].[ProductStatusID],
            [fPL].[ProductStatusName],
            [fPL].[ProductAdditionalInfo1],
            [fPL].[ProductAdditionalInfo2],
            [fPL].[ProductAdditionalInfo3],
            [fPL].[ProductAdditionalInfo4],
            [fPL].[ProductAdditionalInfo5],
            [fPL].[ProductAdditionalInfo6],
            [fPL].[ProductAdditionalInfo7],
            [fPL].[ProductAdditionalInfo8],
            [fPL].[ProductAdditionalInfo9],
            [fPL].[ProductAdditionalInfo10],
            [fPL].[Code] [ProductLotCode],
            [fPL].[ExpiredDate] [ProductLotExpiredDate],
            [fPL].[StatusID] [ProductLotStatusID],
            [fPL].[StatusName] [ProductLotStatusName],
            (SELECT CASE WHEN [ST].[DocumentStatusID] = 1 THEN ISNULL([fSOHA].[QtyOnHandGood], 0) ELSE [STD].[QtyOnHandGood] END) [QtyOnHandGood],
            (SELECT CASE WHEN [ST].[DocumentStatusID] = 1 THEN ISNULL([fSOHA].[QtyOnHandHold], 0) ELSE [STD].[QtyOnHandHold] END) [QtyOnHandHold],
            (SELECT CASE WHEN [ST].[DocumentStatusID] = 1 THEN ISNULL([fSOHA].[QtyOnHandBad], 0) ELSE [STD].[QtyOnHandBad] END) [QtyOnHandBad],                       
            [STD].[QtyConvLGood],
            [STD].[QtyConvMGood],
            [STD].[QtyConvSGood],
            [STD].[QtyConvLHold],
            [STD].[QtyConvMHold],
            [STD].[QtyConvSHold],
            [STD].[QtyConvLBad],
            [STD].[QtyConvMBad],
            [STD].[QtyConvSBad],
            [STD].[QtyGood],
            [STD].[QtyHold],
            [STD].[QtyBad],
            (CAST([STD].[QtyConvLGood] AS nvarchar(10)) + '/' +  CAST([STD].[QtyConvMGood] AS nvarchar(10)) + '/' + CAST([STD].[QtyConvSGood] AS nvarchar(10))) [QtyTransferConvGood],
            (CAST([STD].[QtyConvLHold] AS nvarchar(10)) + '/' + CAST([STD].[QtyConvMHold] AS nvarchar(10)) + '/' + CAST([STD].[QtyConvSHold] AS nvarchar(10))) [QtyTransferConvHold],
            (CAST([STD].[QtyConvLBad] AS nvarchar(10)) + '/' + CAST([STD].[QtyConvMBad] AS nvarchar(10)) + '/' + CAST([STD].[QtyConvSBad] AS nvarchar(10))) [QtyTransferConvBad],            
            ([STD].[QtyGood] * -1) [QtyTransferGood],
            ([STD].[QtyHold] * -1) [QtyTransferHold],
            ([STD].[QtyBad] * -1) [QtyTransferBad]
        FROM
			[dbo].[StockTransferDetails] [STD] INNER JOIN
            [dbo].[StockTransfer] [ST] ON ([STD].[DocumentID] = [ST].[DocumentID]) LEFT OUTER JOIN
            [dbo].[fStockOnHandAvailable]
            (
                NULL,
                NULL,
                @ProductID,
                @ProductLotID,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                @ProductCode,
                @ProductName,
                @ProductBrandID,
                @ProductBrandCode,
                @ProductBrandName,
                @ProductShortName,
                @ProductStatusID,
                @ProductAdditionalInfo,
                @ProductLotCode,
                @ProductLotExpiredDateFrom,
                @ProductLotExpiredDateTo,
                @ProductLotStatusID,
                NULL
            ) [fSOHA] ON
            (
                [ST].[DocumentStatusID] = 1 AND
                [ST].[SourceWarehouseID] = [fSOHA].[WarehouseID] AND
                [STD].[ProductID] = [fSOHA].[ProductID] AND
                [STD].[ProductLotID] = [fSOHA].[ProductLotID]
            ) INNER JOIN
            [dbo].[fProductLot]
            (
                @ProductLotID,
                @ProductLotCode,
                @ProductID,
                @ProductCode,
                @ProductName,
                @ProductBrandID,
                @ProductBrandCode,
                @ProductBrandName,            
                @ProductShortName,            
                @ProductStatusID,
                @ProductAdditionalInfo,
                @ProductLotExpiredDateFrom,
                @ProductLotExpiredDateTo,
                @ProductLotStatusID,
                NULL
            ) [fPL] ON ([STD].[ProductLotID] = [fPL].[ID])
		WHERE
            ((@DocumentID IS NULL) OR ([STD].[DocumentID] = @DocumentID)) AND
            ((@ProductID IS NULL) OR ([STD].[ProductID] = @ProductID)) AND
            ((@ProductLotID IS NULL) OR ([STD].[ProductLotID] = @ProductLotID))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vStockTransferDetails]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vStockTransferDetails];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 22:14:40
-- Description   : Provide view (model) to retrieve [dbo].[fStockTransferDetails] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vStockTransferDetails]
AS
(
    SELECT
            [DocumentID],
            [ProductID],
            [ProductLotID],
            [ProductCode],
            [ProductName],
            [Product],
            [ProductBrandID],
            [ProductBrandCode],
            [ProductBrandName],
            [ProductBrand],
            [ProductShortName],
            [ProductUOMLID],
            [ProductUOMMID],
            [ProductUOMSID],
            [ProductUOMLName],
            [ProductUOMMName],
            [ProductUOMSName],
            [ProductWeight],
            [ProductDimensionL],
            [ProductDimensionW],
            [ProductDimensionH],
            [ProductConversionL],
            [ProductConversionM],
            [ProductConversionS],
            [ProductStatusID],
            [ProductStatusName],
            [ProductAdditionalInfo1],
            [ProductAdditionalInfo2],
            [ProductAdditionalInfo3],
            [ProductAdditionalInfo4],
            [ProductAdditionalInfo5],
            [ProductAdditionalInfo6],
            [ProductAdditionalInfo7],
            [ProductAdditionalInfo8],
            [ProductAdditionalInfo9],
            [ProductAdditionalInfo10],
            [ProductLotCode],
            [ProductLotExpiredDate],
            [ProductLotStatusID],
            [ProductLotStatusName],            
            [QtyOnHandGood],
            [QtyOnHandHold],
            [QtyOnHandBad],            
            [QtyConvLGood],
            [QtyConvMGood],
            [QtyConvSGood],
            [QtyConvLHold],
            [QtyConvMHold],
            [QtyConvSHold],
            [QtyConvLBad],
            [QtyConvMBad],
            [QtyConvSBad],
            [QtyGood],
            [QtyHold],
            [QtyBad],
            [QtyTransferConvGood],
            [QtyTransferConvHold],
            [QtyTransferConvBad],
            [QtyTransferGood],
            [QtyTransferHold],
            [QtyTransferBad]
        FROM
			[dbo].[fStockTransferDetails]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
