USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fStockTransactionSummary]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fStockTransactionSummary];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide function to retrieve summary of
--                 [dbo].[StockTransactionSummary] data.
-- ===================================================================================

CREATE FUNCTION [dbo].[fStockTransactionSummary]
(
    @DocumentID uniqueidentifier,
    @ProductID int,
    @ProductLotID int,
    @TransactionDateFrom datetime,
    @TransactionDateTo datetime,
    @TransactionTypeID int,
    @DocumentCode nvarchar(30),
    @SourceID uniqueidentifier,
    @DestinationID uniqueidentifier
)
RETURNS TABLE 
AS
RETURN 
(
    (
        SELECT
                [WarehouseID],
                [ProductID],
                [ProductLotID],
                SUM([QtyGood]) [SumQtyGood],
                SUM([QtyHold]) [SumQtyHold],
                SUM([QtyBad]) [SumQtyBad]
            FROM
            (
                SELECT
                        (
                            SELECT CASE
                                WHEN
                                    ([TransactionTypeID] = 2) OR  -- Sales Order Return
                                    ([TransactionTypeID] = 8)     -- Stock Transfer
                                THEN
                                    [DestinationID]
                                ELSE
                                    [SourceID]
                            END
                        ) [WarehouseID],
                        [ProductID],
                        [ProductLotID],
                        [QtyGood],
                        [QtyHold],
                        [QtyBad]
                    FROM
			            [dbo].[StockTransaction]
                    WHERE
                    ((@DocumentID IS NULL) OR ([DocumentID] = @DocumentID)) AND
                    ((@ProductID IS NULL) OR ([ProductID] = @ProductID)) AND
                    ((@ProductLotID IS NULL) OR ([ProductLotID] = @ProductLotID)) AND
                    ((@TransactionDateFrom IS NULL) OR ([TransactionDate] >= [dbo].[ValidateMinDate](@TransactionDateFrom))) AND
                    ((@TransactionDateTo IS NULL) OR ([TransactionDate] <= [dbo].[ValidateMaxDate](@TransactionDateTo))) AND
                    ((@DocumentCode IS NULL) OR ([DocumentCode] LIKE '%' + @DocumentCode + '%')) AND
                    (
                        ((@SourceID IS NULL) OR ([SourceID] = @SourceID)) OR
                        ((@DestinationID IS NULL) OR ([DestinationID] = @DestinationID))
                    )                            
            ) [svST]
            GROUP BY
                [WarehouseID],
                [ProductID],
                [ProductLotID]
    )
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vStockTransactionSummary]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vStockTransactionSummary];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide view (model) to retrieve [dbo].[fStockTransactionSummary] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vStockTransactionSummary]
AS
(
    SELECT
            [WarehouseID],
            [ProductID],
            [ProductLotID],
            [SumQtyGood],
            [SumQtyHold],
            [SumQtyBad]
        FROM
			[dbo].[fStockTransactionSummary]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL                
            )
);
GO
