USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fStockOnHandAll]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fStockOnHandAll];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:11:40
-- Description   : Provide function to retrieve [dbo].[StockOnHandAll] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fStockOnHandAll]
(    
    @WarehouseID uniqueidentifier,
    @TransactionDate datetime,
    @ProductID int,
    @ProductLotID int,
    @WarehouseCode nvarchar(10),
    @WarehouseName nvarchar(50),
    @SiteID uniqueidentifier,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @SiteDistributionTypeID int,
    @IsSiteLotNumberEntryRequired bit,
    @WarehouseTypeID int,
    @IsWarehouseSOAllowed bit,
    @WarehouseStatusID int,
    @IsWarehouseDeleted bit,
    @ProductCode nvarchar(10),
    @ProductName nvarchar(50),
    @ProductBrandID int,
    @ProductBrandCode nvarchar(10),
    @ProductBrandName nvarchar(50),
    @ProductShortName nvarchar(30),
    @ProductStatusID int,
    @ProductAdditionalInfo nvarchar(100),
    @ProductLotCode nvarchar(20),
    @ProductLotExpiredDateFrom datetime,
    @ProductLotExpiredDateTo datetime,
    @ProductLotStatusID int,
    @IsProductLotDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
    SELECT
            [vWPL].[WarehouseID],
            [vWPL].[ProductID],
            [vWPL].[ProductLotID],
            ISNULL([fSOHA].[QtyPeriodOnHandGood], 0) [QtyPeriodOnHandGood],
            ISNULL([fSOHA].[QtyPeriodOnHandHold], 0) [QtyPeriodOnHandHold],
            ISNULL([fSOHA].[QtyPeriodOnHandBad], 0) [QtyPeriodOnHandBad],
            ISNULL([fSOHA].[QtyTransactionGood], 0) [QtyTransactionGood],
            ISNULL([fSOHA].[QtyTransactionHold], 0) [QtyTransactionHold],
            ISNULL([fSOHA].[QtyTransactionBad], 0) [QtyTransactionBad],
            ISNULL([fSOHA].[QtyPeriodOnHandGood], 0) + ISNULL([fSOHA].[QtyTransactionGood], 0) [QtyOnHandGood],
            ISNULL([fSOHA].[QtyPeriodOnHandHold], 0) + ISNULL([fSOHA].[QtyTransactionHold], 0) [QtyOnHandHold],
            ISNULL([fSOHA].[QtyPeriodOnHandBad], 0) + ISNULL([fSOHA].[QtyTransactionBad], 0) [QtyOnHandBad],
            [vWPL].[ProductCode],
            [vWPL].[ProductName],
            [vWPL].[Product],
            [vWPL].[ProductBrandID],
            [vWPL].[ProductBrandCode],
            [vWPL].[ProductBrandName],
            [vWPL].[ProductBrand],
            [vWPL].[ProductShortName],
            [vWPL].[ProductUOMLID],
            [vWPL].[ProductUOMMID],
            [vWPL].[ProductUOMSID],
            [vWPL].[ProductUOMLName],
            [vWPL].[ProductUOMMName],
            [vWPL].[ProductUOMSName],
            [vWPL].[ProductWeight],
            [vWPL].[ProductDimensionL],
            [vWPL].[ProductDimensionW],
            [vWPL].[ProductDimensionH],
            [vWPL].[ProductConversionL],
            [vWPL].[ProductConversionM],
            [vWPL].[ProductConversionS],
            [vWPL].[ProductStatusID],
            [vWPL].[ProductStatusName],
            [vWPL].[ProductAdditionalInfo1],
            [vWPL].[ProductAdditionalInfo2],
            [vWPL].[ProductAdditionalInfo3],
            [vWPL].[ProductAdditionalInfo4],
            [vWPL].[ProductAdditionalInfo5],
            [vWPL].[ProductAdditionalInfo6],
            [vWPL].[ProductAdditionalInfo7],
            [vWPL].[ProductAdditionalInfo8],
            [vWPL].[ProductAdditionalInfo9],
            [vWPL].[ProductAdditionalInfo10],
            [vWPL].[ProductLotCode],
            [vWPL].[ProductLotExpiredDate],
            [vWPL].[ProductLot],
            [vWPL].[ProductLotStatusID],
            [vWPL].[ProductLotStatusName],
            [vWPL].[IsProductLotCodeDeleted]
        FROM
            (
                SELECT
                        [fW].[ID] [WarehouseID],
                        [fW].[Code] [WarehouseCode],
                        [fW].[Name] [WarehouseName],
                        [fW].[Warehouse],
                        [fW].[SiteID],
                        [fW].[SiteCode],
                        [fW].[SiteName],
                        [fW].[Site],
                        [fW].[AreaID],
                        [fW].[AreaCode],
                        [fW].[AreaName],
                        [fW].[Area],
                        [fW].[RegionID],
                        [fW].[RegionCode],
                        [fW].[RegionName],
                        [fW].[Region],
                        [fW].[TerritoryID],
                        [fW].[TerritoryCode],
                        [fW].[TerritoryName],
                        [fW].[Territory],
                        [fW].[CompanyID],
                        [fW].[CompanyCode],
                        [fW].[CompanyName],
                        [fW].[Company],
                        [fW].[SiteDistributionTypeID],
                        [fW].[SiteDistributionTypeName],
                        [fW].[IsSiteLotNumberEntryRequired],
                        [fW].[TypeID] [WarehouseTypeID],
                        [fW].[TypeName] [WarehouseTypeName],
                        [fW].[StatusID] [WarehouseStatusID],
                        [fW].[StatusName] [WarehouseStatusName],
                        [fW].[IsDeleted] [IsWarehouseDeleted],
                        [fPL].[ProductID],
                        [fPL].[ID] [ProductLotID],
                        [fPL].[ProductCode],
                        [fPL].[ProductName],
                        [fPL].[Product],
                        [fPL].[ProductBrandID],
                        [fPL].[ProductBrandCode],
                        [fPL].[ProductBrandName],
                        [fPL].[ProductBrand],
                        [fPL].[ProductShortName],
                        [fPL].[ProductUOMLID],
                        [fPL].[ProductUOMMID],
                        [fPL].[ProductUOMSID],
                        [fPL].[ProductUOMLName],
                        [fPL].[ProductUOMMName],
                        [fPL].[ProductUOMSName],
                        [fPL].[ProductWeight],
                        [fPL].[ProductDimensionL],
                        [fPL].[ProductDimensionW],
                        [fPL].[ProductDimensionH],
                        [fPL].[ProductConversionL],
                        [fPL].[ProductConversionM],
                        [fPL].[ProductConversionS],
                        [fPL].[ProductStatusID],
                        [fPL].[ProductStatusName],
                        [fPL].[ProductAdditionalInfo1],
                        [fPL].[ProductAdditionalInfo2],
                        [fPL].[ProductAdditionalInfo3],
                        [fPL].[ProductAdditionalInfo4],
                        [fPL].[ProductAdditionalInfo5],
                        [fPL].[ProductAdditionalInfo6],
                        [fPL].[ProductAdditionalInfo7],
                        [fPL].[ProductAdditionalInfo8],
                        [fPL].[ProductAdditionalInfo9],
                        [fPL].[ProductAdditionalInfo10],
                        [fPL].[Code] [ProductLotCode],
                        [fPL].[ExpiredDate] [ProductLotExpiredDate],
                        [fPL].[ProductLot] [ProductLot],
                        [fPL].[StatusID] [ProductLotStatusID],
                        [fPL].[StatusName] [ProductLotStatusName],
                        [fPL].[IsDeleted] [IsProductLotCodeDeleted]
                    FROM
                        [dbo].[fWarehouse]
                        (
                            @WarehouseID,
                            @WarehouseCode,
                            @WarehouseName,
                            @SiteID,
                            @SiteCode,
                            @SiteName,
                            @AreaID,
                            @AreaCode,
                            @AreaName,
                            @RegionID,
                            @RegionCode,
                            @RegionName,
                            @TerritoryID,
                            @TerritoryCode,
                            @TerritoryName,
                            @CompanyID,
                            @CompanyCode,
                            @CompanyName,
                            @SiteDistributionTypeID,
                            @IsSiteLotNumberEntryRequired,
                            @WarehouseTypeID,
                            @IsWarehouseSOAllowed,
                            @WarehouseStatusID,
                            @IsWarehouseDeleted
                        ) [fW],
                        [dbo].[fProductLot]
                        (
                            @ProductLotID,
                            @ProductLotCode,
                            @ProductID,
                            @ProductCode,
                            @ProductName,
                            @ProductBrandID,
                            @ProductBrandCode,
                            @ProductBrandName,
                            @ProductShortName,                        
                            @ProductStatusID,
                            @ProductAdditionalInfo,
                            @ProductLotExpiredDateFrom,
                            @ProductLotExpiredDateTo,
                            @ProductLotStatusID,
                            @IsProductLotDeleted
                        ) [fPL]
            ) [vWPL] LEFT OUTER JOIN
            [dbo].[fStockOnHandAvailable]
            (
                @WarehouseID,
                @TransactionDate,
                @ProductID,
                @ProductLotID,
                @WarehouseCode,
                @WarehouseName,
                @SiteID,
                @SiteCode,
                @SiteName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @SiteDistributionTypeID,
                @IsSiteLotNumberEntryRequired,
                @WarehouseTypeID,
                @IsWarehouseSOAllowed,
                @WarehouseStatusID,
                @IsWarehouseDeleted,
                @ProductCode,
                @ProductName,
                @ProductBrandID,
                @ProductBrandCode,
                @ProductBrandName,
                @ProductShortName,
                @ProductStatusID,
                @ProductAdditionalInfo,
                @ProductLotCode,
                @ProductLotExpiredDateFrom,
                @ProductLotExpiredDateTo,    
                @ProductLotStatusID,
                @IsProductLotDeleted
            ) [fSOHA] ON
            (
                [vWPL].[WarehouseID] = [fSOHA].[WarehouseID] AND
                [vWPL].[ProductID] = [fSOHA].[ProductID] AND
                [vWPL].[ProductLotID] = [fSOHA].[ProductLotID]
            )
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vStockOnHandAll]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vStockOnHandAll];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 22:02:32
-- Description   : Provide view (model) to retrieve [dbo].[fStockOnHandAll] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vStockOnHandAll]
AS
(
    SELECT
            [WarehouseID],
            [ProductID],
            [ProductLotID],
            [QtyPeriodOnHandGood],
            [QtyPeriodOnHandHold],
            [QtyPeriodOnHandBad],
            [QtyTransactionGood],
            [QtyTransactionHold],
            [QtyTransactionBad],
            [QtyOnHandGood],
            [QtyOnHandHold],
            [QtyOnHandBad],
            [ProductCode],
            [ProductName],
            [Product],
            [ProductBrandID],
            [ProductBrandCode],
            [ProductBrandName],
            [ProductBrand],
            [ProductShortName],
            [ProductUOMLID],
            [ProductUOMMID],
            [ProductUOMSID],
            [ProductUOMLName],
            [ProductUOMMName],
            [ProductUOMSName],
            [ProductWeight],
            [ProductDimensionL],
            [ProductDimensionW],
            [ProductDimensionH],
            [ProductConversionL],
            [ProductConversionM],
            [ProductConversionS],
            [ProductStatusID],
            [ProductStatusName],
            [ProductAdditionalInfo1],
            [ProductAdditionalInfo2],
            [ProductAdditionalInfo3],
            [ProductAdditionalInfo4],
            [ProductAdditionalInfo5],
            [ProductAdditionalInfo6],
            [ProductAdditionalInfo7],
            [ProductAdditionalInfo8],
            [ProductAdditionalInfo9],
            [ProductAdditionalInfo10],
            [ProductLotCode],
            [ProductLotExpiredDate],
            [ProductLot],
            [ProductLotStatusID],
            [ProductLotStatusName],
            [IsProductLotCodeDeleted]
        FROM
			[dbo].[fStockOnHandAll]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
