USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fStockTransferSummary]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fStockTransferSummary];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide function to retrieve [dbo].[StockTransferSummary] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fStockTransferSummary]
(
    @DocumentID uniqueidentifier,
    @ProductID int,
    @ProductCode nvarchar(10),
    @ProductName nvarchar(50),
    @ProductBrandID int,
    @ProductBrandCode nvarchar(10),
    @ProductBrandName nvarchar(50),
    @ProductShortName nvarchar(30),
    @ProductStatusID int,
    @ProductAdditionalInfo nvarchar(100)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [STS].[DocumentID],            
            [STS].[ProductID],
            [fP].[Code] [ProductCode],
            [fP].[Name] [ProductName],
            [fP].[Product],
            [fP].[BrandID] [ProductBrandID],
            [fP].[BrandCode] [ProductBrandCode],
            [fP].[BrandName] [ProductBrandName],
            [fP].[Brand] [ProductBrand],
            [fP].[ShortName] [ProductShortName],
            [fP].[UOMLID] [ProductUOMLID],
            [fP].[UOMMID] [ProductUOMMID],
            [fP].[UOMSID] [ProductUOMSID],
            [fP].[UOMLName] [ProductUOMLName],
            [fP].[UOMMName] [ProductUOMMName],
            [fP].[UOMSName] [ProductUOMSName],
            [fP].[Weight] [ProductWeight],
            [fP].[DimensionL] [ProductDimensionL],
            [fP].[DimensionW] [ProductDimensionW],
            [fP].[DimensionH] [ProductDimensionH],
            [fP].[ConversionL] [ProductConversionL],
            [fP].[ConversionM] [ProductConversionM],
            [fP].[ConversionS] [ProductConversionS],
            [fP].[StatusID] [ProductStatusID],
            [fP].[StatusName] [ProductStatusName],
            [fP].[AdditionalInfo1] [ProductAdditionalInfo1],
            [fP].[AdditionalInfo2] [ProductAdditionalInfo2],
            [fP].[AdditionalInfo3] [ProductAdditionalInfo3],
            [fP].[AdditionalInfo4] [ProductAdditionalInfo4],
            [fP].[AdditionalInfo5] [ProductAdditionalInfo5],
            [fP].[AdditionalInfo6] [ProductAdditionalInfo6],
            [fP].[AdditionalInfo7] [ProductAdditionalInfo7],
            [fP].[AdditionalInfo8] [ProductAdditionalInfo8],
            [fP].[AdditionalInfo9] [ProductAdditionalInfo9],
            [fP].[AdditionalInfo10] [ProductAdditionalInfo10],
            (SELECT CASE WHEN [ST].[DocumentStatusID] = 1 THEN ISNULL([SOHA].[QtyOnHandGood], 0) ELSE [STS].[QtyOnHandGood] END) [QtyOnHandGood],
            (SELECT CASE WHEN [ST].[DocumentStatusID] = 1 THEN ISNULL([SOHA].[QtyOnHandHold], 0) ELSE [STS].[QtyOnHandHold] END) [QtyOnHandHold],
            (SELECT CASE WHEN [ST].[DocumentStatusID] = 1 THEN ISNULL([SOHA].[QtyOnHandBad], 0) ELSE [STS].[QtyOnHandBad] END) [QtyOnHandBad],
            [STS].[QtyConvLGood],
            [STS].[QtyConvMGood],
            [STS].[QtyConvSGood],
            [STS].[QtyConvLHold],
            [STS].[QtyConvMHold],
            [STS].[QtyConvSHold],
            [STS].[QtyConvLBad],
            [STS].[QtyConvMBad],
            [STS].[QtyConvSBad],
            [STS].[QtyGood],
            [STS].[QtyHold],
            [STS].[QtyBad],
            (CAST([STS].[QtyConvLGood] AS nvarchar(10)) + '/' +  CAST([STS].[QtyConvMGood] AS nvarchar(10)) + '/' + CAST([STS].[QtyConvSGood] AS nvarchar(10))) [QtyTransferConvGood],
            (CAST([STS].[QtyConvLHold] AS nvarchar(10)) + '/' + CAST([STS].[QtyConvMHold] AS nvarchar(10)) + '/' + CAST([STS].[QtyConvSHold] AS nvarchar(10))) [QtyTransferConvHold],
            (CAST([STS].[QtyConvLBad] AS nvarchar(10)) + '/' + CAST([STS].[QtyConvMBad] AS nvarchar(10)) + '/' + CAST([STS].[QtyConvSBad] AS nvarchar(10))) [QtyTransferConvBad],
            ([STS].[QtyGood] * -1) [QtyTransferGood],
            ([STS].[QtyHold] * -1) [QtyTransferHold],
            ([STS].[QtyBad] * -1) [QtyTransferBad]
        FROM
			[dbo].[StockTransferSummary] [STS] INNER JOIN
            [dbo].[StockTransfer] [ST] ON ([STS].[DocumentID] = [ST].[DocumentID]) LEFT OUTER JOIN
            (
                SELECT
                        [fSOHA].[WarehouseID],
                        [fSOHA].[ProductID],
                        SUM([fSOHA].[QtyOnHandGood]) [QtyOnHandGood],
                        SUM([fSOHA].[QtyOnHandHold]) [QtyOnHandHold],
                        SUM([fSOHA].[QtyOnHandBad]) [QtyOnHandBad]
                    FROM
                        [dbo].[fStockOnHandAvailable]
                        (
                            NULL,
                            NULL,
                            @ProductID,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            @ProductCode,
                            @ProductName,
                            @ProductBrandID,
                            @ProductBrandCode,
                            @ProductBrandName,
                            @ProductShortName,
                            @ProductStatusID,
                            @ProductAdditionalInfo,
                            NULL,
                            NULL,
                            NULL,
                            NULL,
                            NULL                
                        ) [fSOHA]
                    GROUP BY
                        [fSOHA].[WarehouseID],
                        [fSOHA].[ProductID]
            ) [SOHA] ON
            (
                [ST].[DocumentStatusID] = 1 AND
                [ST].[SourceWarehouseID] = [SOHA].[WarehouseID] AND
                [STS].[ProductID] = [SOHA].[ProductID]
            ) INNER JOIN
            [dbo].[fProduct]
            (
                @ProductID,
                @ProductCode,
                @ProductName,
                @ProductBrandID,
                @ProductBrandCode,
                @ProductBrandName,
                @ProductShortName,
                @ProductStatusID,
                @ProductAdditionalInfo,
                NULL
            ) [fP] ON ([STS].[ProductID] = [fP].[ID])
		WHERE
            ((@DocumentID IS NULL) OR ([STS].[DocumentID] = @DocumentID)) AND
            ((@ProductID IS NULL) OR ([STS].[ProductID] = @ProductID))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vStockTransferSummary]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vStockTransferSummary];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide view (model) to retrieve [dbo].[fStockTransferSummary] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vStockTransferSummary]
AS
(
    SELECT
            [DocumentID],
            [ProductID],
            [ProductCode],
            [ProductName],
            [Product],
            [ProductBrandID],
            [ProductBrandCode],
            [ProductBrandName],
            [ProductBrand],
            [ProductShortName],
            [ProductUOMLID],
            [ProductUOMMID],
            [ProductUOMSID],
            [ProductUOMLName],
            [ProductUOMMName],
            [ProductUOMSName],        
            [ProductWeight],
            [ProductDimensionL],
            [ProductDimensionW],
            [ProductDimensionH],
            [ProductConversionL],
            [ProductConversionM],
            [ProductConversionS],
            [ProductStatusID],
            [ProductStatusName],
            [ProductAdditionalInfo1],
            [ProductAdditionalInfo2],
            [ProductAdditionalInfo3],
            [ProductAdditionalInfo4],
            [ProductAdditionalInfo5],
            [ProductAdditionalInfo6],
            [ProductAdditionalInfo7],
            [ProductAdditionalInfo8],
            [ProductAdditionalInfo9],
            [ProductAdditionalInfo10],
            [QtyOnHandGood],
            [QtyOnHandHold],
            [QtyOnHandBad],
            [QtyConvLGood],
            [QtyConvMGood],
            [QtyConvSGood],
            [QtyConvLHold],
            [QtyConvMHold],
            [QtyConvSHold],
            [QtyConvLBad],
            [QtyConvMBad],
            [QtyConvSBad],
            [QtyGood],
            [QtyHold],
            [QtyBad],
            [QtyTransferConvGood],
            [QtyTransferConvHold],
            [QtyTransferConvBad],
            [QtyTransferGood],
            [QtyTransferHold],
            [QtyTransferBad]
        FROM
			[dbo].[fStockTransferSummary]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL                
            )
);
GO
