USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fStockTransfer]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fStockTransfer];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide function to retrieve [dbo].[StockTransfer] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fStockTransfer]
(
    @DocumentID uniqueidentifier,
    @DocumentCode nvarchar(30),
    @TransactionDateFrom datetime,
    @TransactionDateTo datetime,
    @SourceWarehouseID uniqueidentifier,
    @SourceWarehouseCode nvarchar(10),
    @SourceWarehouseName nvarchar(50),
    @SourceSiteID uniqueidentifier,
    @SourceSiteCode nvarchar(10),
    @SourceSiteName nvarchar(50),
    @SourceCompanyID int,
    @SourceCompanyCode nvarchar(10),
    @SourceCompanyName nvarchar(50),
    @SourceAreaID int,
    @SourceAreaCode nvarchar(10),
    @SourceAreaName nvarchar(50),
    @SourceRegionID int,
    @SourceRegionCode nvarchar(10),
    @SourceRegionName nvarchar(50),
    @SourceTerritoryID int,
    @SourceTerritoryCode nvarchar(10),
    @SourceTerritoryName nvarchar(50),    
    @SourceSiteDistributionTypeID int,
    @IsSourceSiteLotNumberEntryRequired bit,
    @SourceWarehouseTypeID int,
    @SourcePIC nvarchar(50),
    @DestinationWarehouseID uniqueidentifier,
    @DestinationWarehouseCode nvarchar(10),
    @DestinationWarehouseName nvarchar(50),
    @DestinationSiteID uniqueidentifier,
    @DestinationSiteCode nvarchar(10),
    @DestinationSiteName nvarchar(50),
    @DestinationCompanyID int,
    @DestinationCompanyCode nvarchar(10),
    @DestinationCompanyName nvarchar(50),
    @DestinationAreaID int,
    @DestinationAreaCode nvarchar(10),
    @DestinationAreaName nvarchar(50),
    @DestinationRegionID int,
    @DestinationRegionCode nvarchar(10),
    @DestinationRegionName nvarchar(50),
    @DestinationTerritoryID int,
    @DestinationTerritoryCode nvarchar(10),
    @DestinationTerritoryName nvarchar(50),    
    @DestinationSiteDistributionTypeID int,
    @DestinationWarehouseTypeID int,
    @IsDestinationSiteLotNumberEntryRequired bit,
    @DestinationPIC nvarchar(50),
    @ReferenceNumber nvarchar(30),
    @DODocumentID uniqueidentifier,
    @DODocumentCode nvarchar(30),
    @DOShipmentDateFrom datetime,
    @DOShipmentDateTo datetime,
    @DOReceivedDateFrom datetime,
    @DOReceivedDateTo datetime,
    @DOLastPrintedDateFrom datetime,
    @DOLastPrintedDateTo datetime,
    @DocumentStatusID int,
    @PostedDateFrom datetime,
    @PostedDateTo datetime
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [ST].[DocumentID],
            [ST].[DocumentCode],
            [ST].[TransactionDate],
            [ST].[SourceWarehouseID],
            [fWSrc].[Code] [SourceWarehouseCode],
            [fWSrc].[Name] [SourceWarehouseName],
            [fWSrc].[Warehouse] [SourceWarehouse],
            [fWSrc].[SiteID] [SourceSiteID],
            [fWSrc].[SiteCode] [SourceSiteCode],
            [fWSrc].[SiteName] [SourceSiteName],
            [fWSrc].[Site] [SourceSite],
            [fWSrc].[CompanyID] [SourceCompanyID],
            [fWSrc].[CompanyCode] [SourceCompanyCode],
            [fWSrc].[CompanyName] [SourceCompanyName],
            [fWSrc].[Company] [SourceCompany],
            [fWSrc].[AreaID] [SourceAreaID],
            [fWSrc].[AreaCode] [SourceAreaCode],
            [fWSrc].[AreaName] [SourceAreaName],
            [fWSrc].[Area] [SourceArea],
            [fWSrc].[RegionID] [SourceRegionID],
            [fWSrc].[RegionCode] [SourceRegionCode],
            [fWSrc].[RegionName] [SourceRegionName],
            [fWSrc].[Region] [SourceRegion],
            [fWSrc].[TerritoryID] [SourceTerritoryID],
            [fWSrc].[TerritoryCode] [SourceTerritoryCode],
            [fWSrc].[TerritoryName] [SourceTerritoryName],
            [fWSrc].[Territory] [SourceTerritory],
            [fWSrc].[SiteDistributionTypeID] [SourceSiteDistributionTypeID],
            [fWSrc].[SiteDistributionTypeName] [SourceSiteDistributionTypeName],
            [fWSrc].[IsSiteLotNumberEntryRequired] [IsSourceSiteLotNumberEntryRequired],
            [fWSrc].[TypeID] [SourceWarehouseTypeID],
            [fWSrc].[TypeName] [SourceWarehouseTypeName],
            [ST].[SourcePIC],
            [ST].[DestinationWarehouseID],
            [fWDest].[Code] [DestinationWarehouseCode],
            [fWDest].[Name] [DestinationWarehouseName],
            [fWDest].[Warehouse] [DestinationWarehouse],
            [fWDest].[SiteID] [DestinationSiteID],
            [fWDest].[SiteCode] [DestinationSiteCode],
            [fWDest].[SiteName] [DestinationSiteName],
            [fWDest].[Site] [DestinationSite],
            [fWDest].[CompanyID] [DestinationCompanyID],
            [fWDest].[CompanyCode] [DestinationCompanyCode],
            [fWDest].[CompanyName] [DestinationCompanyName],
            [fWDest].[Company] [DestinationCompany],
            [fWDest].[AreaID] [DestinationAreaID],
            [fWDest].[AreaCode] [DestinationAreaCode],
            [fWDest].[AreaName] [DestinationAreaName],
            [fWDest].[Area] [DestinationArea],
            [fWDest].[RegionID] [DestinationRegionID],
            [fWDest].[RegionCode] [DestinationRegionCode],
            [fWDest].[RegionName] [DestinationRegionName],
            [fWDest].[Region] [DestinationRegion],
            [fWDest].[TerritoryID] [DestinationTerritoryID],
            [fWDest].[TerritoryCode] [DestinationTerritoryCode],
            [fWDest].[TerritoryName] [DestinationTerritoryName],
            [fWDest].[Territory] [DestinationTerritory],
            [fWDest].[SiteDistributionTypeID] [DestinationSiteDistributionTypeID],
            [fWDest].[SiteDistributionTypeName] [DestinationSiteDistributionTypeName],
            [fWDest].[IsSiteLotNumberEntryRequired] [IsDestinationSiteLotNumberEntryRequired],
            [fWDest].[TypeID] [DestinationWarehouseTypeID],
            [fWDest].[TypeName] [DestinationWarehouseTypeName],
            [ST].[DestinationPIC],
            [ST].[ReferenceNumber],
            [ST].[AttachmentFile],
            [ST].[DODocumentID],
            [DO].[DocumentCode] [DODocumentCode],
            [DO].[ShipmentDate] [DOShipmentDate],
            [DO].[ReceivedDate] [DOReceivedDate],
            [DO].[PrintedCount] [DOPrintedCount],
            [DO].[LastPrintedDate] [DOLastPrintedDate],
            [ST].[DocumentStatusID],
            [fSL].[Name] [DocumentStatusName],
            [ST].[PrintCount],
            [ST].[PostedDate],
            [ST].[CreatedDate],
            [ST].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [ST].[ModifiedDate],
            [ST].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName]
        FROM
			[dbo].[StockTransfer] [ST] INNER JOIN
            [dbo].[fWarehouse]
            (
                @SourceWarehouseID,
                @SourceWarehouseCode,
                @SourceWarehouseName,
                @SourceSiteID,
                @SourceSiteCode,
                @SourceSiteName,
                @SourceAreaID,
                @SourceAreaCode,
                @SourceAreaName,
                @SourceRegionID,
                @SourceRegionCode,
                @SourceRegionName,
                @SourceTerritoryID,
                @SourceTerritoryCode,
                @SourceTerritoryName,
                @SourceCompanyID,
                @SourceCompanyCode,
                @SourceCompanyName,
                @SourceSiteDistributionTypeID,
                @IsSourceSiteLotNumberEntryRequired,
                @SourceWarehouseTypeID,
                NULL,
                NULL,
                NULL
            ) [fWSrc] ON ([ST].[SourceWarehouseID] = [fWSrc].[ID]) INNER JOIN
            [dbo].[fWarehouse]
            (
                @DestinationWarehouseID,
                @DestinationWarehouseCode,
                @DestinationWarehouseName,
                @DestinationSiteID,
                @DestinationSiteCode,
                @DestinationSiteName,
                @DestinationAreaID,
                @DestinationAreaCode,
                @DestinationAreaName,
                @DestinationRegionID,
                @DestinationRegionCode,
                @DestinationRegionName,
                @DestinationTerritoryID,
                @DestinationTerritoryCode,
                @DestinationTerritoryName,
                @DestinationCompanyID,
                @DestinationCompanyCode,
                @DestinationCompanyName,
                @DestinationSiteDistributionTypeID,
                @IsDestinationSiteLotNumberEntryRequired,
                @DestinationWarehouseTypeID,
                NULL,
                NULL,
                NULL
            ) [fWDest] ON ([ST].[DestinationWarehouseID] = [fWDest].[ID]) INNER JOIN
            [dbo].[DeliveryOrder] [DO] ON ([ST].[DODocumentID] = [DO].[DocumentID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'DocumentStatus',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([ST].[DocumentStatusID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([ST].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([ST].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@DocumentID IS NULL) OR ([ST].[DocumentID] = @DocumentID)) AND
            ((@DocumentCode IS NULL) OR ([ST].[DocumentCode] LIKE '%' + @DocumentCode + '%')) AND
            ((@TransactionDateFrom IS NULL) OR ([ST].[TransactionDate] >= [dbo].[ConvertToFirstTimeOfDay](@TransactionDateFrom))) AND
            ((@TransactionDateTo IS NULL) OR ([ST].[TransactionDate] <= [dbo].[ConvertToLastTimeOfDay](@TransactionDateTo))) AND
            ((@SourceWarehouseID IS NULL) OR ([ST].[SourceWarehouseID] = @SourceWarehouseID)) AND
            ((@SourcePIC IS NULL) OR ([ST].[SourcePIC] LIKE '%' + @SourcePIC + '%')) AND
            ((@DestinationWarehouseID IS NULL) OR ([ST].[DestinationWarehouseID] = @DestinationWarehouseID)) AND
            ((@DestinationPIC IS NULL) OR ([ST].[DestinationPIC] LIKE '%' + @DestinationPIC + '%')) AND
            ((@ReferenceNumber IS NULL) OR ([ST].[ReferenceNumber] LIKE '%' + @ReferenceNumber + '%')) AND
            ((@DODocumentID IS NULL) OR ([ST].[DODocumentID] = @DODocumentID)) AND            
            ((@DODocumentCode IS NULL) OR ([DO].[DocumentCode] LIKE '%' + @DODocumentCode + '%')) AND
            ((@DocumentStatusID IS NULL) OR ([ST].[DocumentStatusID] = @DocumentStatusID)) AND
            ((@PostedDateFrom IS NULL) OR ([dbo].[ValidateMaxDate]([ST].[PostedDate]) >= [dbo].[ValidateMinDate](@PostedDateFrom))) AND
            ((@PostedDateTo IS NULL) OR ([dbo].[ValidateMinDate]([ST].[PostedDate]) <= [dbo].[ValidateMaxDate](@PostedDateTo)))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vStockTransfer]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vStockTransfer];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 20 Mar 2016 23:32:11
-- Description   : Provide view (model) to retrieve [dbo].[fStockTransfer] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vStockTransfer]
AS
(
    SELECT
            [DocumentID],
            [DocumentCode],
            [TransactionDate],            
            [SourceWarehouseID],
            [SourceWarehouseCode],
            [SourceWarehouseName],
            [SourceWarehouse],
            [SourceSiteID],
            [SourceSiteCode],
            [SourceSiteName],
            [SourceSite],
            [SourceCompanyID],
            [SourceCompanyCode],
            [SourceCompanyName],
            [SourceCompany],
            [SourceAreaID],
            [SourceAreaCode],
            [SourceAreaName],
            [SourceArea],
            [SourceRegionID],
            [SourceRegionCode],
            [SourceRegionName],
            [SourceRegion],
            [SourceTerritoryID],
            [SourceTerritoryCode],
            [SourceTerritoryName],
            [SourceTerritory],
            [SourceSiteDistributionTypeID],
            [SourceSiteDistributionTypeName],
            [IsSourceSiteLotNumberEntryRequired],
            [SourceWarehouseTypeID],
            [SourceWarehouseTypeName],
            [SourcePIC],
            [DestinationWarehouseID],
            [DestinationWarehouseCode],
            [DestinationWarehouseName],
            [DestinationWarehouse],
            [DestinationSiteID],
            [DestinationSiteCode],
            [DestinationSiteName],
            [DestinationSite],
            [DestinationCompanyID],
            [DestinationCompanyCode],
            [DestinationCompanyName],
            [DestinationCompany],
            [DestinationAreaID],
            [DestinationAreaCode],
            [DestinationAreaName],
            [DestinationArea],
            [DestinationRegionID],
            [DestinationRegionCode],
            [DestinationRegionName],
            [DestinationRegion],
            [DestinationTerritoryID],
            [DestinationTerritoryCode],
            [DestinationTerritoryName],
            [DestinationTerritory],
            [DestinationSiteDistributionTypeID],
            [DestinationSiteDistributionTypeName],            
            [DestinationWarehouseTypeID],
            [DestinationWarehouseTypeName],
            [IsDestinationSiteLotNumberEntryRequired],
            [DestinationPIC],
            [ReferenceNumber],
            [AttachmentFile],
            [DODocumentID],
            [DODocumentCode],
            [DOShipmentDate],
            [DOReceivedDate],
            [DOPrintedCount],
            [DOLastPrintedDate],
            [DocumentStatusID],
            [DocumentStatusName],
            [PrintCount],
            [PostedDate],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName]
        FROM
			[dbo].[fStockTransfer]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL                
            )
);
GO
