USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fSystemLookup]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fSystemLookup];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 16 Mar 2016 10:55:43
-- Description   : Provide function to retrieve [dbo].[SystemLookup] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fSystemLookup]
(
    @ID int,
    @Name nvarchar(128),
    @Value_Boolean bit,
    @Value_Int32 int,
    @Value_Double float,
    @Value_String nvarchar(512),
    @Value_Guid uniqueidentifier,
    @Value_DateTime datetime2,
    @ParentID int,
    @Group nvarchar(128),
    @SortIndex int,
    @IsActive bit,
    @IsAuthorization bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [SL].[ID],
            [SL].[Name],
            [SL].[Value_Boolean],
            [SL].[Value_Int32],
            [SL].[Value_Double],
            [SL].[Value_String],
            [SL].[Value_Guid],
            [SL].[Value_DateTime],
            [SL].[ParentID],
            [SL].[Group],
            [SL].[SortIndex],
            [SL].[IsActive],
            [SL].[IsAuthorization],
            [SL].[CreatedDate],
            [SL].[ModifiedDate]
        FROM
			[dbo].[SystemLookup] [SL]
		WHERE
            ((@ID IS NULL) OR ([SL].[ID] = @ID)) AND
            ((@Name IS NULL) OR ([SL].[Name] LIKE '%' + @Name + '%')) AND
            ((@Value_Boolean IS NULL) OR ([SL].[Value_Boolean] = @Value_Boolean)) AND
            ((@Value_Int32 IS NULL) OR ([SL].[Value_Int32] = @Value_Int32)) AND
            ((@Value_Double IS NULL) OR ([SL].[Value_Double] = @Value_Double)) AND
            ((@Value_String IS NULL) OR ([SL].[Value_String] = @Value_String)) AND
            ((@Value_Guid IS NULL) OR ([SL].[Value_Guid] = @Value_Guid)) AND
            ((@Value_DateTime IS NULL) OR ([SL].[Value_DateTime] = @Value_DateTime)) AND
            ((@ParentID IS NULL) OR ([SL].[ParentID] = @ParentID)) AND
            ((@Group IS NULL) OR ([SL].[Group] = @Group)) AND
            ((@SortIndex IS NULL) OR ([SL].[SortIndex] = @SortIndex)) AND
            ((@IsActive IS NULL) OR ([SL].[IsActive] = @IsActive)) AND
            ((@IsAuthorization IS NULL) OR ([SL].[IsAuthorization] = @IsAuthorization))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vSystemLookup]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vSystemLookup];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 16 Mar 2016 10:55:43
-- Description   : Provide view (model) to retrieve [dbo].[fSystemLookup] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vSystemLookup]
AS
(
    SELECT
            [ID],
            [Name],
            [Value_Boolean],
            [Value_Int32],
            [Value_Double],
            [Value_String],
            [Value_Guid],
            [Value_DateTime],
            [ParentID],
            [Group],
            [SortIndex],
            [IsActive],
            [IsAuthorization],
            [CreatedDate],
            [ModifiedDate]
        FROM
			[dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
