USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fTerritory]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fTerritory];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:11:40
-- Description   : Provide function to retrieve [dbo].[Territory] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fTerritory]
(
    @ID int,
    @Code nvarchar(10),
    @Name nvarchar(50),
    @IsDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [T].[ID],
            [T].[Code],
            [T].[Name],
            [dbo].[fCodeNameFormatter]([T].[Code], [T].[Name]) [Territory],
            [T].[CreatedDate],
            [T].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [T].[ModifiedDate],
            [T].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [T].[IsDeleted]
        FROM
			[dbo].[Territory] [T] LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([T].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([T].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR ([T].[ID] = @ID)) AND
            ((@Code IS NULL) OR ([T].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([T].[Name] LIKE '%' + @Name + '%')) AND
            ((@IsDeleted IS NULL) OR ([T].[IsDeleted] = @IsDeleted))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vTerritory]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vTerritory];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:11:40
-- Description   : Provide view (model) to retrieve [dbo].[fTerritory] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vTerritory]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [Territory],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted]
        FROM
			[dbo].[fTerritory]
            (
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
