USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fUserNotification]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fUserNotification];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide function to retrieve [dbo].[UserNotification] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fUserNotification]
(
    @ID uniqueidentifier,
    @RaisedDateFrom datetime,
    @RaisedDateTo datetime,
    @UserID int,
    @UserName nvarchar(256),
    @CategoryID int,
    @HtmlMessage nvarchar(1024),
    @IsRead bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [UN].[ID],
            [UN].[RaisedDate],
            [UN].[UserID],
            [U].[Name] [UserName],
            [UN].[CategoryID],
            [fSL].[Name] [CategoryName],
            [UN].[HtmlMessage],
            [UN].[IsRead],
            '' [_]
        FROM
			[dbo].[UserNotification] [UN] INNER JOIN
            [dbo].[User] [U] ON ([UN].[UserID] = [U].[ID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'UserNotificationCategory',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([UN].[CategoryID] = [fSL].[Value_Int32])            
		WHERE
            ((@ID IS NULL) OR (@ID = [UN].[ID])) AND
            ((@RaisedDateFrom IS NULL) OR ([UN].[RaisedDate] >= [dbo].[ValidateMinDate](@RaisedDateFrom))) AND
            ((@RaisedDateTo IS NULL) OR ([UN].[RaisedDate] <= [dbo].[ValidateMaxDate](@RaisedDateTo))) AND
            ((@UserID IS NULL) OR ([UN].[UserID] = @UserID)) AND
            ((@UserName IS NULL) OR ([U].[Name] LIKE '%' + @UserName + '%')) AND            
            ((@CategoryID IS NULL) OR ([UN].[CategoryID] = @CategoryID)) AND
            ((@HtmlMessage IS NULL) OR ([UN].[HtmlMessage] LIKE '%' + @HtmlMessage + '%')) AND
            ((@IsRead IS NULL) OR ([UN].[IsRead] = @IsRead))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vUserNotification]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vUserNotification];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 17 Mar 2016 20:37:01
-- Description   : Provide view (model) to retrieve [dbo].[fUserNotification] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vUserNotification]
AS
(
    SELECT
            [ID],
            [RaisedDate],
            [UserID],
            [UserName],
            [CategoryID],
            [CategoryName],
            [HtmlMessage],
            [IsRead],
            [_]
        FROM
			[dbo].[fUserNotification]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL                
            )
);
GO
