USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fUserRoleAll]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fUserRoleAll];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 26 Jul 2016 22:40:06
-- Description   : Provide function to retrieve [dbo].[UserRole] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fUserRoleAll]
(
    @RoleID int,
    @UserID int,
    @RoleName nvarchar(256),
    @IsRoleDeleted bit,    
    @UserName nvarchar(256),
    @IsUserHeadOffice bit,
    @UserSiteID uniqueidentifier,
    @UserSiteCode nvarchar(10),
    @UserSiteName nvarchar(50),
    @UserAreaID int,
    @UserAreaCode nvarchar(10),
    @UserAreaName nvarchar(50),
    @UserRegionID int,
    @UserRegionCode nvarchar(10),
    @UserRegionName nvarchar(50),
    @UserTerritoryID int,
    @UserTerritoryCode nvarchar(10),
    @UserTerritoryName nvarchar(50),
    @UserCompanyID int,
    @UserCompanyCode nvarchar(10),
    @UserCompanyName nvarchar(50),
    @UserSiteDistributionTypeID int,
    @IsUserSiteLotNumberEntryRequired bit,
    @UserStatusID int,    
    @IsUserDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [R].[ID] [UserRoleID],
            CAST(0 AS bit) [IsUser],
            [R].[Name] [UserRoleName],
            CAST(0 AS bit) [IsUserHeadOffice],
            NULL [UserSiteID],
            NULL [UserSiteCode],
            NULL [UserSiteName],
            NULL [UserSite],
            NULL [UserAreaID],
            NULL [UserAreaCode],
            NULL [UserAreaName],
            NULL [UserArea],
            NULL [UserRegionID],
            NULL [UserRegionCode],
            NULL [UserRegionName],
            NULL [UserRegion],
            NULL [UserTerritoryID],
            NULL [UserTerritoryCode],
            NULL [UserTerritoryName],
            NULL [UserTerritory],
            NULL [UserCompanyID],
            NULL [UserCompanyCode],
            NULL [UserCompanyName],
            NULL [UserCompany],
            NULL [UserSiteDistributionTypeID],
            NULL [UserSiteDistributionTypeName],
            NULL [IsUserSiteLotNumberEntryRequired],            
            NULL [UserStatusID],
            NULL [UserStatusName],
            [R].[IsDeleted]
        FROM
			[dbo].[Role] [R]
		WHERE
            ((@RoleID IS NULL) OR ([R].[ID] = @RoleID)) AND
            ((@RoleName IS NULL) OR ([R].[Name] = @RoleName))
    UNION
    SELECT
            [fU].[ID] [UserRoleID],
            CAST(1 AS bit) [IsUser],
            [fU].[Name] [UserRoleName],
            [fU].[IsHeadOffice] [IsUserHeadOffice],
            [fU].[SiteID] [UserSiteID],
            [fU].[SiteCode] [UserSiteCode],
            [fU].[SiteName] [UserSiteName],
            [fU].[Site] [UserSite],
            [fU].[AreaID] [UserAreaID],
            [fU].[AreaCode] [UserAreaCode],
            [fU].[AreaName] [UserAreaName],
            [fU].[Area] [UserArea],
            [fU].[RegionID] [UserRegionID],
            [fU].[RegionCode] [UserRegionCode],
            [fU].[RegionName] [UserRegionName],
            [fU].[Region] [UserRegion],
            [fU].[TerritoryID] [UserTerritoryID],
            [fU].[TerritoryCode] [UserTerritoryCode],
            [fU].[TerritoryName] [UserTerritoryName],
            [fU].[Territory] [UserTerritory],
            [fU].[CompanyID] [UserCompanyID],
            [fU].[CompanyCode] [UserCompanyCode],
            [fU].[CompanyName] [UserCompanyName],
            [fU].[Company] [UserCompany],
            [fU].[SiteDistributionTypeID] [UserSiteDistributionTypeID],
            [fU].[SiteDistributionTypeName] [UserSiteDistributionTypeName],
            [fU].[IsSiteLotNumberEntryRequired] [IsUserSiteLotNumberEntryRequired],            
            [fU].[StatusID] [UserStatusID],
            [fU].[StatusName] [UserStatusName],
            [fU].[IsDeleted]
        FROM
			[dbo].[fUser]
            (
                @UserID,
                @UserName,
                @IsUserHeadOffice,
                @UserSiteID,
                @UserSiteCode,
                @UserSiteName,
                @UserAreaID,
                @UserAreaCode,
                @UserAreaName,
                @UserRegionID,
                @UserRegionCode,
                @UserRegionName,
                @UserTerritoryID,
                @UserTerritoryCode,
                @UserTerritoryName,
                @UserCompanyID,
                @UserCompanyCode,
                @UserCompanyName,
                @UserSiteDistributionTypeID,
                @IsUserSiteLotNumberEntryRequired,
                @UserStatusID,
                @IsUserDeleted
            ) [fU]
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vUserRoleAll]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vUserRoleAll];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 26 Jul 2016 22:40:06
-- Description   : Provide view (model) to retrieve [dbo].[fUserRole] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vUserRoleAll]
AS
(
    SELECT
            [UserRoleID],
            [IsUser],
            [UserRoleName],
            [IsUserHeadOffice],
            [UserSiteID],
            [UserSiteCode],
            [UserSiteName],
            [UserSite],
            [UserAreaID],
            [UserAreaCode],
            [UserAreaName],
            [UserArea],
            [UserRegionID],
            [UserRegionCode],
            [UserRegionName],
            [UserRegion],
            [UserTerritoryID],
            [UserTerritoryCode],
            [UserTerritoryName],
            [UserTerritory],
            [UserCompanyID],
            [UserCompanyCode],
            [UserCompanyName],
            [UserCompany],
            [UserSiteDistributionTypeID],
            [UserSiteDistributionTypeName],
            [IsUserSiteLotNumberEntryRequired],            
            [UserStatusID],
            [UserStatusName],
            [IsDeleted]
        FROM
			[dbo].[fUserRoleAll]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,                
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
