USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fUserPermissionAll]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fUserPermissionAll];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 26 Jul 2016 22:40:06
-- Description   : Provide function to retrieve [dbo].[UserRole] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fUserPermissionAll]
(
    @UserID int,
    @UserName nvarchar(256)
)
RETURNS TABLE 
AS
RETURN
(
	SELECT
            [U].[ID] [UserID],
            [URP].[PermissionObjectID],
            [U].[Name] [UserName]            
        FROM
            [dbo].[User] [U] INNER JOIN
            [dbo].[UserRole] [UR] ON ([UR].[UserID] = [U].[ID]) INNER JOIN
            [dbo].[UserRolePermission] [URP] ON
            (
                [URP].[IsUser] = 0 AND
                [UR].[RoleID] = [URP].[UserRoleID]
            )
        WHERE
            ([U].[StatusID] = 1) AND
            ([U].[IsDeleted] = 0) AND
            ((@UserID IS NULL) OR ([U].[ID] = @UserID)) AND
            ((@UserName IS NULL) OR ([U].[ID] = @UserName))
    UNION
    SELECT
            [U].[ID] [UserID],
            [URP].[PermissionObjectID],
            [U].[Name] [UserName]            
        FROM                    
            [dbo].[User] [U] INNER JOIN
            [dbo].[UserRolePermission] [URP] ON
            (
                [URP].[IsUser] = 1 AND
                [U].[ID] = [URP].[UserRoleID]
            )
        WHERE
            ([U].[StatusID] = 1) AND
            ([U].[IsDeleted] = 0) AND
            ((@UserID IS NULL) OR ([U].[ID] = @UserID)) AND
            ((@UserName IS NULL) OR ([U].[ID] = @UserName))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vUserPermissionAll]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vUserPermissionAll];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 26 Jul 2016 22:40:06
-- Description   : Provide view (model) to retrieve [dbo].[fUserRole] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vUserPermissionAll]
AS
(
    SELECT
            [UserID],
            [UserName],
            [PermissionObjectID]
        FROM
			[dbo].[fUserPermissionAll]
            (
                NULL,
                NULL
            )
);
GO
