USE [IDOS];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[fWarehouse]') AND type IN ( N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[fWarehouse];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:14:36
-- Description   : Provide function to retrieve [dbo].[Warehouse] data.
--
-- NOTE: This Function is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE FUNCTION [dbo].[fWarehouse]
(
    @ID uniqueidentifier,
    @Code nvarchar(10),
    @Name nvarchar(50),
    @SiteID uniqueidentifier,
    @SiteCode nvarchar(10),
    @SiteName nvarchar(50),
    @AreaID int,
    @AreaCode nvarchar(10),
    @AreaName nvarchar(50),
    @RegionID int,
    @RegionCode nvarchar(10),
    @RegionName nvarchar(50),
    @TerritoryID int,
    @TerritoryCode nvarchar(10),
    @TerritoryName nvarchar(50),
    @CompanyID int,
    @CompanyCode nvarchar(10),
    @CompanyName nvarchar(50),
    @SiteDistributionTypeID int,
    @IsSiteLotNumberEntryRequired bit,
    @TypeID int,
    @IsSOAllowed bit,
    @StatusID int,
    @IsDeleted bit
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
            [W].[ID],
            [W].[Code],
            [W].[Name],
            [dbo].[fCodeNameFormatter]
            (
                [W].[Code],
                (SELECT CASE WHEN [W].[TypeID] = 1 THEN '[' + [fSL].[Name] + '] ' ELSE '' END) + [W].[Name]
            ) [Warehouse],
            [W].[SiteID],
            [fS].[Code] [SiteCode],
            [fS].[Name] [SiteName],
            [fS].[Site],
            [fS].[AreaID],
            [fS].[AreaCode],
            [fS].[AreaName],
            [fS].[Area],            
            [fS].[RegionID],
            [fS].[RegionCode],
            [fS].[RegionName],
            [fS].[Region],
            [fS].[TerritoryID],
            [fS].[TerritoryCode],
            [fS].[TerritoryName],
            [fS].[Territory],
            [fS].[CompanyID],
            [fS].[CompanyCode],
            [fS].[CompanyName],
            [fS].[Company],
            [fS].[DistributionTypeID] [SiteDistributionTypeID],
            [fS].[DistributionTypeName] [SiteDistributionTypeName],
            [fS].[IsLotNumberEntryRequired] [IsSiteLotNumberEntryRequired],
            [W].[TypeID],
            [fSL].[Name] [TypeName],
            [W].[IsSOAllowed],
            [W].[StatusID],
            [fSL2].[Name] [StatusName],
            [W].[SAPCode],
            [W].[CreatedDate],
            [W].[CreatedByUserID],
            [CU].[Name] [CreatedByUserName],
            [W].[ModifiedDate],
            [W].[ModifiedByUserID],
            [MU].[Name] [ModifiedByUserName],
            [W].[IsDeleted]
        FROM
			[dbo].[Warehouse] [W] INNER JOIN
            [dbo].[fSite]
            (
                @SiteID,
                @SiteCode,
                @SiteName,
                @AreaID,
                @AreaCode,
                @AreaName,
                @RegionID,
                @RegionCode,
                @RegionName,
                @TerritoryID,
                @TerritoryCode,
                @TerritoryName,
                @CompanyID,
                @CompanyCode,
                @CompanyName,
                @SiteDistributionTypeID,
                @IsSiteLotNumberEntryRequired,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            ) [fS] ON ([W].[SiteID] = [fS].[ID]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'WarehouseType',
                NULL,
                NULL,
                NULL
            ) [fSL] ON ([W].[TypeID] = [fSL].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[fSystemLookup]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                'WarehouseStatus',
                NULL,
                NULL,
                NULL
            ) [fSL2] ON ([W].[StatusID] = [fSL2].[Value_Int32]) LEFT OUTER JOIN
            [dbo].[User] [CU] ON ([W].[CreatedByUserID] = [CU].[ID]) LEFT OUTER JOIN
            [dbo].[User] [MU] ON ([W].[ModifiedByUserID] = [MU].[ID])
		WHERE
            ((@ID IS NULL) OR ([W].[ID] = @ID)) AND
            ((@Code IS NULL) OR ([W].[Code] LIKE '%' + @Code + '%')) AND
            ((@Name IS NULL) OR ([W].[Name] LIKE '%' + @Name + '%')) AND
            ((@TypeID IS NULL) OR ([W].[TypeID] = @TypeID)) AND
            ((@IsSOAllowed IS NULL) OR ([W].[IsSOAllowed] = @IsSOAllowed)) AND
            ((@StatusID IS NULL) OR ([W].[StatusID] = @StatusID)) AND
            ((@IsDeleted IS NULL) OR ([W].[IsDeleted] = @IsDeleted))
);
GO



IF EXISTS(SELECT * FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[vWarehouse]') AND type IN ( N'V' ))
    DROP VIEW [dbo].[vWarehouse];
GO

-- ===================================================================================
-- Author        : System
-- Created date  : 18 Mar 2016 00:14:36
-- Description   : Provide view (model) to retrieve [dbo].[fWarehouse] data.
--
-- NOTE: This View is initially generated by system and can be modified following
--       the requirement.
-- ===================================================================================

CREATE VIEW [dbo].[vWarehouse]
AS
(
    SELECT
            [ID],
            [Code],
            [Name],
            [Warehouse],
            [SiteID],
            [SiteCode],
            [SiteName],
            [Site],
            [AreaID],
            [AreaCode],
            [AreaName],
            [Area],
            [RegionID],
            [RegionCode],
            [RegionName],
            [Region],
            [TerritoryID],
            [TerritoryCode],
            [TerritoryName],
            [Territory],
            [CompanyID],
            [CompanyCode],
            [CompanyName],
            [Company],
            [SiteDistributionTypeID],
            [SiteDistributionTypeName],
            [IsSiteLotNumberEntryRequired],
            [TypeID],            
            [TypeName],
            [IsSOAllowed],
            [StatusID],            
            [StatusName],
            [SAPCode],
            [CreatedDate],
            [CreatedByUserID],
            [CreatedByUserName],
            [ModifiedDate],
            [ModifiedByUserID],
            [ModifiedByUserName],
            [IsDeleted]
        FROM
			[dbo].[fWarehouse]
            (
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL
            )
);
GO
