// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:14
// Description   : UserDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Dismoyo.Data;
using Dismoyo.Web.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Dismoyo.Ciptoning.Data
{

    public partial class UserDataProvider : DefaultTableDataProvider<User>, IUserDataProvider
    {

        #region Methods

        public User GetDataByName(string name)
        {
            var user = GetData().SingleOrDefault(p => p.Name.Equals(name, StringComparison.OrdinalIgnoreCase));

            return user;
        }

        public IList<User> GetDataBySiteID(Guid siteID)
        {
            var users = GetData().Where(p => (p.SiteID == siteID)).ToList();

            return users;
        }


        protected override void OnBeginInsertData(BeginOperationDataEventArgs<User> e)
        {
            e.Data.CreatedDate = DefaultDataContext.GetDBServerUtcDateTime();
            if (HttpContext.Current.User.Identity.IsAuthenticated)
                e.Data.CreatedByUserID = ((BasicGenericIdentity<IvUser>)HttpContext.Current.User.Identity).UserData.ID;

            base.OnBeginInsertData(e);
        }

        protected override void OnBeginUpdateData(BeginOperationDataEventArgs<User> e)
        {
            e.Data.ModifiedDate = DefaultDataContext.GetDBServerUtcDateTime();
            if (HttpContext.Current.User.Identity.IsAuthenticated)
                e.Data.ModifiedByUserID = ((BasicGenericIdentity<IvUser>)HttpContext.Current.User.Identity).UserData.ID;

            base.OnBeginUpdateData(e);
        }

        #endregion

    }

}
