// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:57
// Description   : vUserRoleDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Dismoyo.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vUserRoleDataProvider : DefaultViewDataProvider<vUserRole>, IvUserRoleDataProvider
    {

        #region Methods

        protected override void OnInsertData(vUserRole obj)
        {
            var userRoleDataProvider = DataConfiguration.GetDefaultDataProvider<IUserRoleDataProvider>();

            var userRole = new UserRole();

            userRole.RoleID = obj.RoleID;
            userRole.UserID = obj.UserID;

            userRoleDataProvider.InsertData(userRole);
        }

        protected override void OnUpdateData(vUserRole obj)
        {
            
        }

        protected override void OnDeleteData(vUserRole obj)
        {
            var userRoleDataProvider = DataConfiguration.GetDefaultDataProvider<IUserRoleDataProvider>();

            var userRole = userRoleDataProvider.GetData(obj.RoleID, obj.UserID);

            userRoleDataProvider.DeleteData(userRole);
        }

        #endregion

    }

}
