// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:57
// Description   : vPromoMaterialActivityEntityTypeConfig partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Data.Entity.ModelConfiguration;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vPromoMaterialActivityEntityTypeConfig : EntityTypeConfiguration<vPromoMaterialActivity>
    {

        #region Constructors

        public vPromoMaterialActivityEntityTypeConfig()
        {
            HasRequired(p => p.Parent)
                .WithMany(q => q.ChildPromoMaterialActivities)
                .HasForeignKey(p => p.SalesmanCallID)
                .WillCascadeOnDelete(false);
        }

        #endregion

    }

}
