// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:57
// Description   : vStockTransferDetailsDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vStockTransferDetailsDataProvider : DefaultViewDataProvider<vStockTransferDetails>, IvStockTransferDetailsDataProvider
    {

        #region Methods

        protected override void OnInsertData(vStockTransferDetails obj, bool useTransaction)
        {
            var stockTransferDetailsDataProvider = DataConfiguration.GetDefaultDataProvider<IStockTransferDetailsDataProvider>();

            var stockTransferDetails = new StockTransferDetails();

            stockTransferDetails.DocumentID = obj.DocumentID;
            stockTransferDetails.ProductID = obj.ProductID;
            stockTransferDetails.ProductLotID = obj.ProductLotID;

            stockTransferDetails.QtyOnHandGood = obj.QtyOnHandGood;
            stockTransferDetails.QtyOnHandHold = obj.QtyOnHandHold;
            stockTransferDetails.QtyOnHandBad = obj.QtyOnHandBad;

            stockTransferDetails.QtyConvLGood = obj.QtyConvLGood;
            stockTransferDetails.QtyConvMGood = obj.QtyConvMGood;
            stockTransferDetails.QtyConvSGood = obj.QtyConvSGood;
            stockTransferDetails.QtyConvLHold = obj.QtyConvLHold;
            stockTransferDetails.QtyConvMHold = obj.QtyConvMHold;
            stockTransferDetails.QtyConvSHold = obj.QtyConvSHold;
            stockTransferDetails.QtyConvLBad = obj.QtyConvLBad;
            stockTransferDetails.QtyConvMBad = obj.QtyConvMBad;
            stockTransferDetails.QtyConvSBad = obj.QtyConvSBad;

            stockTransferDetails.QtyGood = obj.QtyGood;
            stockTransferDetails.QtyHold = obj.QtyHold;
            stockTransferDetails.QtyBad = obj.QtyBad;

            stockTransferDetailsDataProvider.InsertData(stockTransferDetails, useTransaction);
        }

        protected override void OnUpdateData(vStockTransferDetails obj, bool useTransaction)
        {
            var stockTransferDetailsDataProvider = DataConfiguration.GetDefaultDataProvider<IStockTransferDetailsDataProvider>();

            var stockTransferDetails = stockTransferDetailsDataProvider.GetData(obj.DocumentID, obj.ProductID,
                obj.ProductLotID);

            stockTransferDetails.QtyOnHandGood = obj.QtyOnHandGood;
            stockTransferDetails.QtyOnHandHold = obj.QtyOnHandHold;
            stockTransferDetails.QtyOnHandBad = obj.QtyOnHandBad;

            stockTransferDetails.QtyConvLGood = obj.QtyConvLGood;
            stockTransferDetails.QtyConvMGood = obj.QtyConvMGood;
            stockTransferDetails.QtyConvSGood = obj.QtyConvSGood;
            stockTransferDetails.QtyConvLHold = obj.QtyConvLHold;
            stockTransferDetails.QtyConvMHold = obj.QtyConvMHold;
            stockTransferDetails.QtyConvSHold = obj.QtyConvSHold;
            stockTransferDetails.QtyConvLBad = obj.QtyConvLBad;
            stockTransferDetails.QtyConvMBad = obj.QtyConvMBad;
            stockTransferDetails.QtyConvSBad = obj.QtyConvSBad;

            stockTransferDetails.QtyGood = obj.QtyGood;
            stockTransferDetails.QtyHold = obj.QtyHold;
            stockTransferDetails.QtyBad = obj.QtyBad;

            stockTransferDetailsDataProvider.UpdateData(stockTransferDetails, useTransaction);
        }

        #endregion

    }

}
