// ===================================================================================
// Author        : System
// Created date  : 2014-05-23 00:00:00 
// Description   : IAuthorizationAccessTokenDataProvider partial interface.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Dismoyo.Data;
using System;
using System.Collections.Generic;

namespace Dismoyo.Ciptoning.Data
{

    public partial interface IAuthorizationAccessTokenDataProvider : IDataProvider<AuthorizationAccessToken>
    {

        #region Methods

        AuthorizationAccessToken CreateToken(int userID, string deviceID, double minutes);
        bool IsActiveToken(Guid accessToken, int userID, string deviceID);

        #endregion

    }

}
