// ===================================================================================
// Author        : System
// Created date  : 02 Mei 2016 21:23:35
// Description   : vSystemParameterDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vSystemParameterDataProvider : DefaultViewDataProvider<vSystemParameter>, IvSystemParameterDataProvider
    {
        
        #region Methods

        protected override void OnInsertData(vSystemParameter obj)
        {
            var systemParameterDataProvider = DataConfiguration.GetDefaultDataProvider<ISystemParameterDataProvider>();
            
            var systemParameter = new SystemParameter();

            systemParameter.ID = obj.ID;
            systemParameter.Description = obj.Description;
            systemParameter.Value = obj.Value;
            
            systemParameterDataProvider.InsertData(systemParameter);
        }

        protected override void OnUpdateData(vSystemParameter obj)
        {
            var systemParameterDataProvider = DataConfiguration.GetDefaultDataProvider<ISystemParameterDataProvider>();

            var systemParameter = systemParameterDataProvider.GetData(obj.ID);

            systemParameter.Description = obj.Description;
            systemParameter.Value = obj.Value;

            systemParameterDataProvider.UpdateData(systemParameter);
        }

        #endregion
        
    }

}
