// ===================================================================================
// Author        : System
// Created date  : 10 Apr 2016 13:37:37
// Description   : vRoutePlanDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class vRoutePlanDataProvider : DefaultViewDataProvider<vRoutePlan>, IvRoutePlanDataProvider
    {

        #region Methods

        protected override void OnInsertData(vRoutePlan obj)
        {
            var routePlanDataProvider = DataConfiguration.GetDefaultDataProvider<IRoutePlanDataProvider>();

            var routePlan = new RoutePlan();

            routePlan.SalesmanID = obj.SalesmanID;
            routePlan.CustomerID = obj.CustomerID;
            routePlan.WeekID = obj.WeekID;
            routePlan.DayID = obj.DayID;

            routePlanDataProvider.InsertData(routePlan);
        }

        protected override void OnUpdateData(vRoutePlan obj)
        {
            var routePlanDataProvider = DataConfiguration.GetDefaultDataProvider<IRoutePlanDataProvider>();

            var routePlan = routePlanDataProvider.GetData(obj.SalesmanID, obj.CustomerID, obj.WeekID, obj.DayID);

            routePlanDataProvider.UpdateData(routePlan);
        }

        protected override void OnDeleteData(vRoutePlan obj)
        {
            var routePlanDataProvider = DataConfiguration.GetDefaultDataProvider<IRoutePlanDataProvider>();

            var routePlan = routePlanDataProvider.GetData(obj.SalesmanID, obj.CustomerID, obj.WeekID, obj.DayID);

            routePlanDataProvider.DeleteData(routePlan);
        }

        #endregion

    }

}
