// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:14
// Description   : DiscountStrataDetailsDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
using Dismoyo.Data;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class DiscountStrataDetailsDataProvider : DefaultTableDataProvider<DiscountStrataDetails>, IDiscountStrataDetailsDataProvider
    {

        #region Methods

        public IList<DiscountStrataDetails> GetDataByStrataID(int strataID)
        {
            var discountStrataDetails = GetData().Where(p => p.StrataID.Equals(strataID)).ToList();

            return discountStrataDetails;
        }

        #endregion

    }

}
