// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:14
// Description   : SalesmanTargetTargetDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
using Dismoyo.Data;
using System.Web;
using Dismoyo.Web.Security;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class SalesmanTargetDataProvider : DefaultTableDataProvider<SalesmanTarget>, ISalesmanTargetDataProvider
    {

        #region Methods

        protected override void OnBeginInsertData(BeginOperationDataEventArgs<SalesmanTarget> e)
        {
            e.Data.CreatedDate = DefaultDataContext.GetDBServerUtcDateTime();
            if (HttpContext.Current.User.Identity.IsAuthenticated)
                e.Data.CreatedByUserID = ((BasicGenericIdentity<IvUser>)HttpContext.Current.User.Identity).UserData.ID;

            base.OnBeginInsertData(e);
        }

        protected override void OnBeginUpdateData(BeginOperationDataEventArgs<SalesmanTarget> e)
        {
            e.Data.ModifiedDate = DefaultDataContext.GetDBServerUtcDateTime();
            if (HttpContext.Current.User.Identity.IsAuthenticated)
                e.Data.ModifiedByUserID = ((BasicGenericIdentity<IvUser>)HttpContext.Current.User.Identity).UserData.ID;

            base.OnBeginUpdateData(e);
        }

        #endregion

    }

}
