// ===================================================================================
// Author        : System
// Created date  : 29 Feb 2016 12:50:14
// Description   : StockChangesSummaryDataProvider partial class.
//
// Modified date :
// Modified by   :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
using Dismoyo.Data;
//using WebMatrix.WebData;

namespace Dismoyo.Ciptoning.Data
{

    public partial class StockChangesSummaryDataProvider : DefaultTableDataProvider<StockChangesSummary>, IStockChangesSummaryDataProvider
    {

        #region Methods

        public IList<StockChangesSummary> GetDataByDocumentID(Guid documentID)
        {
            var stockChangesDetails = GetData().Where(p => p.DocumentID.Equals(documentID)).ToList();

            return stockChangesDetails;
        }


        public override void DeleteData(StockChangesSummary obj, bool useTransaction)
        {
            var stockChangesDetailsDataProvider =
                DataConfiguration.GetDefaultDataProvider<IStockChangesDetailsDataProvider>();

            var deleteChilds = stockChangesDetailsDataProvider.GetDataByDocumentIDAndProductID(
                obj.DocumentID, obj.ProductID);
            foreach (var child in deleteChilds)
                stockChangesDetailsDataProvider.DeleteData(child, useTransaction);

            base.DeleteData(obj, useTransaction);
        }

        #endregion

    }

}
